Dhammapada_Wickramanayaka={
  "title": "Treasury Of Truth, Illustrated Dhammapada",
  "year": 1993,
  "author": "P. Wickramanayaka",
  "source": "vẽ minh hoạ theo bản tiếng Pali",
  "link": "http://www.buddhanet.net/dhammapada/",
  "link": "https://www.urbandharma.org/pdf/DhammapadaIllustrated.pdf",
  "imgdir": "Dhammapada-Wickramanayaka/720px",
  "image_link": "https://tienvnguyen.net/a1122/treasury-of-truth-illustrated-dhammapada-chapter-01-26-kho-bau-su-that-kinh-phap-cu-minh-hoa-pham-01-26-",
  "thumbnails": "http://www.buddhanet.net/dhammapada/images/IDP423@50dpiRGB.jpg",
  "images": "https://tienvnguyen.net/images/file/eNami7M51QgBAIAP/dhp423-b.jpg",
  "preface": "In the religious literature of the world that pre-eminently represents man's continued urge towards the spiritual, The Dhammapada occupies a place of high distinction. Its sacred contents have unceasingly influenced human thought, holding aloft the torch of knowledge to light the path of men in their quest for truth and inner solace. In the current global context, The Dhammapada has evolved into the stature of an outstanding treasure of the common human heritage, transcending man-made borders and boundaries and rising above limitations imposed by time. The Dhammapada, in short, is among the handful of gems of sacred literature esteemed by people all over the globe, irrespective of cleavages of creed, faith and variegated religious professions.\n\nThe primary purpose of the present English rendering of The Dhammapada, under the title The Treasury of Truth is to take the word of the Buddha further afield, in a verbal and visual idiom that will have greater appeal to the modern mind. The eternal wisdom embodied in the verses of The Dhammapada holds within it the potential to bring tranquility to men and women troubled by the stresses and conflicts of life as it is being lived by a good majority of the people in today's world of disharmony and distress. In spite of the deeply felt need of the contemporary world, to yearn for peace, solace and tranquility, the word of the Buddha has not generally been presented in a frequency that throbs to the rhythm of the modern mind-set.\n\nThe rationale of the present translation, therefore, is to bring The Dhammapada closer to generations who are being brought up right round the globe on a staple fare of visual messages emanating in multiple colour, from the world's visual primary media - both of electronic and print categories.\n\nIn consequence, The Treasury of Truth has, as its most prominent core feature a series of 423 specially commissioned illustrations, at the rate of one per stanza in The Dhammapada. This veritable gallery of Dhammapada illustrations is the creation of artist P. Wickramanayaka, a well-known Sri Lankan professional. He was assisted by artist K. Wi-Jayakeerthi. The illustrations bear witness to the wisdom encapsulated in the Chinese proverb, “One picture is worth ten thousand words”.\n\n[...]\n\nI am happy to share with all, the sense of profound joy I experience in being able to present this Treasury of Perennial Transcendental Wisdom to the world. May this work prove a constant companion to all, guiding them along the path of righteousness and virtue towards the ultimate goal of Total Bliss.\n\nVen. Weragoda Sarada Maha Thero\nauthor - Chief Monk,\nSBMC, Singapore\n27th November, 1993"
}
