PhapCu_ThienSieu={
	"title": "KINH PHÁP CÚ (DHAMMAPADA)",
	"year": 1959,
	"author": "Thích Thiện Siêu (Trí Đức)",
	"source": "dịch từ chữ Hán",
    "link": "https://thuvienhoasen.org/images/file/ZSqWfkb40QgQAJh6/kinh-phap-cu-19-10-2014-.pdf",
	"link": "http://www.chualientri.com/index.php/thu-vien/sach-phat-giao/book/16-kinh-phap-cu-ht-thich-thien-sieu",
	"preface": "PHÁP CÚ là quyển Kinh chọn lọc những lời dạy của đức Phật Thích-ca Mâu-ni khi còn tại thế. Suốt trong 45 năm thuyết pháp, đức Phật đã nói rất nhiều Pháp ngữ, bao gồm nghĩa lý thâm thiết để cởi mở nghiệp khổ cho chúng sanh mà đưa họ đến Niết-bàn an lạc. Những giáo pháp ấy, ngay ba tháng sau khi Phật diệt độ, được các vị cao đồ tập họp Ðại hội Kết tập Kinh điển lần đầu tiên, tập thành Tam tạng để truyền lại cho hậu thế noi theo. Đồng thời, những câu dạy ngắn gọn đầy ý nghĩa của Phật trong hơn ba trăm trường hợp giáo hóa khác nhau, cũng được kết tập thành kinh Pháp cú này và lưu truyền mãi cho đến ngày nay. \n\n Thường thường chúng ta thấy trong báo chí, sách vở của các nhà nghiên cứu Phật học hay trích dẫn những câu nói ngắn gọn nhưng rất có giá trị của đức Phật, là phần nhiều từ ở Kinh này mà ra. \n\n Kinh Pháp cú gồm 26 phẩm, 423 câu (bài kệ), là quyển thứ hai trong 15 quyển thuộc Kinh Tiểu Bộ (Khuddaka-Nikāya) trong Kinh tạng Pāli và được dịch ra rất nhiều thứ tiếng ở Á châu và Âu-Mỹ. Theo chỗ chúng tôi được biết, những người đầu tiên dịch kinh Pháp cú kể có học giả Đan-mạch Viggo Fausbøll (Fausböll) dịch sang tiếng La-tinh năm 1855; học giả Max F. Mueller sang Anh ngữ năm 1881; giáo sư E.W. Burlingame thì chuyển ngữ bản Sớ giải, sau này được giáo sư Charles Rockwell Lanman (1850-1941) giảo đính và đại học Havard tại Mỹ quốc xuất bản năm 1901; giáo sư Sanskrit Phước Đảo Trực tứ lang (Fukushima Naoshiro, 福島直四郎, 1899-1979), dịch sang Nhật ngữ; năm 1862, lần đầu tiên Dhammapada được dịch ra tiếng Đức, v.v. Ngoài ra, lại còn có các bản Hán dịch rất cổ với danh đề Pháp cú kinh, Pháp tập yếu tụng v.v. Cho đến nay riêng phần Anh ngữ đã có gần 80 bản dịch, ngoài các học giả kể trên còn có những cao tăng tôn túc như Nārada MahāThera, Acharya Buddharakkhita, v.v. \n\n Xưa nay các nước Phật giáo Nam truyền như Tích-lan, Miến-điện v.v., và Phật giáo Tây tạng, đều đặc biệt tôn vinh Pháp cú làm bộ kinh nhật tụng quý báu; hàng Tăng giới ít ai không biết, không thuộc, không hành trì, và hàng cư sĩ cũng lấy đó phụng hành để sống một đời sống an lành thanh khiết. \n\n Riêng tại Việt Nam, lâu nay thấy có trích dẫn, nhưng chưa ai dịch hết toàn bộ.  Nay nhân dịp may, tôi gặp được bản kinh Pháp cú do Pháp sư Liễu Tham vừa dịch từ nguyên bản Pāli ra Hán văn, với sự tham khảo chú thích rạch ròi, có thể giúp chúng ta đọc như đọc thẳng bản văn Pāli, nên tôi kính cẩn dịch ra để góp vào kho Phật kinh tiếng Việt. \n\n Gần đây Hoà thượng Thích Minh Châu cũng đã dịch toàn văn kinh Pháp cú từ bản Pāli và in song song cả hai thứ chữ Việt-Pāli, tạo thuận lợi rất nhiều cho việc học hỏi thêm chính xác và sâu sắc hơn đối với lời Phật dạy. Do vậy mà lần tái bản này, có thêm bản Anh ngữ của ngài Nārada MahāThera, được xem là chính xác nhất, trình bày cùng với bản văn vần thi kệ của Hoà thượng Thích Minh Châu, lập thành một quyển kinh Pháp cú tương đối hoàn chỉnh (Pāli-Việt-HánAnh), thực hiện đầy đủ hy vọng xưa nay của tôi, để làm thủ sách cho mọi giới. \n\n Đọc xong kinh Pháp cú, độc giả sẽ thấy trong đó gồm những lời dạy về triết lý cho cả hai giới xuất gia và tại gia. Những lời dạy cho hàng xuất gia tất nhiên không bao hàm tại gia, nhưng những lời dạy cho hàng tại gia đương nhiên trùm cả hàng xuất gia. Do đó dù ở hạng nào, đọc cuốn kinh này, cũng thu thập được nhiều ích lợi thanh cao. \n\n Tôi tin rằng những lời dạy giản dị mà thâm thúy trong kinh Pháp cú có thể làm cho chúng ta mỗi khi đọc đến thấy một niềm siêu thoát lâng lâng tràn ngập tâm hồn, và những đức tính từ bi hỉ xả, bình tĩnh, lạc quan vươn lên tỏa rộng giữa những ngang trái, hẹp hòi, khổ đau, điên đảo của cuộc thế vô thường. \n\n Bản dịch này tôi đã xuất bản lần đầu tiên năm 1959 (với pháp tự Trí Đức) và sau đó đã nhiều lần tái bản. Nay, lại có thiện duyên, bản dịch này được tái bản để pháp bảo lưu thông rộng rãi. \n\nPhật lịch 2542, ngày Phật Thành Đạo\n THÍCH THIỆN SIÊU",
	"chapters": {
		"1": {
			"title": "I. Phẩm Song Yếu",
			"from_verse": 1,
			"to_verse": 20
		},
		"2": {
			"title": "II. Phẩm Không Phóng Dật",
			"from_verse": 21,
			"to_verse": 32
		},
		"3": {
			"title": "III. Phẩm Tâm",
			"from_verse": 33,
			"to_verse": 43
		},
		"4": {
			"title": "IV. Phẩm Hoa",
			"from_verse": 44,
			"to_verse": 59
		},
		"5": {
			"title": "V. Phẩm Ngu",
			"from_verse": 60,
			"to_verse": 75
		},
		"6": {
			"title": "VI. Phẩm Hiền Trí",
			"from_verse": 76,
			"to_verse": 89
		},
		"7": {
			"title": "VII. Phẩm A-la-hán",
			"from_verse": 90,
			"to_verse": 99
		},
		"8": {
			"title": "VIII. Phẩm Ngàn",
			"from_verse": 100,
			"to_verse": 115
		},
		"9": {
			"title": "IX. Phẩm Ác",
			"from_verse": 116,
			"to_verse": 128
		},
		"10": {
			"title": "X. Phẩm Hình Phạt",
			"from_verse": 129,
			"to_verse": 145
		},
		"11": {
			"title": "XI. Phẩm Già",
			"from_verse": 146,
			"to_verse": 156
		},
		"12": {
			"title": "XII. Phẩm Tự Ngã",
			"from_verse": 157,
			"to_verse": 166
		},
		"13": {
			"title": "XIII. Phẩm Thế Gian",
			"from_verse": 167,
			"to_verse": 178
		},
		"14": {
			"title": "XIV. Phẩm Phật-đà",
			"from_verse": 179,
			"to_verse": 196
		},
		"15": {
			"title": "XV. Phẩm An Lạc",
			"from_verse": 197,
			"to_verse": 208
		},
		"16": {
			"title": "XVI. Phẩm Thân Ái",
			"from_verse": 209,
			"to_verse": 220
		},
		"17": {
			"title": "XVII. Phẩm Sân Hận",
			"from_verse": 221,
			"to_verse": 234
		},
		"18": {
			"title": "XVIII. Phẩm Ô Uế",
			"from_verse": 235,
			"to_verse": 255
		},
		"19": {
			"title": "XIX. Phẩm Pháp Trụ",
			"from_verse": 256,
			"to_verse": 272
		},
		"20": {
			"title": "XX. Phẩm Đạo",
			"from_verse": 273,
			"to_verse": 289
		},
		"21": {
			"title": "XXI. Phẩm Tạp Lục",
			"from_verse": 290,
			"to_verse": 305
		},
		"22": {
			"title": "XXII. Phẩm Địa Ngục",
			"from_verse": 306,
			"to_verse": 319
		},
		"23": {
			"title": "XXIII. Phẩm Voi",
			"from_verse": 320,
			"to_verse": 333
		},
		"24": {
			"title": "XXIV. Phẩm Tham Ái",
			"from_verse": 334,
			"to_verse": 359
		},
		"25": {
			"title": "XXV. Phẩm Tỳ-kheo",
			"from_verse": 360,
			"to_verse": 382
		},
		"26": {
			"title": "XXVI. Phẩm Bà-la-môn",
			"from_verse": 383,
			"to_verse": 423
		}
	},
    "verses": {
"1": "Trong các pháp(2), tâm dẫn đầu, tâm làm chủ, tâm tạo tác. Nếu nói hoặc làm với tâm ô nhiễm, sự khổ sẽ theo nghiệp kéo đến như bánh xe lăn theo chân con vật kéo(3).",
"2": "Trong các pháp, tâm dẫn đầu, tâm làm chủ, tâm tạo tác. Nếu nói hoặc làm với tâm thanh tịnh, sự vui sẽ theo nghiệp kéo đến như bóng theo hình.",
"3": "“Nó lăng mạ tôi, đánh đập tôi, phá hoại tôi, cướp đoạt tôi”, ai còn ôm ấp tâm niệm ấy, thì sự oán hận không thể dứt.",
"4": "“Nó lăng mạ tôi, đánh đập tôi, phá hoại tôi, cướp đoạt tôi”, ai bỏ được tâm niệm ấy, thì sự oán hận tự dứt.",
"5": "Ở thế gian này, chẳng phải hận thù trừ được hận thù, chỉ có từ bi trừ được hận thù. Đó là định luật ngàn thu (4).",
"6": "Người kia(5) không hiểu rằng: ”Chúng ta săp bị hủy diệt(6)” (mới phí sức tranh luận hơn thua). Nếu họ hiểu rõ điều đó thì chẳng còn tranh luận nữa.",
"7": "Người chỉ muốn sống khoái lạc(7), không nhiếp hộ các căn, ăn uống vô độ, biếng nhác chẳng tinh cần, người ấy thật dễ bị ma(8) nhiếp phục, như cành mềm trước cơn gió lốc.",
"8": "Người nguyện ở trong cảnh chẳng khoái lạc (9), khéo nhiếp hộ các căn, ăn uống tiết độ, vững tin và siêng năng, ma không dễ gì thắng họ, như gió thổi núi đá.",
"9": "Mặc áo cà sa mà không rời bỏ cấu uế (10), không thành thật khắc kỷ, thà chẳng mặc còn hơn.",
"10": "Rời bỏ các cấu uế, khéo giữ gìn giới luật, khắc kỷ và chân thành, người như thế đáng mặc ao cà sa.",
"11": "Phi chơn(11) tưởng là chân thật, chơn thật(12) lại thấy là phi chơn, cứ tư duy một cách tà vạy, người như thế không thể đạt đến chân thật.",
"12": "Chơn thật nghĩ là chơn thật, phi chơn biết là phi chơn, cứ tư duy một cách đúng đắn, người như thế mau đạt đến chân thật.",
"13": "Nhà lợp không kín ắt bị mưa dột; cũng vậy, người tâm không khéo tu ắt bị tham dục lọt vào.",
"14": "Nhà khéo lợp kín ắt không bị mưa dột; cũng vậy, người tâm khéo tu ắt không bị tham dục lọt vào.",
"15": "Đời này chỗ này buồn, chết rồi chỗ khác buồn, kẻ làm điều ác nghiệp, cả hai nơi đều lo buồn, vì thấy ác nghiệp mình gây ra, kẻ kia sinh buồn than khổ não.",
"16": "Đời này chỗ này vui, chết rồi chỗ khác vui, kẻ làm điều thiện nghiệp, cả hai nơi đều vui, vì thấy thiện nghiệp mình đã làm, kẻ kia sinh ra an vui, cực vui.",
"17": "Đời này chổ này khổ, chết rồi chỗ khác khổ, kẻ gây điều ác nghiệp, cả hai nơi đều khổ, buồn rằng “ta đã tạo ác” phải đọa vào ác thú khổ hơn(13).",
"18": "Đời này chỗ này hoan hỷ, chết rồi chỗ khác hoan hỷ, kẻ tu hành phước nghiệp, cả hai nơi đều hoan hỷ, mừng rằng “ta đã tạo phước” được sinh vào cõi lành hoan hỷ hơn.",
"19": "Dù tụng nhiều kinh mà buông lung không thực hành thì chẳng huởng được phần ích lợi của Sa-môn, khác nào kẻ chăn bò thuê, lo đếm bò cho người (14).",
"20": "Tuy tụng ít kinh mà thường y giáo hành trì, hiểu biết chân chánh, từ bỏ tham sân, si, tâm hiền lành, thanh tịnh, giải thoát, xa bỏ thế dục, thì dù ở cõi này hay cõi khác, người kia vẫn hưởng phần ích lợi của Sa-môn.",
"21": "Không buông lung đưa tới cõi bất tử (15), buông lung đưa tới cõi tử vong, người không buông lung thì không chết, kẻ buông lung thì sống như thây ma(16).",
"22": "Kẻ trí biết chắc điều ấy(17) nên gắng làm theo sự không buông lung. Không buông lung thì đặng an vui trong các cõi thánh(18).",
"23": "Nhờ kiên nhẫn, dõng mãnh tu thiền định(19), kẻ trí được giải thoát an ổn, chứng nhập vô thượng Niết-bàn.",
"24": "Không buông lung, cố gắng, hăng hái, chánh niệm, khắc kỷ theo tịnh hạnh, sinh hoạt đúng như pháp, thì tiếng lành càng tăng trưởng.",
"25": "Bằng sự cố gắng, hăng hái, không buông lung, tự khắc chế lấy mình, kẻ trí tự tạo cho mình hòn đảo(20) chẳng còn ngọn thủy triều(21) nào nhận chìm được.",
"26": "Người ám độn ngu si đắm chìm trong buông lung, nhưng kẻ trí lại chăm giữ tâm không buông lung, như người giàu chăm giữ của báu.",
"27": "Chớ đắm chìm theo buông lung, chớ mê say dục lạc; hãy tỉnh giác tu thiền, mới mong đặng đại an lạc.",
"28": "Nhờ trừ hết buông lung, kẻ trí không còn lo sợ gì. Bậc thánh hiền bước lên lầu trí tuệ, nhìn thấy kẻ ngu si còn nhiều lo sợ, như được lên núi cao, cúi nhìn muôn vật trên mặt đất.",
"29": "Tinh tấn giữa đám người buông lung, tỉnh táo giữa đám người mê ngủ, kẻ trí như con tuấn mã thẳng tiến, bỏ lại sau con ngựa gầy hèn.",
"30": "Nhờ không buông lung, Ma già(22) được làm chủ chư thiên. Không buông lung được nguời khen ngợi, buông lung bị người khinh chê.",
"31": "Tỷ-kheo thường ưa không buông lung, hoặc sợ thấy sự buông lung, ta ví họ như ngọn lửa hồng đốt thiêu tất cả kiết sử(23) lớn nhỏ.",
"32": "Tỷ-kheo nào thường ưa không buông lung, hoặc sợ thấy sự buông lung, ta biết họ gần tới Niết-bàn, nhất định không bị đọa lạc dễ dàng như trước.",
"33": "Tâm kẻ phàm phu thường dao động hốt hoảng khó chế phục, nhưng kẻ trí chế phục tâm làm cho chính trực dễ dàng, như thợ khéo uốn nắn mũi tên.",
"34": "Như cá bị quăng lên bờ, sợ sệt vùng vẫy thế nào, thì cũng như thế, các người hãy đem tâm lo sợ, phấn đấu để mau thoát khỏi cảnh giới ác ma.",
"35": "Tâm phàm phu cứ xoay vần theo ngũ dục, dao động không dễ nắm bắt. Chỉ những người nào đã điều phục được tâm mình mới được yên vui.",
"36": "Tâm phàm phu cứ xoay vần theo ngũ dục, biến hóa u ẩn khó thấy, nhưng người trí lại phòng hộ tâm mình, và được yên vui nhờ tâm phòng hộ ấy.",
"37": "Tâm phàm phu cứ lén lút đi một mình, rất xa, vô hình vô dạng, như ẩn náu hang sâu(24); ai điều phục được tâm, thì giải thoát khỏi vòng ma trói buộc.",
"38": "Người tâm không an định, không hiểu biết Chánh pháp, lòng tin không kiên cố, thì trí tuệ khó thành.",
"39": "Người tâm đã thanh tịnh, không còn các hoặc loạn, vượt trên thiện và ác(25), là người giác ngộ chẳng sợ hãi.",
"40": "Hãy biết thân này mong manh như đồ gốm, giam giữ tâm ngươi như thành quách, ngươi hãy đánh dẹp ma quân với thanh huệ kiếm và giữ phần thắng lợi (26), chớ sanh tâm đắm trước (27).",
"41": "Thân này thật không bao lâu sẽ ngủ một giấc dài dưới ba thước đất, vô ý thức, bị vứt bỏ như khúc cây vô dụng.(28)",
"42": "Cái hại của kẻ thù gây ra cho kẻ thù hay oan gia đối với oan gia, không bằng cái hại của tâm niệm hướng về hạnh tà ác(29) gây ra cho mình.",
"43": "Chẳng phải cha mẹ hay bà con nào hết, nhưng chính tâm niệm hướng về hành vi chánh thiện(30) làm cho mình cao thượng hơn.",
"44": "Ai chinh phục(32) địa giới(33), diêm ma giới(34), thiên giới(35), và ai khéo giảng Pháp cú (36) như người thợ khéo(37) nhặt hoa làm tràng?",
"45": "Bậc hữu học(38) chinh phục địa giới, diêm ma giới, thiên giới và khéo giảng Pháp cú như người thợ khéo nhặt hoa làm tràng(39).",
"46": "Nên biết thân này là pháp huyễn hóa như bọt nổi, để bẻ gãy mũi tên cám dỗ của ma quân(40) mà thoát ngoài vòng dòm ngó của tử thần.",
"47": "Như nước lũ cuốn phăng những xóm làng say ngủ(41), tử thần sẽ lôi phăng đi những người sinh tâm ái trước những bông hoa dục lạc mình vừa góp nhặt được.",
"48": "Cứ sinh tâm ái trước, tham luyến mãi những bông hoa(42) dục lạc mà mình vừa góp nhặt được, đó chính là cơ hội tốt cho tử thần lôi đi.",
"49": "Hàng Sa-môn (Mâu ni)(43) đi vào xóm làng khất thực, ví như con ong đi kiếm hoa, chỉ lấy mật rồi đi chứ không làm tổn thương về hương sắc.",
"50": "Chớ nên dòm ngó lỗi người, chớ nên coi họ đã làm hay không làm(44); chỉ nên ngó lại hành động của mình, coi đã làm được gì hay chưa làm được gì.",
"51": "Như thứ hoa đẹp chỉ phô trương màu sắc mà chẳng có hương thơm, những người chỉ biết nói điều lành mà không làm điều lành thì chẳng đem lại lợi ích.",
"52": "Như thứ hoa tươi đẹp vừa có màu sắc lại có hương thơm, những người nói điều lành và làm điều lành sẽ đem lại kết quả tốt.",
"53": "Như từ đống hoa có thể làm nên nhiều tràng hoa; như vậy, từ nơi thân người có thể tạo nên nhiều việc thiện.",
"54": "Hương của các loài hoa chiên đàn, đa già la hay mạt lỵ(45) đều không thể bay ngược gió, chỉ có mùi hương đức hạnh của người chân chính, tuy ngược gió vẫn bay khắp muôn phương.",
"55": "Hương chiên đàn, hương đa già la, hương bạt tất kỳ(46), hương sen xanh, trong tất cả thứ hương chỉ thứ hương đức hạnh hơn cả.",
"56": "Hương chiên đàn, hương đa già la đều là thứ hương vi diệu nhưng không bằng thứ hương đức hạnh xông ngát tận chư thiên.",
"57": "Người nào thành tựu các giới hạnh, hằng ngày chẳng buông lung, an trụ trong chính trí và giải thoát, thì ác ma không thể dòm ngó được.",
"58": "Như từ trong đống bùn nhơ vất bỏ trên đường lớn sinh ra hoa sen thanh khiết ngọt ngào, làm đẹp ý mọi người; cũng thế, chỉ từ nơi chốn phàm phu ngu muội mới sản sanh những vị đệ tử bậc Chánh giác, đem trí tuệ soi sáng thế gian.",
"59": 58,
"60": "Đêm rất dài với người mất ngủ, đường rất xa với kẻ lữ hành mỏi mệt. Cũng thế, dòng luân hồi(47) sẽ tiếp nối mãi với kẻ ngu si không minh đạt Chánh pháp.",
"61": "Không gặp kẻ hơn mình cũng không gặp kẻ ngang mình để kết bạn, thà quyết chí ở một mình còn hơn kết bạn với người ngu.",
"62": "“Đây là con ta, đây là tài sản của ta”, kẻ phàm phu thường lo nghĩ như thế, nhưng chẳng biết chính “ta” còn không có, huống là con ta hay là tài sản ta.",
"63": "Ngu mà tự biết mình ngu tức là trí, ngu mà xưng rằng trí chính đó mới thật là ngu.",
"64": "Người ngu suốt đời gần gũi ngưòi trí, vẫn chẳng hiểu gì Chánh pháp, ví như cái muỗng múc thuốc chẳng bao giờ biết được mùi vị thuốc.",
"65": "Người trí gần gũi với người trí trong khoảng khắc cũng hiểu được Chánh pháp, chẳng khác gì cái lưỡi mới tiếp xúc với thuốc đã biết được mùi vị của thuốc.",
"66": "Kẻ phàm phu không giác tri nên đi chung với cừu địch một đường. Cũng thế, những người tạo ác nghiệp nhất định phải cùng ác nghiệp chịu khổ báo.",
"67": "Người gây điều bất thiện, làm xong ăn năn, khóc lóc nhỏ lệ dầm dề, vì biết mình sẽ thọ lấy quả báo tương lai(48).",
"68": "Người tạo các nghiệp thiện, làm xong chẳng ăn năn, còn vui mừng hớn hở, vì biết mình sẽ thọ lấy quả báo tương lai.(49)",
"69": "Khi ác nghiệp chưa thành thục, người ngu tưởng như đường mật; nhưng khi ác nghiệp đã thành thục, họ nhất định phải chịu khổ đắng cay.",
"70": "Từ tháng này qua tháng khác, với món ăn bằng đầu ngọn cỏ cô sa (cỏ thơm) (50) người ngu có thể lấy ăn để sống, nhưng việc ấy không có giá trị bằng một phần mười sáu của người tư duy Chánh pháp(51).",
"71": "Người cất sữa bò không chỉ sáng chiều đã thành vị đề hồ(52) được. Cũng thế, kẻ phàm phu tạo nghiệp ác tuy chẳng cảm thụ ác quả liền, nhưng nghiệp lực vẫn âm thầm theo họ như lửa ngún giữa tro than.",
"72": "Kẻ phàm phu lòng muốn được tri thức mà hành động lại dẫn tới diệt vong, nên hạnh phúc bị tổn hại mà trí tuệ(53) cũng tiêu tan.",
"73": "Kẻ ngu thường muốn hư danh: chỗ ngồi cao trong Tăng chúng, viện chủ trong Tăng viện, mọi người xin đến cúng dường.",
"74": "Hãy để cho người Tăng kẻ tục nghĩ rằng: “Sự này do ta làm, mọi việc lớn nhỏ đều theo lệnh của ta”. Kẻ ngu cứ tưởng lầm như thế nên lòng tham lam ngạo mạn tăng hoài.",
"75": "Một đàng đưa tới thế gian, một đàng đưa tới Niết-bàn, hàng Tỷ-kheo đệ tử Phật hãy biết rõ như thế, chớ nên tham đắm thế lợi để chuyên chú vào đạo giải thoát.",
"76": "Nếu gặp được người hiền trí chỉ bày lầm lỗi và khiển trách mình những chổ bất toàn, hãy nên kết thân cùng họ, xem như bậc trí thức chỉ cho kho tàng bảo vật. Kết thân với người trí lành mà không dữ.",
"77": "Những người khéo khuyên răn dạy dỗ, can ngăn tội lỗi kẻ khác, đuợc người lành kính yêu bao nhiêu thì bị người dữ ghét bỏ bấy nhiêu.",
"78": "Chớ nên kết bạn với người ác, chớ nên kết bạn với người kém hèn, hãy nên kết bạn với người lành, với người chí khí cao thượng(55).",
"79": "Được uống nước Chánh pháp thì tâm thanh tịnh an lạc, nên người trí thường vui mừng nghe thánh nhơn(56) thuyết pháp.",
"80": "Người tưới nước lo dẫn nước, thợ làm cung tên lo uốn cung tên, thợ mộc lo nảy mực đo cây, còn người trí thì lo tự điều phục lấy mình(57).",
"81": "Như ngọn núi kiên cố, chẳng bao giờ bị gió lay, những lời phỉ báng hoặc tán dương chẳng bao giờ lay động được người đại trí.",
"82": "Như hồ nước sâu, yên lặng trong sạch, những người có trí sau khi nghe Pháp, tâm họ cũng thanh tịnh và yên lặng.",
"83": "Người lành thường xa lìa mà không bàn đến những điều tham dục. Kẻ trí không còn niệm mừng lo, nên chẳng bị lay động vì khổ, lạc.",
"84": "Không vì mình cũng không vì người để làm chuyện ác, không vì cầu con trai, giàu có hay mưu việc thiên hạ để làm việc ác, không vì cầu phồn vinh cho mình bằng những phương tiện bất chánh. Người này thật là người giới hạnh, trí tuệ và chánh pháp.",
"85": "Trong đám nhân quần, một ít người đạt đến bờ kia(58), còn bao nhiêu người khác thì đang quanh quẩn tại bờ này (59).",
"86": "Những người hay thuyết pháp, theo Chánh pháp tu hành, thì được đạt tới bờ kia, thoát khỏi cảnh giới tà ma khó thoát(60).",
"87": "Người trí hãy mau từ bỏ hắc pháp (ác pháp) tu tập bạch pháp (thiện pháp), xa gia đình nhỏ hẹïp, xuất gia sống độc thân theo phép tắc Sa-môn.",
"88": "Người trí cần gột sạch cấu uế trong tâm, cầu cái vui Chánh pháp, xa lìa ngũ dục, chẳng còn vướng mắc chi.",
"89": "Người nào chính tâm tu tập các pháp giác chi(61) xa lìa tánh cố chấp(62), rời bỏ tâm nhiễm ái, diệt hết mọi phiền não(63) để trở nên sáng suốt, thì sẽ chứng Niết-bàn ngay trong đời hiện tại.",
"90": "Người đã giải thoát hết thảy, đã dứt hết thảy buộc ràng(65), là người đi đường đã đến đích(66), chẳng còn chi lo sợ khổ đau.",
"91": "Kẻ dũng mãnh chánh niệm, tâm không ưa thích tại gia; ví như con ngỗng trời, khi ra khỏi ao, chúng bỏ lại cái ao hồ không chút nhớ tiếc(67).",
"92": "Những vị A-la-hán không chất chứa tài sản(68) biết rõ mục đích sự ăn uống(69), tự tại đi trong cảnh giới: “không, vô tướng, giải thoát”(70), như chim bay giữa hư không, khó tìm thấy dấu vết.",
"93": "Những vị A-la-hán đã dứt sạch các lậu hoặc(71), không tham đắm uống ăn, tự tại đi trong cảnh giới “không, vô tướng, giải thoát” như chim bay giữa hư không, khó tìm thấy dấu vết.",
"94": "Những vị A-la-hán đã tịch tịnh được các căn như tên kỵ mã đã điều luyện được ngựa lành, nên không còn phiền não ngã mạn, được hàng nhơn thiên kính mộ.",
"95": "Những vị A-la-hán đã bỏ hết sân hận, tâm như cõi đất bằng, chí thành kiên cố như nhân đà yết la(72), như ao sâu không bùn, nên chẳng còn bị luân hồi xoay chuyển.",
"96": "Những vị A-la-hán ý nghiệp thường vắng lặng, ngữ nghiệp, hành nghiệp thường vắng lặng, lại có chánh trí giải thoát, nên được an ổn luôn.",
"97": "Những vị A-la-hán chẳng còn phải tin ai(73), đã thấu hiểu đạo vô vi, dứt trừ vĩnh viễn nguyên nhân(74) cùng quả báo ràng buộc(75), lòng tham dục cũng xa lìa. Thật là bậc Vô thượng sĩ.",
"98": "Dù ở xóm làng, dù ở núi rừng, dù ở đất bằng, dù ở ngõ trũng(76), bất cứ ở chốn nào mà có vị A-la-hán thì ở đấy đầy cảnh tượng yên vui.",
"99": "Lâm dã là cảnh rất vui đối với vị A-la-hán, nhưng người đời chẳng ưa thích; trái lại, dục lạc là cảnh ưa thích đối với người đời, vị A-la-hán lại lánh xa.",
"100": "Tụng đến ngàn câu vô nghĩa chẳng bằng một câu có nghĩa lý, nghe xong tâm liền tịch tịnh.",
"101": "Tụng đến ngàn câu kệ vô nghĩa, chẳng bằng một câu kệ có nghĩa lý, nghe xong tâm liền tịch tịnh.",
"102": "Tụng đến trăm câu kệ vô nghĩa chẳng bằmg một Pháp cú (77), nghe xong tâm liền tịch tịnh.",
"103": "Thắng ngàn quân giặc ở chiến trường chẳng bằng tự thắng. Người tự thắng là chiến sĩ oanh liệt nhất.",
"104": "Tự thắng mình còn vẻ vang hơn thắng kẻ khác. Muốn thắng mình phải luôn luôn tiết chế lòng tham dục(78).",
"105": "Dù là Thiên thần, Càn thát bà(79), Ma vương(80), hay Phạm thiên(81), không một ai chẳng thất bại trước người đã tự thắng(82).",
"106": "Mỗi tháng bỏ ra hàng ngàn vàng để sắm vật hy sinh tế tự cả đến trăm năm, chẳng bằng giây lát cúng dường bậc chân tu; cúng dường bậc chân tu trong giây lát thắng hơn tế tự quỉ thần cả trăm năm.",
"107": "Cả trăm năm ở tại rừng sâu thờ lửa, chẳng bằng trong giây lát cúng dường bậc chân tu, cúng dường bậc chân tu trong giây lát thắng hơn thờ lửa cả trăm năm.",
"108": "Suốt năm cúng dường để cầu phước, công đức chẳng bằng một phần tư sự kính lễ bậc chánh trực, chánh giác(83).",
"109": "Thường hoan hỷ tôn trọng, kính lễ bậc trưởng lão(84) thì được tăng trưởng bốn điều: sống lâu, đẹp đẽ, vui vẻ, khỏe mạnh(85).",
"110": "Sống trăm tuổi mà phá giới, không tu thiền, chẳng bằng sống chỉ một ngày mà trì giới, tu thiền định.",
"111": "Sống trăm tuổi mà thiếu trí tuệ, không tu thiền, chẳng bằng sống chỉ một ngày mà đủ trí tuệ, tu thiền định.",
"112": "Sống trăm tuổi mà giải đải không tinh tấn, chẳng bằng sống chỉ một ngày mà hăng hái tinh cần.",
"113": "Sống trăm tuổi mà không thấy pháp vô thường sanh diệt(86), chẳng bằng sống chỉ một ngày mà được thấy pháp sinh diệt vô thường.",
"114": "Sống trăm tuổi mà không thấy đạo tịch tịnh vô vi, chẳng bằng sống chỉ một ngày mà thấy đạo vô vi tịch tịnh.",
"115": "Sống trăm tuổi mà không thấy pháp tối thượng, chẳng bằng sống chỉ một ngày mà thấy pháp tối thượng.",
"116": "Hãy gấp rút làm lành, chế chỉ tâm tội ác. Hễ biếng nhác làm lành giờ nào thì tâm liền ưa chuyện ác giờ ấy.",
"117": "Nếu đã lỡ làm ác, chớ tiếp tục làm thêm, chớ vui làm việc ác. Hễ chứa ác nhất định thọ khổ.",
"118": "Nếu đã làm việc lành, hãy nên tiếp làm mãi, nên vui làm việc lành. Hễ chứa lành nhất định thọ lạc.",
"119": "Khi nghiệp ác chưa thành thục, kẻ ác cho là vui; khi nghiệp ác đã thành thục kẻ ác mới hay là ác.",
"120": "Khi nghiệp lành chưa thành thục, người lành cho là khổ; khi nghiệp lành đã thành thục, người lành mới biết là lành.",
"121": "Chớ khinh điều ác nhỏ(87), cho rằng “chẳng đưa lại quả báo cho ta”. Phải biết giọt nước nhiểu lâu ngày cũng đầy bình. Kẻ ngu phu sở dĩ đầy tội ác bởi chứa dồn từng chút từng chút mà nên.",
"122": "Chớ khinh điều lành nhỏ cho rằng: “chẳng đưa lại quả báo cho ta”. Phải biết giọt nước nhiểu lâu ngày cũng làm đầy bình. Kẻ trí sở dĩ toàn thiện bởi chứa dồn từng chút từng chút mà nên.",
"123": "Như người đi buôn mang nhiều của báu mà thiếu bạn đồng hành, tránh xa con đường nguy hiểm làm sao, như kẻ tham sống tránh xa thuốc độc như thế nào, thì các ngươi cũng phải tránh xa điều ác thế ấy.",
"124": "Với bàn tay không thương tích, có thể nắm thuốc độc mà không bị nhiễm độc; với người không làm ác thì không bao giờ bị ác.",
"125": "Đem ác ý xâm phạm đến người không tà vạy, người thanh tịnh vô nhiễm, tội ác sẽ trở lại làm cho kẻ ác như ngược gió tung bụi.",
"126": "Con người sinh ra từ bào thai, nhưng kẻ ác thì đọa vào địa ngục, người chính trực thì sinh lên chư Thiên, còn cõi Niết-bàn chỉ dành riêng cho những ai đã diệt sạch nghiệp sanh tử.",
"127": "Chẳng phải bay lên không trung, chẳng phải lặn xuống đáy bể, chẳng phải chui vào hang sâu núi thẳm, dù tìm khắp thế gian này, chẳng có nơi nào trốn khỏi nghiệp ác đã gây.",
"128": "Chẳng phải bay lên không trung, chẳng phải lặn xuống đáy bể, chẳng phải chui vào hang sâu núi thẳm, dù tìm khắp thế gian này, chẳng có nơi nào trốn khỏi tử thần.",
"129": "Ai cũng sợ dao gậy, ai cũng sợ chết; hãy lấy lòng mình suy lòng người, chớ giết, chớ bảo giết.",
"130": "Ai cũng sợ dao gậy, ai cũng thích sống; hãy lấy lòng mình suy lòng người, chớ giết, chớ bảo giết.",
"131": "Người nào cầu an vui cho mình mà lại lấy dao gậy não hại kẻ khác, thì sẽ không được yên vui.",
"132": "Người nào cầu an vui cho mình mà không lấy dao gậy não hại kẻ khác, thì sẽ được yên vui.",
"133": "Chớ nên nói lời thô ác. Khi ngươi dùng lời thô ác nói với người khác thì người khác cũng dùng lời thô ác nói với ngươi. Thương thay những lời nói nóng giận, thô ác, chỉ làm cho các ngươi đau đớn khó chịu như dao gậy mà thôi.",
"134": "Nếu ngươi yên lặng như cái đồng la bể trước lời thô ác cãi vã thì ngươi đã tự tại đi trên đường Niết-bàn, người kia chẳng tranh cãi với ngươi được nữa.",
"135": "Như với chiếc gậy, người chăn trâu xua trâu ra đồng; sự già, sự chết cũng thế, thường xua chúng sanh đến tử vong.",
"136": "Kẻ ngu tạo ác nghiệp vẫn không tự biết có quả báo. Người ngu tự tạo ra nghiệp để chiụ khổ, chẳng khác nào tự lấy lửa để đốt mình.",
"137": "Nếu lấy dao gậy hại người toàn thiện, toàn nhân(89), lập tức kẻ kia phải thọ lấy đau khổ trong mười điều này: Thống khổ về tiền tài bị tiêu mất, thân thể bị bại hoại, bị trọng bệnh bức bách, bị tán tâm loạn ý, bị vua quan bách hại, bị vu trọng tội, bị quyến thuộc ly tán, bị tài sản tan nát, phòng ốc nhà cửa bị giặc thiêu đốt, và sau khi chết bị đọa vào địa ngục.",
"138": 137,
"139": 137,
"140": 137,
"141": "Chẳng phải đi chân không, chẳng phải bện tóc, chẳng phải xoa tro đất vào mình, chẳng phải tuyệt thực, chẳng phải nằm trên đất, chẳng để mình nhớp nhúa, cũng chẳng phải ngồi xổm(90) mà có thể trở nên thanh tịnh, nếu không dứt trừ nghi hoặc(91).",
"142": "Người nào nghiêm giữ thân tâm tịch tịnh, chế ngự, khắc phục ráo riết trên đường tu Phạm hạnh, không dùng dao gậy gia hại sinh linh, thì chính người ấy là Bà-la-môn, là Sa-môn, là Tỷ-kheo vậy.",
"143": "Biết lấy điều hổ thẹn để tự cấm ngăn mình, thế gian ít người làm được. Nhưng người đã làm được, họ khéo tránh điều khổ nhục như ngựa hay khéo tránh roi da.",
"144": "Các ngươi hãy nỗ lực sám hối như ngựa đã hay còn thêm roi. Hãy ghi nhớ lấy chánh tín, tịnh giới, tinh tiến, tam ma địa (Thiền định) trí phân biệt Chánh pháp, và minh hành túc(92) để tiêu diệt vô lượng thống khổ.",
"145": "Người tưới nước lo dẫn nước, thợ làm tên lo uốn tên, thợ mộc lo nẩy mực cưa cây, người làm lành thì lo tự chế ngự.",
"146": "Làm sao vui cười, có gì thích thú, khi ở trong cõi đời luôn luôn bị thiêu đốt (94). Ở trong chỗ tối tăm bưng bít(95) sao không tìm tới ánh quang minh(96)?",
"147": "Hãy ngắm cái thân trang sức này chỉ là đống xương(97) lở lói(97), chồng chất tật bịnh mà người ta tưởng là êm ái(99), cái thân ấy tuyệt đối không có gì trường tồn.",
"148": "Cái hình hài suy già này là cái rừng già tập trung bịnh tật, dễ hư nát. Đã có tụ tất có tán, có sinh tất có tử.",
"149": "Trái hồ lô (trái bầu) về mùa thu thì khô rụng, thân này cũng vậy, rốt cuộc chỉ còn một đống xương màu lông hạc, rõ thật chẳng có gì vui.",
"150": "Thân này là cái thành xây bằng xương cốt, tô quét bằng máu thịt, để cất chứa sự già và sự chết, ngã mạn và dối gian(100).",
"151": "Cái xe vua đi dù được trang hoàng lộng lẫy cũng phải hư hoại, thân này dù có trau tria cũng phải già yếu. Chỉ trừ pháp của bậc thiện nhân(101) là không bị suy già mà cứ di chuyển từ người lành này sang người lành khác.",
"152": "Người ngu ít nghe, kém học, suốt đời như trâu, gân thịt dẫu lớn mạnh mà trí tuệ không tăng thêm.",
"153": "Ta lang thang trong vòng luân hồi qua bao kiếp sống, tìm mãi mà không gặp kẻ làm nhà. Đau khổ thay kiếp sống cứ tái diễn mãi! Hỡi kẻ làm nhà! Nay ta gặp được ngươi rồi. Ngươi không thể làm nhà nữa. Cột và đòn tay của ngươi đều gãy cả, nóc và xà nhà của ngươi đã tan vụn rồi. Ta đã chứng đắc Niết-bàn, bao nhiêu dục ái đều dứt sạch(102).",
"154": 153,
"155": "Lúc thiếu niên cường tráng đã không kiếm ra tài của, cũng chẳng lo tu hành, thì khi già chẳng khác gì con cò già bên bờ ao, không kiếm ra mồi, phải ủ rũ chết mòn.",
"156": "Lúc thiếu niên cường tráng đã không kiếm ra tài của, cũng chẳng lo tu hành, nên khi già nằm xuống, dáng ngươi như cây cung gãy, cứ buồn than về dĩ vãng.",
"157": "Nếu biết tự thương mình, phải tự gắng bảo hộ, trong ba thời có một, người trí nên tỉnh ngộ, chớ mê man(103).",
"158": "Trước hãy tự đặt mình vào chánh đạo rồi sau giáo hóa kẻ khác, hiền giả như vậy mới tránh khỏi điều lỗi lầm xảy ra.",
"159": "Nếu muốn khuyên người khác nên làm như mình, trước hãy sửa mình rồi sau sửa người. Tự sửa mình vốn là điều khó nhất.",
"160": "Chính tự mình làm chổ nương cho mình (104) chứ người khác làm sao nương được? Tự mình khéo tu tập mới đạt đến chỗ nương dựa nhiệm mầu (105).",
"161": "Ác nghiệp chính do mình tạo, từ mình sinh ra. Ác nghiệp làm hại kẻ ngu dễ dàng như kim cang phá hoại bảo thạch.",
"162": "Sự phá giới làm hại mình như giây man la bao quanh cây Ta la làm cho nó khô héo(106). Người phá giới là làm điều mà kẻ thù muốn làm cho họ.",
"163": "Việc ác dễ làm nhưng chẳng lợi gì cho ta, trái lại, việc lành có lợi cho ta thì lại rất khó làm.",
"164": "Những người ác tuệ ngu si, vì tâm tà kiến mà vu miệt giáo pháp A-la-hán, vu miệt người hành chánh đạo và giáo pháp đức Như lai để tự mang lấy bại hoại, giống như cỏ Cách tha, hễ sinh quả xong liền tự diệt (107).",
"165": "Làm dữ bởi ta, mà nhiễm ô cũng bởi ta; làm lành bởi ta, mà thanh tịnh cũng bởi ta. Tịnh hay không tịnh đều bởi ta, chứ không ai có thể làm cho ai thanh tịnh được.",
"166": "Chớ vì lợi ích cho kẻ khác mà quên hẳn lợi ích cho chính mình(108). Người biết lo lợi ích mình mới thường chuyên tâm vào những điều ích lợi tất cả.",
"167": "Chớ theo điều ty liệt, chớ đem thân buông lung. Chớ nên theo tà thuyết, chớ làm tăng trưởng tục trần(109).",
"168": "Hăng hái đừng buông lung, làm theo Chánh pháp. Người thực hành Chánh pháp, đời này vui, đời sau vui(110).",
"169": "Khéo thực hành Chánh pháp, chớ làm điều ác hành. Người thực hành Chánh pháp, đời này vui, đời sau vui.",
"170": "Như bọt nước trôi sông, như lầu sò chợ bể(111). Nếu xem đời bằng cặp mắt ấy, thần chết không tìm tới được.",
"171": "Giả sử thế gian này có được lộng lẫy như chiếc xe của vua, thì trong số người xem thấy, chỉ người ngu mới tham đắm, chứ kẻ trí chẳng hề bận tâm.",
"172": "Người nào trước buông lung sau lại tinh tấn, người đó là ánh sáng chiếu cõi thế gian, như vầng trăng ra khỏi mây mù.",
"173": "Người nào lấy việc lành tiêu trừ việc ác, người đó là ánh sáng chiếu cõi thế gian như vầng trăng ra khỏi mây mù.",
"174": "Như chim thoát khỏi lưới, chẳng mấy con bay thẳng lên trời cao, trong thế gian này chẳng mấy người sáng suốt trông thấy cao xa.",
"175": "Con thiên nga chỉ bay được giữa không trung, người có thần thông chỉ bay được khỏi mặt đất, duy bậc đại trí, trừ dẹp ma quân mới bay được khỏi thế gian này.",
"176": "Những ai vi phạm đạo nhất thừa(112), những ai ưa nói lời vọng ngữ, những ai không tin có đời sau, thì chẳng có điều ác nào mà họ không làm được.",
"177": "Người xan tham không thể sanh lên cõi trời, người ngu si không ưa tán dương việc cúng dường, nhưng người trí thấy việc cúng dường lại tùy hỷ và tương lai họ sẽ được phần an lạc.",
"178": "Người thống suất cõi đất, người làm chủ chư Thiên, hết thảy vị thế chúa ấy chẳng sánh kịp một vị đã chứng quả Tu đà hoàn(113).",
"179": "(114) Chẳng ai hơn nổi người đã thắng phục dục tình. Người đã thắng phục dục tình không còn bị thất bại trở lại(115), huống Phật trí mênh mông không dấu tích, các ngươi lấy gì mà hòng cám dỗ được?",
"180": "Người dứt hết trói buộc, ái dục còn khó cám dỗ được họ, huống Phật trí mênh mông không dấu tích, các ngươi lấy gì mà hòng cám dỗ được?",
"181": "Người tu trì Thiền định, ưa xuất gia, ở chổ thanh vắng. Người có chánh niệm chánh giác, bao giờ cũng được sự ái kính của Thiên, nhơn.",
"182": "Được sinh làm người là khó, được sống trọn đời còn khó hơn, được nghe Chánh pháp là khó, được gặp Phật ra đời là khó.",
"183": "Chớ làm điều ác, gắng làm việc lành, giữ tâm ý trong sạch. Ấy, lời chư Phật dạy.",
"184": "Chư Phật thường dạy Niết-bàn là quả vị tối thượng. Nhẫn nhục là khổ hạnh tối cao. Xuất gia mà não hại người khác, không gọi là Sa-môn(117).",
"185": "Chớ nên phỉ báng, đừng làm não hại, giữ giới luật tinh nghiêm(118), uống ăn có chừng mực, riêng ở chổ tịch tịnh, siêng tu tập Thiền định(119). Ấy lời chư Phật dạy.",
"186": "Giả sử mưa xuống bạc vàng cũng chẳng làm thỏa mãn lòng tham dục. Người trí đã biết rõ ái dục vui ít mà khổ nhiều. Thế nên, dù sự dục lạc ở cõi trời, ngươi cũng chớ sanh tâm mà mong cầu. Đệ tử đấng Chánh giác chỉ mong cầu diệt trừ ái dục mà thôi.",
"187": 186,
"188": "Vì sợ hãi bất an mà đến quy y thần núi, quy y rừng cây, quy y miếu thờ thọ thần(120), nhưng đó chẳng phải là chỗ nương dựa yên ổn, là chỗ quy y tối thượng. Ai quy y như thế khổ não vẫn còn nguyên. Trái lại, quy y Phật, Pháp, Tăng, phát trí tuệ chơn chánh, hiểu thấu Bốn Lẽ mầu: Biết khổ, biết khổ nhân, biết khổ diệt, và biết Tám chi Thánh đạo(121) diệt trừ hết khổ não. Đó là chỗ quy y an ổn, là chỗ quy y tối thượng. Ai quy y được như vậy, giải thoát hết khổ đau.",
"189": 188,
"190": 188,
"191": 188,
"192": 188,
"193": "Rất khó gặp được bậc Thánh nhơn, vì chẳng phải thường có. Phàm ở đâu có người trí ra đời thì ở đó gia tộc được an lành.",
"194": "Hạnh phúc thay đức Phật ra đời, hạnh phúc thay diễn nói Chánh pháp; hạnh phúc thay Tăng già hòa hợp, hạnh phúc thay dõng tiến đồng tu.",
"195": "Cúng dường những vị đáng cúng dường là Phật hay đệ tử của Ngài - những vị thoát ly hư vọng, vượt khỏi mọi lo âu. Công đức của người cúng dường bậc Tịch tịnh vô úy như vậy không thể kể lường.",
"196": 195,
"197": "Sung sướng thay chúng ta(123) sống không thù oán giữa những người thù oán. Giữa những người thù oán, ta sống không thù oán.",
"198": "Sung sướng thay chúng ta sống không tật bệnh giữa những người tật bệnh (124). Giữa những người tật bệnh, ta sống không tật bệnh.",
"199": "Sung sướng thay chúng ta sống không tham dục giữa những người tham dục! Giữa những người tham dục, ta sống không tham dục.",
"200": "Sung sướng thay chúng ta sống không bị điều gì chướng ngại(125), ta thường sống với những điều hỷ lạc như những vị trời Quang âm(126).",
"201": "Thắng lợi bị thù oán, thất bại bị đau khổ; chẳng màng tới thắng bại, sẽ sống hòa hiếu an vui.",
"202": "Không lửa nào bằng lửa tham dục, không ác nào bằng ác sân hận. Không khổ nào bằng khổ ngũ uẩn và không vui nào bằng vui Niết-bàn.",
"203": "Đói là chứng bệnh lớn, vô thường(127) là nỗi khổ lớn; biết được đúng như thế, đạt đến Niết-bàn vui tối thượng.",
"204": "Không bệnh là điều rất lợi, biết đủ là kẻ rất giàu, thành tín là nơi chí thân, Niết-bàn là vui tối thượng.",
"205": "Ai từng nếm mùi độc cư, ai từng nếm mùi tịch tịnh, người ấy còn ưa nếm mùi pháp vị, để xa lìa mọi tội ác, sợ hãi.",
"206": "Gặp được bậc Thánh nhơn là rất quí, vì sẽ chung hưởng sự vui lành. Bởi không gặp kẻ ngu si, nên người kia thường hoan hỷ.",
"207": "Đi chung với người ngu, chẳng lúc nào không lo buồn; ở chung với kẻ ngu khác nào ở chung với quân địch. Ở chung với người trí vui như hội ngộ với người thân.",
"208": "Đúng thật như vậy(128): Người hiền trí, người đa văn, người trì giới chân thành và bậc Thánh giả, được đi theo những bậc thiện nhân, hiền tuệ ấy, khác nào mặt trăng đi theo quỷ đạo tinh tú.",
"209": "Chuyên tâm làm những việc không đáng làm, nhác tu những điều cần tu, bỏ việc lành mà chạy theo dục lạc, người như thế dù có hâm mộ kẻ khác đã cố gắng thành công, cũng chỉ là hâm mộ suông(129).",
"210": "Chớ kết giao với người đáng ưa, chớ kết giao với người không đáng ưa. Không gặp được người thương yêu là khổ, gặp người cừu oán cũng khổ.",
"211": "Thế nên chớ đắm yêu, vì đắm yêu bị biệt ly là khổ. Nếu không còn những niệm yêu ghét thì không điều gì ràng buộc được.",
"212": "Từ hỷ ái sinh lo, từ hỷ ái sinh sợ; xa lìa hết hỷ ái, chẳng còn lo sợ gì.",
"213": "Từ tham ái sinh lo, từ tham ái sinh sợ; xa lìa hết tham ái, chẳng còn lo sợ gì.",
"214": "Từ tham dục sinh lo, từ tham dục sinh sợ; xa lìa hết tham dục, chẳng còn lo sợ gì.",
"215": "Từ lạc dục sinh lo, từ lạc dục sinh sợ; xa lìa hết lạc dục, chẳng còn lo sợ gì.",
"216": "Từ ái dục sinh lo, từ ái dục sinh sợ; xa lìa hết ái dục, chẳng còn lo sợ gì (130).",
"217": "Đầy đủ giới hạnh và chánh kiến, an trú Chánh pháp(131), rõ lý chơn thường (132), viên mãn các công hạnh(133), ấy mới là người đáng ái mộ.",
"218": "Khát cầu pháp ly ngôn, sung mãn tâm cứu xét, không đắm mê dục lạc, ấy là bậc thượng lưu(134).",
"219": "Người khách ly hương lâu ngày, từ phương xa trở về an ổn, được bà con thân hữu đón mừng như thế nào, thì người tạo phước nghiệp cũng vậy, khi từ cõi đời này sang cõi đời khác, phước nghiệp của họ là kẻ thân hữu đón mừng họ.",
"220": 219,
"221": "Xa bỏ lòng giận dữ, trừ diệt tính kiêu căng, giải thoát mọi ràng buộc, không chấp trước danh sắc(135), người không có một vật chi ấy, sự khổ chẳng còn theo dõi được.",
"222": "Người nào ngăn được cơn giận dữ nổi lên như dừng được chiếc xe đang chạy mạnh, mới là kẻ chế ngự giỏi, ngoài ra chỉ là kẻ cầm cương hờ(136).",
"223": "Lấy không giận thắng giận, lấy lành thắng chẳng lành, lấy cúng dường thắng xan tham, lấy chân thật thắng hư ngụy.",
"224": "Nói chân thật, không giận hờn, san sẻ cho người xin(137); đó là ba việc lành đưa người đến cõi chư Thiên.",
"225": "Không làm hại người thanh tịnh, thường chế phục thân tâm, thì đạt đến nơi bất tử chẳng còn ưu bi.",
"226": "Những người thường giác tỉnh, ngày đêm chuyên tu học, chí hướng đến Niết-bàn, thì mọi phiền não dứt sạch.",
"227": "A đa la(138) nên biết: Đây không phải chỉ là chuyện đời nay mà đời xưa đã từng nói: làm thinh bị người chê, nói nhiều bị người chê, ít nói cũng bị người chê; làm người không bị chê thực là chuyện khó có ở thế gian này.",
"228": "Toàn bị người chê cả, hay toàn được người khen cả, là điều quá khứ chưa từng có, hiện tại tìm không ra, và vị lai cũng không dễ gì thấy được.",
"229": "Cứ mỗi buổi mai thức dậy, tự biết phản tỉnh, hành động không tỳ vết, trí tuệ hiền minh, giới hạnh thanh tịnh, đó là người đáng được kẻ trí tán dương.",
"230": "Phẩm chất đúng loại vàng Diêm phù (139); thì ai chê bai được? Đó là hạng Bà-la-môn được chư Thiên tán thưởng.",
"231": "Giữ thân đừng nóng giận, điều phục thân hành động, xa lìa thân làm ác, dùng thân tu hạnh lành.",
"232": "Giữ lời đừng nóng giận, điều phục lời chánh chân, xa lìa lời thô ác, dùng lời tu hạnh lành.",
"233": "Giữ ý đừng nóng giận, điều phục ý tinh thuần, xa lìa ý hung ác, dùng ý tu hạnh lành.",
"234": "Người trí điều phục thân, cũng điều phục ngôn ngữ, điều phục luôn tâm ý, cả ba nghiệp thảy điều phục.",
"235": "Ngươi đã giống như ngọn lá khô, Diêm ma sứ giả (tứ thần) ở sát bên mình. Ngươi đang đứng trước ngưỡng cửa chết, bước lữ hành của ngươi thiếu hẳn lương thực.",
"236": "Ngươi hãy tự lo tạo lấy cho mình một hòn đảo an toàn, gấp rút tinh cần làm kẻ khôn ngoan, gột sạch phiền não trần cấu, để bước lên thánh cảnh chư Thiên(140).",
"237": "Đời sống ngươi sắp lụn tàn, ngươi đang dịch bước đến gần Diêm vương, giữa đường không nơi ngơi nghỉ, bước lữ hành của ngươi thiếu hẳn lương thực.",
"238": "Ngươi hãy tạo lấy cho mình một hòn đảo an toàn, gấp rút tinh cần làm kẻ khôn ngoan, gột sạch phiền não trần cấu, chớ trở lui đường sanh lão nguy nan.",
"239": "Hết sát na này đến sát na khác, người trí lo gột trừ dần những cấu uế nơi mình, như người thợ vàng cần mẫn gột trừ cặn bã khỏi chất vàng ròng.",
"240": "Như sét do sắt sinh ra rồi trở lại ăn sắt, ác nghiệp do ngươi gây ra rồi trở lại dắt ngươi đi vào cõi ác.",
"241": "Không tụng tập là vết nhơ của sự học kinh điển, không siêng năng là vết nhơ của nghiệp nhà, biếng nhác là vết nhơ của thân thể và nơi ăn chốn ở, phóng túng là vết nhơ của phép tự vệ.",
"242": "Tà hạnh là vết nhơ của người đàn bà, xan lẫn là vết nhơ của sự cúng dường. Đối với cõi này hay cõi khác thì tội ác chính là vết nhơ.",
"243": "Trong các nhơ cấu đó, vô minh cấu là hơn cả. Các ngươi hãy trừ hết vô minh để thành Tỷ-kheo thanh tịnh.",
"244": "Sống không biết xấu hổ, lỗ mãng như quạ diều, sống chê bai kẻ khác, sống đại đởm khoa trương, sống ngạo mạn tà ác; sống như thế chẳng khó khăn gì.",
"245": "Sống biết hổ thẹn, sống thường cầu thanh tịnh, sống không đam mê dục lạc, sống khiêm tốn, trong sạch và dồi dào kiến thức; sống như thế mới thực khó làm.",
"246": "Trong thế gian này, ai hay sát sinh, hay nói dối, hay lấy cắp, hay phạm dâm, hay say đắm rượu chè; ai có các hành vi đó tức là đã tự đào bỏ thiện căn của mình ngay ở cõi đời này.",
"247": 246,
"248": "Các ngươi nên biết: “Hễ không lo chế ngự tức là ác”. Vậy chớ tham, chớ làm điều phi pháp, để khỏi sa vào thống khổ đời đời.",
"249": "Vì có tâm tin vui nên người ta mới cúng dường, trái lại kẻ có tâm ganh ghét người khác được ăn, thì ngày hoặc đêm kẻ kia không thể định tâm được.",
"250": "Nhưng kẻ nào đã đoạn được, nhổ được, diệt được tâm tưởng ấy thì ngày hoặc đêm, kẻ kia đều được định tâm.",
"251": "Không lửa nào dữ bằng lửa tham dục, không cố chấp nào bền bằng tâm sân giận, không lưới nào trói buộc bằng lưới ngu si, không dòng sông nào đắm chìm bằng sông ái dục.",
"252": "Thấy lỗi người thì dễ, thấy lỗi mình thì khó. Lỗi người ta cố phanh tìm như tìm thóc lẫn trong gạo; còn lỗi mình, ta cố che giấu như kẻ cờ gian bạc lận thu giấu quân bài.",
"253": "Nếu thấy lỗi người thì tâm ta dễ sinh nóng giận mà phiền não tăng thêm, nếu bỏ đi thì phiền não cũng xa lánh.",
"254": "Giữa hư không thì làm gì có dấu vết, trong ngoại đạo thì làm gì có Sa-môn(141). Chúng sanh thì thích điều hư vọng mà Như lai làm gì còn hư vọng(142).",
"255": "Giữa hư không thì làm gì có dấu vết, trong ngoại đạo thì làm gì có Sa-môn. Năm uẩn thì không thường trú mà Như lai thì chẳng loạn động bao giờ.",
"256": "Xử sự lỗ mãng(144) đâu phải hạnh của người phụng thờ Chánh pháp, vậy người trí cần biện biệt đâu chánh và đâu tà.",
"257": "Không khi nào lỗ mãng, đúng phép và công bình mới là người dẫn đạo. Kẻ trí nhờ sống đúng pháp nên gọi là người an trụ pháp.",
"258": "Chẳng phải cậy nhiều lời cho là người có trí, nhưng an tịnh không cừu oán, không sợ hãi, mới là người có trí.",
"259": "Chẳng phải cậy nhiều lời cho là hộ trì pháp, nhưng tuy ít học mà do thân thực (145) thấy pháp, không buông lung, mới là người hộ trì pháp.",
"260": "Trưởng lão(146) chẳng phải vì bạc đầu. Nếu chỉ vì tuổi tác cao mà xưng trưởng lão, thì đó là chỉ xưng suông.",
"261": "Đủ kiến giải chân thật(147), giữ trọn các pháp hành(148), không sát hại sinh linh, lo tiết chế (149) điều phục(150), người có trí tuệ đó trừ hết các cấu nhơ, mới xứng danh trưởng lão.",
"262": "Những người hư ngụy, tật đố và xan tham, tuy có biện tài lưu loát, tướng mạo đoan trang, cũng chẳng phải người lương thiện.",
"263": "Những người trí nhờ diệt trừ tận gốc lòng sân hận, mới là người lương thiện.",
"264": "Người vọng ngữ và phá giới, dù cạo tóc cũng chưa phải là Sa-môn; huống còn chất đầy tham dục, làm sao thành Sa-môn?",
"265": "Người nào dứt hết các điều ác, không luận lớn hay nhỏ, nhờ dứt hết các ác mà được gọi Sa-môn.",
"266": "Chỉ mang bát khất thực, đâu phải là Tỷ-kheo? Chỉ làm nghi thức tôn giáo cũng chẳng phải Tỷ-kheo vậy.",
"267": "Bỏ thiện(151) và bỏ ác, chuyên tu hành thanh tịnh, lấy “Biết”(152) mà ở đời, mới thật là Tỷ-kheo.",
"268": "Kẻ ngu muội vô trí, dù làm thinh cũng không thể gọi được là người tịch tịnh. Kẻ trí tuệ sáng suốt như bàn cân, biết cân nhắc điều thiện lẽ ác mà chọn lành bỏ dữ, mới gọi là người tịch tịnh. Biết được cả nội giới và ngoại giới, nên gọi là người tịch tịnh.",
"269": 268,
"270": "Còn sát hại chúng sanh, đâu được xưng là Thánh hiền, không sát hại chúng sanh mới gọi là Thánh hiền(153).",
"271": "Chẳng do giới luật, đầu đà(154), chẳng phải do nghe nhiều, học rộng(155), chẳng phải do chứng được tam muội, chẳng phải do ở riêng một mình, đã vội cho là ”hưởng được cái vui xuất gia, phàm phu không bì kịp”. Các ngươi chớ vội tin điều ấy, khi mê lầm phiền não của các ngươi chưa trừ.",
"272": 271,
"273": "Bát chánh đạo là đạo thù thắng hơn các đạo, Tứ đế (156) là lý thù thắng hơn các lý, ly dục(157) là pháp thù thắng hơn các pháp, cụ nhãn(158) là bậc thù thắng hơn các bậc thánh hiền.",
"274": "Chỉ có con đường này(159), chẳng còn con đường nào khác có thể làm cho tri kiến các ngươi thanh tịnh. Các ngươi thuận làm theo thì bọn ma bị rối loạn.",
"275": "Các ngươi thuận tu theo Chánh đạo trên đây, thì khổ não sẽ dứt hết, và biết rằng đạo ta nói có sức trừ diệt chông gai(160).",
"276": "(161) Các ngươi hãy nỗ lực lên! Như Lai chỉ dạy cho con đường giác ngộ(162). Sự trói buộc của ma vương sẽ tùy sức Thiền định của các ngươi mà được giải thoát.",
"277": "“Các hành(163) đều vô thường”; khi đem trí tuệ soi xét được như thế, thì sẽ nhàm lìa thống khổ. Đó là đạo thanh tịnh.",
"278": "“Các hành đều là khổ”; khi đem trí tuệ soi xét được như thế, thì sẽ nhàm lìa thống khổ. Đó là đạo thanh tịnh.",
"279": "“Các pháp đều vô ngã”; khi đem trí tuệ soi xét được như thế, thì sẽ nhàm lìa thống khổ. Đó là đạo thanh tịnh.",
"280": "Khi đáng nỗ lực không nỗ lực, thiếu niên cường tráng đã biếng lười, ý chí tiêu trầm và nhu nhược; kẻ biếng nhác ấy làm gì có trí để ngộ đạo!",
"281": "Thận trọng lời nói, kềm chế ý nghĩ, thân không làm ác, ba nghiệp thanh tịnh, là được đạo Thánh nhơn.",
"282": "Tu Du già(164) thì trí phát, bỏ Du già thì tuệ tiêu. Biết rõ hai lẽ này thế nào là đắc thất, rồi nỗ lực thực hành, sẽ tăng trưởng trí tuệ.",
"283": "Hãy đốn rừng dục vọng, chớ đốn cây thọ lâm; từ rừng dục vọng sinh sợ, hãy thoát ngoài rừng dục.",
"284": "Sợi dây tình giữa trai gái chưa dứt, thì tâm còn bị buộc ràng như bò con chẳng rời vú mẹ.",
"285": "Tự mình dứt hết ái dục như lấy tay bẻ cành sen thu, siêng tu đạo tịch tịnh. Đó là Niết-bàn mà đức Thiện thệ(165) đã truyền dạy.",
"286": "“Mùa mưa ta ở đây, đông, hạ, ta cũng ở đây”, đấy là tâm tưởng của hạng người ngu si, không tự giác những gì nguy hiểm(166).",
"287": "Người đắm yêu con cái và súc vật, thì tâm thường mê hoặc, bị tử thần bắt đi, như xóm làng đang say ngủ mà bị cơn nước lũ cuốn trôi.",
"288": "Một khi tử thần đã đến, chẳng thân thuộc nào có thể thay thế, dù cha con thân thích cũng chẳng làm sao cứu hộ.",
"289": "Biết rõ lý lẽ trên(167) người trí gắng trì giới, thấu hiểu đường Niết-bàn, mau làm cho thanh tịnh.",
"290": "Nếu bỏ vui nhỏ mà được hưởng vui lớn, kẻ trí sẽ làm như thế.",
"291": "Gieo khổ cho người để cầu vui cho mình, thì sẽ bị lòng sân hận buộc ràng, không sao thoát khỏi nỗi oán ghét.",
"292": "Việc đáng làm không làm, việc không đáng làm lại làm, những người phóng túng ngạo mạn, thì lậu tập mãi tăng thêm.",
"293": "Thường quan sát tự thân, không làm việc không đáng, việc đáng gắng chuyên làm, thì lậu tập dần tiêu tan.",
"294": "(168)Hãy diệt mẹ (ái dục) và cha (kiêu căng), diệt hai vua dòng Sát đế lợi(169), diệt Vương quốc(170) luôn cả quần thần (171) mà hướng về Bà-la-môn vô ưu(172).",
"295": "Hãy diệt mẹ (ái dục) và cha (kiêu căng), diệt hai vua dòng Bà-la-môn, diệt luôn hổ tướng “nghi” thứ năm (173), mà hướng về Bà-la-môn vô ưu.",
"296": "Đệ tử Kiều đáp ma(174), phải luôn tự tỉnh giác, vô luận ngày hay đêm, thường niệm tưởng Phật đà.",
"297": "Đệ tử Kiều đáp ma, phải luôn tự tỉnh giác, vô luận ngày hay đêm, thường niệm tưởng Đạt ma.",
"298": "Đệ tử Kiều đáp ma, phải luôn tự tỉnh giác, vô luận ngày hay đêm, thường niệm tưởng Tăng già.",
"299": "Đệ tử Kiều đáp ma, phải luôn tự tỉnh giác, vô luận ngày hay đêm, thường niệm tưởng sắc thân(175).",
"300": "Đệ tử Kiều đáp ma, phải luôn tự tỉnh giác, vô luận ngày hay đêm, thường vui điều bất sát.",
"301": "Đệ tử Kiều đáp ma, phải luôn tự tỉnh giác, vô luận ngày hay đêm, thường ưa tu Thiền quán.",
"302": "Xuất gia dứt hết ái dục là khó, tại gia theo đường sinh hoạt là khó, không phải bạn mà chung ở là khổ, qua lại trong vòng luân hồi là khổ. Vậy các ngươi đừng qua lại trong vòng sanh tử luân hồi ấy.",
"303": "Chánh tín mà giới hạnh, được danh dự và thánh tài(176); người nào được như thế, đến đâu cũng tôn vinh.",
"304": "Làm lành thì danh được vang xa, tỏ rạng như Tuyết sơn(177); làm ác thì mù mịt như bắn cung ban đêm.",
"305": "Ngồi một mình, nằm một mình, đi một mình không mệt mỏi, một mình tự điều luyện, vui trong chốn rừng sâu.",
"306": "Thường nói lời vọng ngữ, có làm nói không làm, người tạo hai nghiệp ấy, chết cùng đọa địa ngục.",
"307": "Dù mặc nhiều cà sa, không ngăn trừ ác hạnh, người ác vì nghiệp ác, chết đọa vào địa ngục.",
"308": "Phá giới chẳng tu hành, thà nuốt hòn sắt nóng, hừng hực lửa đốt thân, còn hơn thọ lãnh của tín chủ.",
"309": "Buông lung theo vợ người, phải mắc vào bốn nạn: mắc tội, ngủ không yên, bị chê, đọa địa ngục.",
"310": "Vô phước, đọa ác thú, thường sợ hãi, ít vui, quốc vương kết trọng tội: Vậy chớ theo vợ người.",
"311": "Vụng nắm cỏ cô sa (kusa) tức bị họa đứt tay, Sa-môn theo tà hạnh, tức bị đọa địa ngục.",
"312": "Những người giải đãi, giới hạnh nhiễm ô, hoài nghi việc tu Phạm hạnh, không thể chứng quả lớn.",
"313": "Việc đáng làm nên làm, phải làm cho hết sức, xuất gia mà phóng túng rong chơi, chỉ tăng thêm dục trần.",
"314": "Không làm nghiệp ác là hơn, làm ác nhất định thọ khổ, làm các nghiệp lành là hơn, làm lành nhất định thọ vui.",
"315": "Như thành ở biên khu, đuợc phòng hộ trong ngoài, tự phòng hộ mình cũng vậy, giây lát chớ buông lung, hễ giây lát buông lung là giây lát đọa vào địa ngục.",
"316": "Không đáng hổ lại hổ, việc đáng hổ lại không; cứ ôm tà kiến ấy, địa ngục khó lánh xa.",
"317": "Không đáng sợ lại sợ, việc đáng sợ lại không; cứ ôm tà kiến ấy, địa ngục khó lánh xa.",
"318": "Không lỗi tưởng là lỗi, có lỗi lại tưởng không; cứ ôm tà kiến ấy, địa ngục khó lánh xa.",
"319": "Có lỗi biết có lỗi, không lỗi biết không lỗi; giữ tâm chánh kiến ấy, đường lành thấy chẳng xa.",
"320": "Như voi xuất trận hứng chịu cung tên, ta nhẫn chịu mọi điều phỉ báng, bởi đời lắm người phá giới (thường ghét kẻ tu hành ).",
"321": "Luyện được voi để đem dự hội, luyện được voi để cho vua cỡi là giỏi, nhưng nếu luyện được lòng ẩn nhẫn trước sự chê bai, mới là người có tài điêu luyện hơn cả mọi người.",
"322": "Con la(178) thuần tánh là con vật lành tốt, con tuấn mã Tín độ(179) là con vật lành, con voi lớn Kiều la(180) cũng là con vật lành, nhưng kẻ đã tự điều luyện được mình lại càng lành hơn (181).",
"323": "Chẳng phải nhờ xe hay ngựa mà đến được cảnh giới Niết-bàn, chỉ có người khéo điều luyện mình mới đến được Niết-bàn.",
"324": "Con voi Tài hộ Dhamapalako(182) (hộ vệ tài sản) đến kỳ phát dục thì lung lăng khó trị, buộc trói thì bỏ ăn mà chỉ nhớ nghĩ rừng voi (183) ).",
"325": "Như heo kia ưa ngủ lại tham ăn, kẻ phàm ngu vì tham ăn ưa ngủ, nên phải bị tiếp tục vào bào thai.",
"326": "Trong những thời quá khứ, tâm ta(184) thường chạy theo dục lạc, tham ái, ưa nhàn du, nhưng nay ta đã điều phục tâm như người quản tượng lấy móc câu chế ngự con voi luông tuồng.",
"327": "Hãy vui vẻ siêng năng, phòng hộ, tự cứu khỏi nguy nan, như voi cố gắng vượt khỏi chốn sa lầy.",
"328": "Nếu gặp bạn đồng hành hiền lương, giàu trí lự, hàng phục được gian nguy; hãy vui mừng mà đi cùng họ.",
"329": "Nếu không gặp bạn đồng hành hiền lương, giàu trí lự, hãy sống một mình, như vua tránh nước loạn, như voi sống ở rừng.",
"330": "Thà ở một mình hơn cùng người ngu kết bạn. Ở một mình khỏi điều ác dục, như voi một mình thênh thang giữa rừng sâu.",
"331": "Gặp bạn xa lâu ngày là vui, sung túc phải lúc là vui, mệnh chung có được thiện nghiệp là vui, lìa hết thống khổ là vui.",
"332": "Ở đời được kính dưỡng mẹ hiền là vui, kính dưỡng thân phụ là vui, kính dưỡng Sa-môn là vui, kính dưỡng Thánh nhơn là vui.",
"333": "Già vẫn giữ giới là vui, thành tựu chánh tín là vui, đầy đủ trí tuệ là vui, không làm điều ác là vui.",
"334": "Nếu say đắm buông lung thì tham ái tăng lên hoài như giống cỏ mạn la mọc tràn lan, từ đời này tiếp đời nọ như vượn chuyền cây tìm trái.",
"335": "Ở thế gian này nếu bị ái dục buộc ràng thì những điều sầu khổ càng tăng, như loài cỏ tỳ la gặp mưa.",
"336": "Ở thế gian này nếu hàng phục được ái dục khó hàng phục, thì sầu khổ tự nhiên rụng như nuớc giọt lá sen.",
"337": "Đây là sự lành mà ta bảo với các ngươi: Các ngươi hãy dồn sức vào để nhổ sạch gốc ái dục, như người muốn trừ cỏ tỳ la thì phải nhổ gốc nó. Các ngươi chớ lại để bị ma làm hại như loài cỏ lau gặp cơn nước lũ.",
"338": "Đốn cây mà chưa đào hết gốc rễ sâu bền thì cây vẫn sinh ra, đoạn trừ ái dục mà chưa sạch căn gốc thì khổ não vẫn sanh trở lại mãi.",
"339": "Những người có đủ ba mươi sáu dòng ái dục(185), họ mạnh mẽ dong ruỗi theo dục cảnh. Thế nên người có tâm tà kiến hằng bị những tư tưởng ái dục làm trôi giạt hoài.",
"340": "Dòng ái dục tuôn chảy khắp nơi(186) như giống cỏ mạn la mọc tràn lan mặt đất. Ngươi hãy xem giống cỏ đó để dùng tuệ kiếm đoạn tận gốc đi.",
"341": "Đời thường vui thích theo ái dục, ưa dong ruỗi lục trần, tuy họ có hướng cầu an lạc, vẫn bị quanh quẩn trong sanh tử vẫy vùng.",
"342": "Những người trì trục theo ái dục, vùng vẫy khác nào thỏ bị sa lưới. Càng buộc ràng với phiền não càng chịu khổ lâu dài.",
"343": "Những người trì trục theo ái dục, vùng vẫy khác nào thỏ bị sa lưới. Hàng Tỷ-kheo vì cầu vô dục(187) nên phải tự gắng lìa dục.",
"344": "Người đã lìa dục xuất gia, vui ở chốn sơn lâm(188) rồi trở lại nhà theo dục(189), ngươi hãy xem hạng người đó là đã được mở ra rồi lại tự trói vào!",
"345": "Đối với người trí, sự trói buộc bằng dây gai, bằng cây, bằng sắt, chưa phải bền chắc, chỉ có lòng luyến ái vợ con, tài sản, mới thật là sự trói buộc chắc bền.",
"346": "Đối với người trí, những gì dắt người vào sa đọa mới là sự trói buộc chắc bền. Nó hình như khoan dung hòa hoãn mà thật khó lòng thoát ra. Hãy đoạn trừ đừng dính mắc, lìa dục mà xuất gia.",
"347": "Những người say đắm ái dục, trôi theo ái dục là tự lao mình vào lưới trói buộc, như nhện mắc lưới. Ai dứt được sự buộc ràng, không còn dính mắc, thì sẽ lìa mọi thống khổ mà ngao du tự tại (190).",
"348": "Bỏ quá khứ, hiện tại, vị lai(191) mà vượt qua bờ kia; tâm giải thoát hết thảy, không còn bị sanh già.",
"349": "Những kẻ bị tư tưởng xấu ác làm tao loạn, cầu mong dục lạc thật nhiều. Người mong dục lạc tăng nhiều là tự trói mình thêm bền chắc.",
"350": "Muốn lìa xa ác tưởng, thường nghỉ tới bất tịnh, hãy trừ hết ái dục, đừng để ác ma buộc ràng.",
"351": "Bước tới chổ cứu kính(192) thì không còn sợ hãi, xa lìa ái dục thì không còn nhiễm ô, nhổ lấy mũi tên sanh hữu thì chỉ còn một thân này là cuối cùng(193).",
"352": "Xa lìa ái dục không nhiễm trước, thông đạt từ vô ngại, thấu suốát nghĩa và pháp vô ngại, và thứ lớp của tự cú(194), đó là bậc đại trí, đại trượng phu, chỉ còn một thân này là cuối cùng.",
"353": "Ta đã hàng phục được tất cả, ta đã rõ biết tất cả, ta không nhiễm một pháp nào, ta xa lìa hết thảy, diệt dục mà giải thoát và tự mình chứng ngộ, thì còn ai là thầy? (195).",
"354": "Trong các cách cúng dường, pháp thí là hơn cả; trong các chất vị, pháp vị là hơn cả; trong các hỷ lạc, pháp hỷ là hơn cả; người nào trừ hết mọi ái dục là vượt trên mọi khổ đau.",
"355": "Tài sản giàu có chỉ làm hại người ngu chứ không phải để cầu sang bờ kia. Người ngu bị tài dục hại mình, như mình đã vì tài dục mà hại người khác.",
"356": "Cỏ làm hại ruộng vườn, tham dục làm hại thế nhân.Vậy nên cúng dường cho người lìa tham, sẽ được quả báo lớn.",
"357": "Cỏ làm hại ruộng vườn, sân nhuế làm hại thế nhân.Vậy nên cúng dường cho người lìa sân, sẽ được quả báo lớn.",
"358": "Cỏ làm hại ruộng vườn, ngu si sẽ làm hại thế nhân. Vậy nên cúng dường cho ngưới lìa si, sẽ được quả báo lớn.",
"359": "Cỏ làm hại ruộng vườn, ái dục làm hại thế nhân. Vậy nên cúng dường cho người lìa dục, sẽ được quả báo lớn.",
"383": "Dũng cảm đoạn trừ dòng ái dục, các ngươi bỏ dục mới là Bà-la-môn. Nếu thấy rõ các uẩn(206) diệt tận, các ngươi liền thấy được Vô tác (Niết-bàn).",
"384": "Nếu thường trú trong hai pháp(207), hàng Bà-la-môn đạt đến bờ kia; dù có bao nhiêu ràng buộc cũng đều bị dứt sạch do trí tuệ của người kia.",
"385": "Không bờ kia cũng không bờ này(208), cả hai bờ đều không, xa lìa khổ não (209), không bị trói buộc; đó gọi là Bà-la-môn.",
"386": "Ai nhập vào Thiền định, an trú ly trần cấu, việc cần làm đã làm xong, phiền não lậu dứt sạch, chứng cảnh giới tối cao; đó là Bà-la-môn.",
"387": "Mặt trời chiếu sáng ban ngày, mặt trăng chiếu sáng ban đêm, khí giới chiếu sáng dòng vua chúa, Thiền định chiếu sáng kẻ tu hành, nhưng hào quang đức Phật chiếu sáng cả ngày đêm.",
"388": "Người dứt bỏ ác nghiệp gọi là Bà-la-môn; người hành vi thanh tịnh gọi là Sa-môn; người tự trừ bỏ cấu uế, gọi là người xuất gia.",
"389": "Chớ đánh đập Bà-la-môn! Bà-la-môn chớ sân hận! Người đánh đập mang điều đáng hổ, người sân hận lại càng đáng hổ hơn.",
"390": "Bà-la-môn, đây không phải là điều ích nhỏ. Nếu biết vui mừng chế phục tâm mình, tùy lúc đoạn trừ tâm độc hại thì thống khổ được ngăn chận liền.",
"391": "Không dùng thân, ngữ, ý tạo tác nghiệp ác, chế ngự được ba chổ đó, đó gọi là Bà-la-môn.",
"392": "Bất luận nơi đâu được nghe đấng Chánh Đẳng Chánh Giác thuyết pháp, hãy đem hết lòng cung kính như Bà-la-môn(210) kính thờ lửa.",
"393": "Chẳng phải vì bện tóc, chẳng phải vì chủng tộc, cũng chẳng phải tại nơi sanh mà gọi là Bà-la-môn; nhưng ai hiểu biết chân thật(211), thông đạt Chánh pháp, đó là kẻ Bà-la-môn hạnh phúc(212).",
"394": "Người ngu bện tóc và mặc áo da(213) đâu có ích chi? Trong lòng còn chứa đầy tham dục, thì dung nghi bên ngoài chỉ là trang điểm suông.",
"395": "Ai mặc áo phấn tảo(214), gầy ốm lộ gân xương, ở rừng sâu tu định; đó gọi là Bà-la-môn.",
"396": "Gọi là Bà-la-môn, không phải từ bụng mẹ đẻ ra. Nếu cứ chấp chặt các phiền não thì chỉ được gọi là ”Bồ” suông (215). Người nào lìa hết chấp trước, đó gọi là Bà-la-môn.",
"397": "Ai đoạn hết kiết sử, người đó thật không còn sợ hãi. Không bị đắm trước, xa lìa ràng buộc; đó gọi là Bà-la-môn.",
"398": "Như ngựa bỏ đai da, bỏ cương, bỏ dây và đồ sở thuộc, người giác trí bỏ tất cả chướng ngại, đó gọi là Bà-la-môn(216).",
"399": "Nhẫn nhục khi bị đánh mắng không sinh lòng sân hận, người có đội quân nhẫn nhục hùng cường, đó gọi là Bà-la-môn.",
"400": "Người đầy đủ đức hạnh không nóng giận, trì giới không dục nhiễm, chế ngự và đạt được thân cuối cùng, người như thế, Ta gọi là Bà-la-môn.",
"401": "Như nước giọt lá sen, như hột cải đặt đầu mũi kim, người không đắm nhiễm ái dục cũng như thế, Ta gọi họ là Bà-la-môn.",
"402": "Nếu ngay tại thế gian này, ai tự giác ngộ và diệt trừ đau khổ, trút bỏ gánh nặng mà giải thoát, Ta gọi họ là Bà-la-môn.",
"403": "Người có trí tuệ sâu xa, biết rõ thế nào là đạo, phi đạo và chứng đến cảnh giới vô thượng, đó gọi là Bà-la-môn.",
"404": "Chẳng lẫn lộn với tục luân, chẳng tạp xen với Tăng lữ, xuất gia lìa ái dục, đó gọi là Bà-la-môn.",
"405": "Bỏ hết đao trượng, không tự mình giết, không bảo người khác giết đối với tất cả hữu tình mạnh yếu; người như thế Ta gọi là Bà-la-môn.",
"406": "Ở giữa đám người cừu địch mà gây tình hữu nghị, ở giữa đám người hung hăng cầm gậy mà giữ khí ôn hòa, ở giữa đám người chấp đắm mà không chấp đắm, người như thế Ta gọi là Bà-la-môn.",
"407": "Từ lòng tham dục, sân nhuế, kiêu mạn, cho đến lòng hư ngụy, đều thoát bỏ như hột cải không dính đầu mũi kim, người như thế Ta gọi là Bà-la-môn.",
"408": "Chỉ nói lời chân thật hữu ích, không nói lời thô ác, không xúc phạm đến người, đó gọi là Bà-la-môn.",
"409": "Đối với vật gì xấu hay tốt, dài hay ngắn, thô hay tế, mà người ta không cho thì không lấy, đó gọi là Bà-la-môn.",
"410": "Đối với đời này cũng như đời khác, không móng lòng dục vọng, vô dục nên giải thoát, đó gọi là Bà-la-môn.",
"411": "Người không còn tham dục, liễu ngộ không nghi hoặc, chứng đến bậc vô sanh, đó gọi là Bà-la-môn.",
"412": "Nếu ở thế gian này không chấp trước thiện và ác, thanh tịnh không ưu lo, đó gọi là Bà-la-môn.",
"413": "Cái ái dục làm tái sanh đã được đoạn tận, như trăng trong không bợn, đứng lặng mà sáng ngời, đó gọi là Bà-la-môn.",
"414": "Vượt khỏi đường gồ ghề, lầy lội(217), ra khỏi biển luân hồi ngu si mà lên đến bờ kia, an trú trong Thiền định, không nghi hoặc, không chấp đắm, chứng Niết-bàn tịch tịnh, người như thế Ta gọi là Bà-la-môn.",
"415": "Xả bỏ dục lạc ngay tại đời này mà xuất gia làm Sa-môn không nhà, không cho dục lạc phát sinh lại, người như thế Ta gọi là Bà-la-môn.",
"416": "Xả bỏ ái dục ngay tại đời này mà xuất gia làm Sa-môn không nhà, không cho ái dục phát sinh lại, người như thế Ta gọi là Bà-la-môn.",
"417": "Lìa khỏi trói buộc của nhân gian, vượt khỏi trói buộc ở thiên thượng, hết thảy trói buộc đều lìa sạch, đó gọi là Bà-la-môn.",
"418": "Xả bỏ đều ưa ghét, thanh lương không phiền não, dũng mãnh hơn thế gian (218), đó gọi là Bà-la-môn.",
"419": "Nếu biết tất cả loài hữu tình tử thế nào, sinh thế nào, không chấp trước, khéo vượt qua, đó gọi là Bà-la-môn.",
"420": "Dù Chư thiên, Càn thát bà hay nhân loại, không ai biết được nơi chốn của vị A-la-hán đã dứt sạch phiền não; vị ấy Ta gọi là Bà-la-môn.",
"421": "Quá khứ vị lai hay hiện tại, người kia chẳng có một vật chi, người không chấp thủ một vật chi ấy gọi là Bà-la-môn.",
"422": "Hạng người dũng mãnh, tôn quí như trâu chúa(219), hạng người thắng lợi(220), vô dục như đại tiên, hạng người tẩy sạch(221), không nhiễm và giác tỉnh, hạng người như thế Ta gọi là Bà-la-môn.",
"423": "Vị Mâu ni (thanh tịnh) hay biết đời trước, thấy cả cõi Thiên và cõi khổ (ác thú), đã trừ diệt tái sinh, thiện nghiệp hoàn toàn, thành bậc Vô thượng trí; bậc viên mãn thành tựu mọi điều như thế Ta gọi là Bà-la-môn."
    },
    "notes": {
"1": "Những pháp yếu được diễn nói theo cách song đối.",
"2": "Pháp tức là Dhamma. Ở đây chỉ về pháp bất thiện, ở câu thứ hai chỉ về pháp thiện.",
"3": "Nguyên văn: Cakkam va vahato padam, nên dịch là: “Như bánh xe lăn theo chân con thú kéo xe”.",
"4": "Nguyên văn: Sanantano, có nghĩa là đời xưa. Cổ pháp (Sanantano Dhamma, hoặc Paranako Dham-ma) tức chỉ cho tất cả pháp tắc vĩnh cửu bất dịch mà chư Phật và đệ tử quá khứ đã gìn giữ và truyền dạy.",
"5": "Chỉ người tranh luận. Nhân khi Phật ở Kỳ đà lâm, đối với các vị Tỷ-kheo ưa tranh luận tại Câu sanh bì (Kosambi)ù mà nói kinh này, nên có sự xưng hô đó.",
"6": "Nguyên văn: Mayametthayamamasa, ý nói thẳng thì “chúng ta sắp bị diệt vong vì luật vô thường”.",
"7": "Tự cho thân mình trong sạch rồi đắm ưa hoài.",
"8": "Ma vương (Ma ra) ở đây chỉ tình dục.",
"9": "Chẳng khoái lạc (asubha) chỉ phép bất tịnh quán, như quán thân với 32 điều bất tịnh v.v...",
"10": "Chỉ tham dục v.v...",
"11": "Như bốn thứ tư cụ là áo, cơm, thuốc uống, nhà ở và mười thứ tà kiến v.v...",
"12": "Như giới, định, huệ và chánh kiến v.v...",
"13": "Do tạo ác nghiệp mà đưa đến sự bi ai trong đời này gọi là “Buồn tôi đã tạo ác”. Nhưng mà nỗi bi ai này còn có hạn chứ tương lai đọa vào ác đạo thọ báo lâu dài, cái khổ này mới vô cùng.",
"14": "Kẻ chăn bò thuê cứ sáng sớm dắt bò ra đồng, tối lại lùa bò về chuồng giao cho chủ, ngày ngày chỉ đếm bò mà đổi lấy ít tiền công, còn sữa, lạc, sanh tô, đề hồ của bò thì anh ta không hưởng được. Tụng kinh mà không tu hành theo kinh thì chẳng hưởng được lợi ích của kinh, của kẻ tu hành.",
"15": "Niết-bàn (Nibbàna)",
"16": "Bởi vì người không buông lung thì được chứng nhập Niết-bàn và không còn luân hồi sanh tử tiếp nối nữa. Còn người buông lung tuy sống mà vẫn như thây chết, không biết hướng thiện, nỗ lực làm lành.",
"17": "Bài này tiếp bài trên, khuyên đừng nên phóng dật mà gắng chuyên cần.",
"18": "Cảnh giới của chư Phật, Bích chi và A-la-hán.",
"19": "Muốn chứng đặng Niết-bàn thì phải trừ 4 ách: dục ách (Kamayogo sự tham dục), hữu ách (Bha-vayogo mê chấp ba cõi), kiến ách (Ditthiyogo điều tà kiến, ác kiến), vô minh ách (Avijjayogo sự mê mờ).",
"20": "Như cõi đất cao có thể tránh khỏi thủy tai. Kẻ trí khi chứng được A-la-hán thì không còn bị phiền não quấy nhiễu, nhận chìm.",
"21": "Các phiền não tham, sân, si buộc ràng và sai sử chúng sanh trong vòng ba cõi.",
"22": "Ma già (Maghavà) tên khác của trời Đế Thích (Sarka) khi chưa đủ phúc báo để làm trời, Đế Thích ở nhân gian tên là Ma già, nhờ công đức siêng năng quét tước sạch sẽ mà được làm chủ cõi chư Thiên.",
"23": "Kiết sử (Samyojana) tức là phiền não (Kilesa) danh từ chuyên môn nhà Phật.",
"24": "Mấy câu này đều hình dung cái tâm.",
"25": "Khi chứng được A-la-hán thì vô lậu thiện nghiệp viên mãn, hữu lậu ác nghiệp và hữu lậu thiện nghiệp đã hết rồi, không còn tạo nghiệp mới nữa, và tuy ở trong đạo quả viên mãn mà thường làm những việc lợi tha một cách tự nhiên.",
"26": "Kết quả thắng lợi là chỉ có cảnh giới Thiền định được tiến bộ.",
"27": "Không nên nhiễm trước vào Thiền cảnh đã chứng được, phải nỗ lực cầu tiến mãi.",
"28": "Phật giáo đồ các nước Phật giáo nam phương mỗi khi lâm chung có lệ thỉnh chư Tăng đến để cúng dường làm phước lần chót. Chư Tăng liền tụng bài bài kệ này ba biến.",
"29": "Đem tâm hướng về 10 hạnh ác (Akusala): sát sinh (Panatipato), thâu đạo (Adinnadanam), tà dâm (Kamesumicchacara), vọng ngữ (Musavado), lưỡng thiệt (Pisunavaca), thô ác ngữ (Pharusava-ca), ỷ ngữ (samphap palapo), tham (abhijjha), sân (Viyapado), tà kiến (Micchadithi).",
"30": "Đem tâm hướng về 10 hạnh lành (Kusala): cúng dường (Danam), trì giới (Silam), tu thiền định (Bhavana), tôn kính (Apacaijannam), tác sự ( Vey-yavaccam), hồi hướng công đức (Pattidacam), tùy hỷ công đức (Pattanumodana), thính pháp (Dham-musavanam), thuyết pháp (Dhammadesana), chánh kiến (Dithujjukamman).",
"31": "Ngài Ngô Chi Khiêm dịch là Phẩm Vương Hoa.",
"32": "Chinh phục (Vijessati), là theo Pali nguyên chú. Bản chú thích kinh Pháp cú rất xưa và đầy đủ chi tiết bằng văn bản Pali của Ngài Buddahaghosa, căn bản của các lời chú thích sau này. Bản do E.W.Burlinghame dịch ra Anh văn trong loại sách Harvard Oriental serie là hiểu xác thật. Bản ở Miến Điện chép là vicessati, thì nên dịch là “chọn tìm” hoặc “dò xét ”.",
"33": "Địa giới (Pathavi) là chỉ tự kỷ hay tự thân (Atta-bhava). Bản Dhammapada Anh văn của Đại đức Narada dịch, trang 8, có chú thích rằng: “This is one who will understand this self as if really is”. câu này có nghĩa “như thật tự biết rõ mình”.",
"34": "Diêm ma giới (Yamalokà), theo nguyên chú thì bao quát cả 4 giới (Catudbhidam apayalokan ca): địa ngục, ngạ quỉ, súc sanh và a tu la (Asura). Bản chú thích bằng Anh văn của Ngài Narada nói: “The fourwoeful states, viz: Hell (địa ngục), Animal kingdom (súc sanh), Peta realm (ngạ quỉ) and the Asura realm(A tu la)”.",
"35": "Thiên giới (Sadevakam), theo nguyên chú thì bao quát 6 cõi trời dục giới và nhân giới (Imamsade- Vakanit mannussalokanca). Ngài Narada chú: “ Namely the world of human beings and the six celestial realm’s”.",
"36": "Pháp cú (Dhammapada tức là pháp tích, pháp, như ba mươi bảy đạo phẩm (Bodhipakkhikadham-ma) v.v...",
"37": "Thợ khéo là thợ làm tràng hoa, để ví dụ cho người khéo giảng nói Pháp cú, có lớp lang, không lộn xộn, như thợ xâu hoa vậy.",
"38": "Hữu học (Sekha) tức là các vị chứng sơ quả Tu đà hoàn (Sotapattiphala), nhị quả Tư đà hàm (Sa-kadagamiphala), tam quả A na hàm (Anagam-phala), và sơ quả hướng, nhị quả hướng, tam quả hướng, tứ quả hướng, vì những vị này còn phải học tập giới, định, huệ. Đến khi chứng tứ quả A-la-hán mới được gọi là Vô học (Asekha).",
"39": "Bài tụng trên là hỏi, bài này đáp.",
"40": "Sự dụ hoặc của dục cảnh.",
"41": "Những người đang say ngủ trong xóm làng giữa đêm khuya, bị nước lũ cuốn đi mà không hay biết gì. Người mê miết trong dục lạc cũng vậy.",
"42": "Cảnh dục lạc.",
"43": "Mâu ni (Muni) có nghĩa là người trầm lặng, nhân từ, trí tuệ, thánh giả, ở đây chỉ hàng Sa-môn khất thực.",
"44": "Nguyên văn của câu này là “Naparesam kataka-tam” dịch thẳng là “Chẳng nên dòm ngó người khác làm hay không làm”.",
"45": "Chiên đàn na (Candana) Đa gia la (tagara), tên hai thứ cây thơm, Mạt lị ca (Malika) là một thứ hoa nhỏ thơm mọc tùm lum như giây bìm.",
"46": "Bạt tất kỳ (Vassiky) là vũ quý hoa.",
"47": "Luân hồi (samsara) chỉ sự sanh tử luân chuyển mãi không ngừng.",
"48": "Thọ quả báo lành dữ trong tương lai tức là thân dị thục (vipaka) ở đây chỉ riêng ác quả.",
"49": "Đây chỉ thiện quả.",
"50": "Cô sa (kusa) tên cỏ thơm, nguyên văn là Kusag-gena, tức là dùng đầu ngọn cỏ cô sa.",
"51": "Người tư duy Chánh pháp (Sankhata dhamman) là người thâm nhập Chánh pháp, đây là người giác ngộ Tứ đế.",
"52": "Muốn sữa đông đặc thành đề hồ không phải một ngày một đêm mà đông được kịp.",
"53": "Trong Hán văn chữ này cũng gọi là đầu thủ, đầu não.",
"54": "Bản chữ Nhật dịch là Hiền phẩm.",
"55": "Người không còn điều ác ở thân khẩu ý nữa, chuyên việc tế độ chúng sanh.",
"56": "Chư Phật và A-la-hán.",
"57": "Khắc chế năm căn đừng cho thấy, nghe, ngửi, nếm, xúc điều quấy.",
"58": "Cảnh giới Niết-bàn.",
"59": "Cảnh giới sanh tử.",
"60": "Cảnh giới sanh tử. Câu này ý nghĩa liên quan với câu trên.",
"61": "Giác chi (Sambodhiyangam) là thất Bồ đề phần hay là “thất giác chi” là: niệm giác chi (Satisanm-bojjhango), trạch pháp giác chi (Dhammavicayas-shojjhango), tinh tấn giác chi (Viriyasambojjhan-go), hỷ giác chi (Pitisam bojjhango), khinh an giác chi (Passadhisambojjhango), định giác chi (Sama-dhisambojjhango), xả giác chi (Upekhasambojjha-ngo).",
"62": "Chứng được Niết-bàn, giải thoát tự tại.",
"63": "Nguyên văn: Khinasava, dịch nghĩa là “Dứt hết các lậu” hoặc “các lậu đã sạch hết ”, tức là dứt hết mọi phiền não.",
"64": "A-la-hán (Arahant) tức là bậc thánh đã dứt hết phiền não, chứng Niết-bàn, không bị sanh tử nữa.",
"65": "Trói buộc (Gantha) có bốn thứ: Tham (Abhijjha), sân (Vijjapada), giới cấm thủ (Sibbhataparomasà), kiến thủ (Idan saccabhinivesa).",
"66": "Con đường hữu vi lậu nghiệp đã đi cùng. Có chỗ gọi là “các lậu đã dứt sạch, việc tu hành đã xong, phạm hạnh đã thành lập”.",
"67": "Con ngỗng mỗi khi ra khỏi ao thì chẳng còn nghĩ tưởng đến mồi, cỏ, nước trong ao là của mình. Vị A-la-hán đã xuất gia rồi thì không còn luyến tưởng tới gia tài của cải nữa.",
"68": "Chẳng còn hoạt động theo nghiệp lực.",
"69": "Biết rõ sự ăn uống là cốt để duy trì tánh mạng mà tu hành.",
"70": "Chứng được Niết-bàn gọi là giải thoát (Vimokha); lại gọi là không (Sinnàta), vì không còn tham, sân, si, phiền não; lại gọi là vô tướng (Animitta) vì từ nay đã được tự tại không còn đắm trước tưởng tham dục.",
"71": "Lậu có bốn thứ: dục lậu (Kamasava), hữu lậu (Bhavasava), kiến lậu (Ditthasava), vô minh lậu (Avijjasava).",
"72": "Nhân đà yết la (Indakhila), nhiều bản dịch là môn hạn (chấn cửa) tức là đặt một tảng đá giữa chổ cửa lớn, dùng chấn then cửa để đóng cho chắc. Có một chỗ nói indakhila theo Phạn tự là indra-khila tức là cái trụ của Nhân đà la (Đế thích). Ở tại chỗ tiến vào thành, dựng một cái trụ lớn để tượng trưng chỗ ở của Nhân đà la (thần bảo hộ của dân Ấn Độ). Chính ngày xưa đã dịch là cái tràng kiên cố, là bảy tràng Đế Thích, là đài tọa.",
"73": "Vô tín (Assaddha) hoặc dịch là bất tín, ý nói vị Thánh nhân tự mình chứng biết chứ không phải do ai làm cho giác ngộ.",
"74": "Các nghiệp thiện, nghiệp ác trong vòng hữu lậu thế gian.",
"75": "Sanh tử luân hồi.",
"76": "Nguyên văn chép: Nina là chỗ thấp, Thala là chỗ cao.",
"77": "Theo bản Tích Lan thì chữ này là Dhammapada nên dịch là “Pháp cú” nhưng theo bản của “Hiệp hội xuất bản Pali thánh điển” thì chép là Gathapada, chữ này nên dịch là “nhất cú kệ”.",
"78": "Câu này liên quan với câu trên.",
"79": "Càn thát bà (Gandhàbha) tên một vị thần ở Thiên giới.",
"80": "Tên một vị Thiên thần.",
"81": "Phạm thiên tức là Bà-la-môn thiên (Brahma).",
"82": "Nguyên văn: “Yitthamva hutamva”, nghĩa là cúng hy sinh, là tế tự, là cúng dường, v.v... Đồng nghĩa là cúng dường trong hội hè, lễ tiết; hutam thì có nghĩa là dự bị cung cấp khách qua đường, hoặc làm việc cúng dường dựa theo một tín ngưỡng về tác nghiệp và quả báo mà mình tin tưởng.",
"83": "Chỉ tứ quả thánh nhân.",
"84": "Người tuổi cao đức trọng.",
"85": "Các tăng lữ ở các nước Nam phương, mỗi khi thọ người lễ kinh thì đọc bài tụng này.",
"86": "Năm uẩn sanh diệt tức là các phép do nhân duyên hòa hợp không thường trú.",
"87": "Nguyên văn: Mappamannatha có hai nghĩa: (a) Mappanati, là “chớ khinh thị”. (b) Mappamannati, là “chớ tưởng ít”.",
"88": "Đao trượng (Danda) cũng dịch là hình phạt.",
"89": "Chỉ vị A-la-hán đã sạch hết các lậu hoặc.",
"90": "Đây là một cách ngồi xổm, đặc biệt là người tu ngoại đạo xưa Ấn Độ, thường dùng để hành hạ xác thân.",
"91": "Bài này nói về cách tu khổ hạnh vô ích, không thể chứng được Niết-bàn.",
"92": "Trí và hành đầy đủ.",
"93": "Nói về sự già.",
"94": "Thế giới bị 11 thứ lửa này thường thiêu đốt: tham (raga), sân (dosa), si (moha), bệnh (vyad-hi), lão (jara), tử (marana), sầu (soda), bi (Pariv-eda), khổ (dukkha), ưu (domandsa), não (upya-sa).",
"95": "Ví vô minh.",
"96": "Dụ trí tuệ.",
"97": "Chín chổ nơi thân: hai mắt, hai mũi, hai tai, miệng, đường đại, đường tiểu.",
"98": "Thân này do trên 300 đốt xương hợp thành.",
"99": "Lầm nghĩ thân này mỹ lệ êm đềm.",
"100": "Hư ngụy (makkho), xưa dịch là che lấp (phủ)",
"101": "Chỉ Phật, Bích chi, La hán.",
"102": "Đây là lời đức Thích ca khi thành đạo, tâm sinh hoan hỷ mà nói ra. Sau này có lần nhân ngài A-nan hỏi nên Phật nói lại lời đó. Kẻ làm nhà chỉ nguyên nhân luân hồi, lòng tình dục, nhà là chỉ thân thể, rui mè là chỉ các thứ dục khác, kèo cột là chỉ vô minh.",
"103": "Thông thường nói ba thời là đầu đêm, giữa đêm, cuối đêm. Ở đây ba thời chỉ vào một đời người thanh niên, trung niên, lão niên. Người ta lúc thanh niên nên nỗ lực học tập, trung niên nên hoằng pháp, tu Thiền định v.v... Nhưng trong hai thời gian đó mà chưa kịp thích thời hành sự thì lúc lão niên phải tỉnh ngộ học tập gấp rút, nếu không thì luống uổng một đời, mang lấy thống khổ chẳng ích chi.",
"104": "Phật giáo chủ trương mỗi cá nhân phải tự lực lo giải thoát cho mình. Phật giáo đồ phát nguyện quy y phật, Pháp, Tăng, Tam Bảo, không có nghĩa là phát 1 lời cầu đảo để Tam Bảo lo giải thoát cho. Song Tam Bảo là thầy chỉ đạo tu hành đúng đường để được giải thoát. Vậy nên, muốn đến cảnh giới giải thoát tự tại thì tự mỗi người phải gắng sức thực hành đúng lời Tam Bảo chỉ dạy.",
"105": "Chỉ quả vị La hán.",
"106": "Mạn la phạm (Maluva) một loại dây bìm. Cây ta la khi đã bị nó leo quấn vào thì khô chết ngay.",
"107": "Cách tha cách (Kattha), loại cây lau. Có tên là Cách tha cách trúc (Velusankhatakattha), hễ ra hoa kết trái rồi thì chết liền.",
"108": "Chỉ việc giải thoát sanh từ.",
"109": "Ở Tích Lan (Xri Lanca) giải thích là luân hồi.",
"110": "Sau khi đức Phật thành đạo, lần đầu Ngài trở về hoàng cung tại thành Ca tỳ la (Kapila), sáng hôm sau Ngài vẫn chiếu lệ mang bát đi khất thực. Vua Tịnh Phạn (Suddhodana) thấy vậy vội bước đến trước Phật mà nói rằng: “Này con ơi! Sao con làm nhục nhà ta vậy? Con vốn là chủ thành này, từng ở trên châu báu, nay cứ cầm bát lần đi từng nhà, không hổ nhục cho ta lắm sao?”. Đức Phật liền nói cho vua nghe đó là phép tắc lâu đời của chư Phật, và nói hai bài này. Nên theo chỗ chú giải xưa này thì hai bài này có nghĩa như sau: bài 168: “Chớ nhác bỏ việc lần theo từng nhà khất thực. Cẩn thận giữ thật đúng hạnh trì bát này, ai làm theo hạnh này thì đời này, đời sau đều khoái lạc”; bài 169: “Cẩn thận làm đúng hạnh này, chớ làm theo sự buông thả. Ai làm theo đúng hạnh này thì đời này, đời sau đều được khoái lạc “.",
"111": "Lầu sò chợ bể là dịch nghĩa từ chữ ”Thần lâu hải thị” để chỉ thị cảnh huyễn hóa không thật. Những làn khí bốc lên trên mặt biển, đụng phải ánh nắng, hoặc là không khí tương phản mà hiện ra những bóng hình nhìn xa như lâu đài chợ búa. Người xưa tin những làn khí ấy là hơi của giống sò thần tự dưới đáy bể phun lên.",
"112": "Nhất pháp (Ekham Dhanman) tức la chân đế, chân lý (Saccam).",
"113": "Dự lưu quả (Sotapattiphalam) là quả vị đầu trong bốn quả vị Niết-bàn Thanh văn.",
"114": "Hai bài này Phật đối Ma nữ mà nói.",
"115": "Ý toàn câu là “Cái tình dục đã bị chinh phục rồi, thì dù đang ở thế gian này, nó cũng không thể theo dõi người kia nữa”.",
"116": "Đã bỏ hết ái dục.",
"117": "Trong Tứ phần (giới bản) đức Như Lai Tỳ Bà Thi dạy: “Nhẫn nhục đệ nhất đạo, Phật thuyết vô vi tối, xuất gia não tha nhơn, bất danh vi Sa-môn”.",
"118": "Nguyên văn: Patimokkha tức là Biệt giải thoát luật nghi giới, gồm 227 giới điều chủ yếu mà tất cả Tỷ-kheo phải giữ.",
"119": "Chỉ tám định (Atthasalacattu): bốn thiền định và bốn không định.",
"120": "Thọ chi đề (Rukkhacetia) là “thọ miếu”, vị thọ thần của Aán Độ tín ngưỡng. Lấy cây làm đối tượng sùng bái, như đối với tháp miếu vậy.",
"121": "Bát Chánh đạo (Ariyam utthangikkhamamagam): chánh kiến (Samaditthi), chánh tư duy (Sammasan-kappa), chánh ngữ (Sammavaca), chánh nghiệp (Samakamanta), chánh mạng (Sammajiva), chánh tinh tấn (Sammavayama), chánh niệm (Samma-sati), chánh định (Samasamadhi). Hai câu này chỉ về đạo diệt khổ, nói gọn là Đạo đế.",
"122": "Nhật bản dịch là An lạc phẩm.",
"123": "Phật tự xưng.",
"124": "Tật bệnh đây chỉ các phiền não thống khổ.",
"125": "Không còn các phiền não chướng như tham, sân, si v.v…",
"126": "Lúc Phật ở tạm nơi thôn của một Bà-la-môn tên Ngũ ta la (Pancasala), một hôm Ngài vô xóm làng khất thực, không gặp ai cúng dường, một kẻ Ma vương đứng ở cửa làng thấy Phật mang bát đi về không, mới cười chọc nói rằng: “Ngài chưa được thực phẩm, ắt phải đi vào thôn xóm khất thực để giải quyết sự đói “. Nhân đó Phật nói bài này.",
"127": "Nguyên văn: Sankhara dịch là hành, tức là pháp hữu vi có sanh diệt, trong Pali chú thích uẩn (khandha).",
"128": "Câu này là câu tiếp liền trên dưới.",
"129": "Những Tỷ-kheo vì bị dục lạc mê hoặc, bỏ việc hành đạo để sinh hoạt theo thế tục, sau thấy kẻ khác tu hành có công quả, lại luống tỏ lòng hâm mộ, chứ tự mình không thành được chi.",
"130": "Năm câu 212-216, theo bản dịch của Đại đức Na ra da là: ”From endearment spings gief, from endearment spings fear for him who is free from endearment there is no gief, much less fear. From affection… From delight … From lust…, From craving…“.",
"131": "Chỉ bốn hướng, bốn quả và Niết-bàn, cộng là chín pháp thù thắng.",
"132": "Chỉ bốn Thánh đế.",
"133": "Chỉ giới, định, tuệ.",
"134": "Bậc thượng lưu (Ubddhamsoto), chỉ quả vị Bất hoàn (Anagami) gần đến Niết-bàn A-la-hán.",
"135": "Danh sắc (Namarapa) tức là tinh thần và vật chất, tâm và thân.",
"136": "Nếu tự chủ, ngăn trừ nóng giận kịp thời, mới là người thiện ngự, ngoài ra toàn như kẻ cầm cương hờ, chứ không khống chế được con ngựa.",
"137": "Nguyên văn còn có một chử “thiểu”, ít (Appam), tức là mình có vật gì dù ít, cũng có thể chia sớt cho người đến xin được.",
"138": "A đa la (Atula) là tên một người Phật tử xưa.",
"139": "Diêm phù kim (jambunaba) là tên đặc biệt để chỉ 1 thứ vàng phẩm chất rất quí. Ý nói vàng này từ sông Diêm phù (Jambu) mà có.",
"140": "Thánh cảnh hàng chư Thiên đây là chỉ 5 cõi trời Tịch cư (Panca Anddhvasabhumi): Vô phiền (A-viha), Vô nhiệt (Atappa), Thiện hiện (Suddassa), Thiện kiến (Suddssi), Sắc cứu kính (Akanittha) là năm chỗ của hàng A na hàm ở.",
"141": "Sa-môn (samano) ở đây chỉ những vị chứng ngộ bốn thánh quả.",
"142": "Nguyên văn: Papanca, gồm có nghĩa hư vọng và chướng ngại. Ở đây đặc biệt chỉ cho Aùi (Tan-ha), Kiến (Ditthi), Mạn (Mano).",
"143": "Pháp trụ (Dhammattha), có nghĩa là thực hành đúng pháp, an trụ phụng thờ đúng pháp, nên cũng dịch là “Phụng pháp”.",
"144": "Lỗ mãng (Sahasa), bao hàm nghĩa cẩu thả, khinh xuất, độc đoán. Ở đây chỉ cho cái quan niệm bất chính xác, bởi chịu ảnh hưởng của tham, sân, si, bố úy mà sinh ra.",
"145": "Do thân (Kayena), nguyên chú thích là “do danh thân” (Namakayena). Trong văn Pali chia năm uẩn ra hai loại: A. Danh thân (Namakayena), tức danh uẩn là thọ, tưởng, hành, thức uẩn; B. Sắc thân (Rupakayena) tức là sắc uẩn. Như vậy, do thân thật thấy Chánh pháp tức là nói do tâm thật thấy Chánh pháp, là do tự nội tâm chứng ngộ Chánh pháp, đích thực, chứ không vịn lấy chỗ ngộ do người làm cho mình ngộ … Chữ thân là một chứa nhóm, đồng nghĩa với chữ uẩn.",
"146": "Trưởng lão (Thera), tiếng tôn xưng người đã giữ giới Tỷ-kheo mười năm trở lên, nhưng vốn trọng về thực tu thực chứng, nếu không thì chỉ là cách gọi suông.",
"147": "Chỉ lý Tứ Đế.",
"148": "Chỉ bốn quả, bốn hướng và Niết-bàn.",
"149": "Chỉ hết thảy giới luật.",
"150": "Đặc biệt chỉ điều phục năm căn: nhãn, nhĩ, tỉ, thiệt, thân.",
"151": "Thiện đây chỉ cái thiện hữu lậu, là cái Thiện làm với tâm bỉ thử ngã nhân.",
"152": "Biết giới, biết định, biết tuệ.",
"153": "Chữ Ariya có nghĩa là hiền đức, cao thượng. Phật đối với người đánh cá tên Ariya mà nói ra bài này.",
"154": "Giới luật đây chỉ cho Biệt giải thoát luật nghi giới, căn bản luật nghi giới. Đầu đà (Dhutanga) là hạnh tu kham khổ, tiết độ trong việc ăn, mặc, ở, để dứt sạch phiền não, gồm có mười hai hạnh, riêng cho một số người tu.",
"155": "Học ba tạng (Tripitaka).",
"156": "Bốn đế (tứ cú): Khổ (dukkha), khổ tập (dukkha-ssamudaya), khổ diệt (dukkhanirodha) khổ diệt đạo (dukkhaniaodhagaminipatipada). Xưa dịch là: khổ, tập, diệt, đạo.",
"157": "Chỉ Niết-bàn.",
"158": "Chỉ Phật đà. Phật đủ năm mắt: nhục nhãn (namsa-cakkhu), thiên nhãn (dibhacakkhu), huệ nhãn (panna-cakkhu), Phật nhãn (Buddhacakkhu), nhất thế trí nhãn (Samantacakkhu).",
"159": "Tứ đế, Bát chánh đạo, Niết-bàn",
"160": "Chỉ cho tham, sân, si v.v…",
"161": "Các Tăng già Tích Lan mỗi khi khai một hội nghị để luận bàn việc trọng đại, thường lấy bài này làm khẩu hiệu kêu gọi.",
"162": "Như Lai chỉ bày chánh đạo, còn hành đạo là do người.",
"163": "Tất cả hiện tượng.",
"164": "Du già (Yoga) tức là định.",
"165": "Thiện Thệ (Sugato) tức là Phật đà.",
"166": "Chẳng biết sự nguy hiểm về cái chết là cách nào, ở đâu, lúc nào.",
"167": "Chỉ ý nghĩa của bài trên.",
"168": "Hai bài này đều mượn ví dụ để cắt nghĩa.",
"169": "Dụ thường kiến (Sassataditti) và đoạn kiến (Ucc-hedaditthi).",
"170": "Chỉ 12 xứ (dvrdasatana) mắt, tai, mũi, lưỡi, thân, ý, sắc, thinh, hương, vị, xúc, pháp.",
"171": "Chỉ sự dục lạc (nadirago).",
"172": "Chỉ quả vị lậu tận A-la-hán.",
"173": "Hổ tướng thứ năm (veyyagghapancaman) tức bằng với nghi thứ 5 (Vicikicchannivarana). Vì trong năm cái (ngăn, cheancanivarana) thì nghi cái (vicikicchannivarana)ở về thứ 5. Năm cái là: tham dục (kamacchanda), sân nhuế (viavada), hôn trầm thùy miên (thinamiddha), trạo cử ác tác (Uddhaccukukkucca), nghi (Vikicikiccha).",
"174": "Kiều-đáp-ma (Gotama) tức là đức Phật.",
"175": "Sắc thân gồm có 32 thứ bất tịnh: Tóc, lông, móng, răng, da v.v..",
"176": "Thánh tài là gia tài của Thánh giả (nhờ đó mà thành đạo quả), có 7: tín, giới, tàm, quý, văn, xả, huệ.",
"177": "Tuyết sơn (Himayanto) tức Hy mã lạp sơn.",
"178": "Lừa và Ngựa giao hợp với nhau sinh ra con gọi là La.",
"179": "Tín độ (Sidha) là con sông Aán Độ. Giống ngựa Tuấn sinh ở địa phương này.",
"180": "Kiều la (Kunjara) tên voi.",
"181": "Ý nói người chưa điêu luyện thì tánh hung hăng hơn cả voi ngựa, nhưng khi tu luyện được rồi thì quí hơn nhiều.",
"182": "Voi đến kỳ phát dục thường tiết ra một thứ nước thối tha và tính tình hung hăng khó trị.",
"183": "Cổ tích kể voi có lòng nhớ mẹ nó là có ý để khuyên người ta hãy hiếu thuận cha mẹ.",
"184": "Phật tự xưng.",
"185": "Ái dục có ba thứ: a) Dục ái (kamatanha), b) Hữu ái (Bhavatanha sự ái dục dính líu với thường kiến) c) Phi hữu ái (Vibhavatanha) sự ái dục tương quan với đoạn kiến. Trong sáu căn, ngoài sáu trần, đều là ái, họp thành 12: Dục ái 12,hữu ái 12, phi hữu ái 12, cộng thành 36 ái dục, 36 ái dục thường lưu động không ngừng như dòng nước, nên gọi là dục lưu.",
"186": "Là từ sáu căn phát ra.",
"187": "Chỉ Niết-bàn.",
"188": "Lìa thế dục để xuất gia.",
"189": "Xuất gia rồi lại hoàn tục.",
"190": "Chứng Niết-bàn.",
"191": "Bỏ sự tham đắm theo ngũ uẩn quá khứ, hiện tại và vị lai.",
"192": "Chỉ A-la-hán.",
"193": "Từ đây không còn luân hồi sanh tử nữa.",
"194": "Câu này theo nguyên văn là: Niruttipada Kovido, dịch thẳng là thông đạt và tha cú; tức chỉ cho bốn thứ biện giải vô hại (Catupatisambbida): Nghĩa vô hại (Atha) là thông suốt lý nghĩa; Pháp vô ngại (Dhamma) là thông suốt giáo pháp như 3 tạng 12 bộ; Từ vô hại (Nirutti), là thông suốt lời lẽ văn cú; Biện thuyết vô ngại (Patibhana), là giảng nói (biết thứ lớp của tự, cú, là chỉ môn biện thuyết vô ngại).",
"195": "Sau khi Phật thành đạo, từ Bồ đề tràng đi tới Lộc dã uyển, giữa đường gặp nhà tu của đạo khác, tên Ưu ba ca (Upaka), hỏi Phật rằng: ”Ôâng xuất gia theo ai?” “Thầy ông là ai”? “Ôâng tin tôn giáo nào?” Phật liền nói bài trên để trả lời.",
"205": "Bà-la-môn (Bhramana) ở đây là tiếng chỉ chung người hành đạo thanh tịnh, chớ không phải như nghĩa thông thường chỉ riêng về giai cấp đạo sĩ Bà-la-môn. Phẩm này Phật dạy, gọi là Bà-la-môn là cốt ở tư cách xứng đáng của họ, chứ không phải là tại dòng dõi, nơi sinh hay những gì hình thức bên ngoài.",
"206": "Các yếu tố cấu thành sanh mạng.",
"207": "Hai pháp là chỉ và quán.",
"208": "Bờ kia là chỉ sáu căn bên trong (Ajjhatikani cho Ayatanani); Mắt, tai, mũi, lưỡi, thân, ý. Bờ này là chỉ sáu trần bên ngoài (Bahirani cho ayatanani): sắc, thanh, hương, vị, xúc, pháp. Không chấp trước ta và của ta, nên nói là không bờ này, bờ kia.",
"209": "Nguyên văn là: dara, cũng cò thể dịch là bố úy.",
"210": "Ở đây chỉ giáo đồ Bà-la-môn.",
"211": "Chỉ tứ đế.",
"212": "Hạnh phúc (sukhí) bổn của Tích Lan viết là Suci, nên dịch thanh tịnh.",
"213": "Một số ngoại đạo Ấn Độ hay dùng da nai làm đồ trải ngồi và áo mặc.",
"214": "Áo phấn tảo (Pansukula civara), là thứ vải rẻo người ta vứt, người xuất gia lượm lấy giặt sạch chắp lại may áo cà sa mà mặc.",
"215": "Nguyên văn là Bhovadi, tức là Bho-vadi, dịch là “thuyết bồ”. Đây là tiếng tôn xưng nhau của giáo đồ Bà-la-môn dùng riêng với nhau trong khi nói chuyện.",
"216": "Bài này toàn dùng những đồ để khớp ngựa mà ví dụ: Đai da dụ lòng sân nhuế, cương dụ ái dục, dây dụ 62 tà kiến, sở thuộc (dây buộc ngựa) dụ những tập tánh tiềm tàng (anusaysg xưa dịch là “Tùy miên”, có 7 thứ: dục, tham, sân, mạn, ác kiến, nghi, vô minh). Chướng ngại dụ vô minh.",
"217": "Chỉ các phiền não tham dục.",
"218": "Khắc phục ngũ uẩn không cho tái sanh.",
"219": "Nguyên văn là Usabaha, dịch là trâu nái hay trâu chúa. Ở đây hàm chỉ sự thù thắng, là chỉ người hùng mạnh, vô úy, siêu quần.",
"220": "Thắng phục phiền não ma, uẩn ma và tử ma, gọi là người thắng lợi.",
"221": "Người Ấn Độ mê tín nước sông Hằng có thể rửa sạch tội lỗi, nhưng ở đây lại ý nói không còn các cấu nhiễm trong tâm người Bà-la-môn."
    }
}
