PhapCu_MinhDuc={
  "title": "Kinh Lời Vàng (Dhammapada)",
  "year": 1995,
  "author": "Minh Đức Triều Tâm Ảnh",
  "source": "dịch và thi hoá từ tiếng Pali",
  "link": "https://thuvienhoasen.org/a19502/kinh-loi-vang",
  "preface": "Kinh Pháp Cú còn, Giáo Pháp còn\nGiáo Pháp còn, kinh Pháp Cú còn.",
  "chapters": {
    "1": {
      "title": "Chương I - YAMAKAVAGGA - (Phẩm Song Đối)",
      "from_verse": 1,
      "to_verse": 20
    },
    "2": {
      "title": "Chương II - APPAMĀVAGGA - (Phẩm Không Phóng Dật)",
      "from_verse": 21,
      "to_verse": 32
    },
    "3": {
      "title": "Chương III - CITTAVAGGA - (Phẩm Tâm)",
      "from_verse": 33,
      "to_verse": 43
    },
    "4": {
      "title": "Chương IV - PUPPHAVAGGA - (Phẩm Hoa)",
      "from_verse": 44,
      "to_verse": 59
    },
    "5": {
      "title": "Chương V - BĀLAVAGGA - (Phẩm Kẻ Ngu)",
      "from_verse": 60,
      "to_verse": 75
    },
    "6": {
      "title": "Chương VI - PAṆḌTAVAGGA - (Phẩm Trí Hiền)",
      "from_verse": 76,
      "to_verse": 89
    },
    "7": {
      "title": "Chương VII - ARAHANTAVAGGA - (Phẩm A-la-hán)",
      "from_verse": 90,
      "to_verse": 99
    },
    "8": {
      "title": "Chương VIII - SAHASSAVAGGA - (Phẩm Một Ngàn)",
      "from_verse": 100,
      "to_verse": 115
    },
    "9": {
      "title": "Chương IX - PĀPAVAGGA - (Phẩm Ác)",
      "from_verse": 116,
      "to_verse": 128
    },
    "10": {
      "title": "Chương X - DAṆḌAVAGGA - (Phẩm Hình Phạt)",
      "from_verse": 129,
      "to_verse": 145
    },
    "11": {
      "title": "Chương XI - JARĀVAGGA - (Phẩm Già)",
      "from_verse": 146,
      "to_verse": 156
    },
    "12": {
      "title": "Chương XII - ATTAVAGGA - (Phẩm Tự Ngã)",
      "from_verse": 157,
      "to_verse": 166
    },
    "13": {
      "title": "Chương XIII - LOKAVAGGA - (Phẩm Thế Gian)",
      "from_verse": 167,
      "to_verse": 178
    },
    "14": {
      "title": "Chương XIV - BUDDHAVAGGA - (Phẩm Đức Phật)",
      "from_verse": 179,
      "to_verse": 196
    },
    "15": {
      "title": "Chương XV - SUKHAVAGGA - (Phẩm An Lạc)",
      "from_verse": 197,
      "to_verse": 208
    },
    "16": {
      "title": "Chương XVI - PIYAVAGGA - (Phẩm Thương, Ái)",
      "from_verse": 209,
      "to_verse": 220
    },
    "17": {
      "title": "Chương XVII - KODHAVAGGA - (Phẩm Phẫn Nộ)",
      "from_verse": 221,
      "to_verse": 234
    },
    "18": {
      "title": "Chương XVIII - MALAVAGGA - (Phẩm Uế Trược)",
      "from_verse": 235,
      "to_verse": 255
    },
    "19": {
      "title": "Chương XIX - DHAMMAṬṬHAVAGGA - (Phẩm Công Bình và Chánh Hạnh)",
      "from_verse": 256,
      "to_verse": 272
    },
    "20": {
      "title": "Chương XX - MAGGAVAGGA - (Phẩm Con Đường)",
      "from_verse": 273,
      "to_verse": 289
    },
    "21": {
      "title": "Chương XXI - PAKIṆṆAKAVAGGA - (Phẩm Tạp Lục).  Tạp Lục",
      "from_verse": 290,
      "to_verse": 305
    },
    "22": {
      "title": "Chương XXII - NIRAYAVAGGA - (Phẩm Khổ Cảnh)",
      "from_verse": 306,
      "to_verse": 319
    },
    "23": {
      "title": "Chương XXIII - NĀGAVAGGA - (Phẩm Voi)",
      "from_verse": 320,
      "to_verse": 333
    },
    "24": {
      "title": "Chương XXIV - TAṆHĀVAGGA - (Phẩm Ái Dục)",
      "from_verse": 334,
      "to_verse": 359
    },
    "25": {
      "title": "Chương XXV - BHIKKHUVAGGA - (Phẩm Tỳ-khưu)",
      "from_verse": 360,
      "to_verse": 382
    },
    "26": {
      "title": "Chương XXVI - BRĀHMAṆAVAGGA - (Phẩm Bà-la-môn)",
      "from_verse": 383,
      "to_verse": 423
    }
  },
  "verses": {
"1": "Các pháp, tư tác(1) dẫn đầu\nTư tác chủ ý bắc cầu đưa duyên\nNói, làm xấu ác, chẳng hiền\nBánh xe bò kéo, khổ liền theo sau!",
"2": "Các pháp, tư tác dẫn đầu\nTư tác, chủ ý bắc cầu đưa duyên\nNói, làm lành tốt, thiện hiền\nNhư hình dọi bóng, vui liền theo sau.",
"3": "“Nó đánh, nó cướp của tôi!\nLại còn nhục mạ lắm lời đắng cay!”\nAi mà ôm ấp niệm nầy\nLửa phiền thiêu đốt tháng ngày chẳng nguôi!",
"4": "“Nó đánh, nó cướp của tôi!\nLại còn nhục mạ lắm lời đắng cay!”\nNgười không ôm giữ niệm nầy\nLửa phiền chợt tắt, khổ rày tự tiêu!",
"5": "Nếu ai lấy oán báo thù\nOan oan tương báo, thiên thu hằng sầu\nTừ tâm, định luật nhiệm mầu\nLấy ân báo oán, còn đâu oán thù?",
"6": "Luận tranh chẳng có ích gì!\nTranh cường, hiếu thắng lắm khi phiền hà\nAi người suy ngẫm sâu xa\nNói năng tự chế, bất hòa lặng yên!",
"7": "Người hằng say đắm dục trần(2)\nUống ăn vô độ, trăm phần dể duôi\nMa Vương chúng vỗ tay cười\nCây cành mềm yếu, tơi bời gió lay!",
"8": "Người hằng quán niệm tự thân\nUống ăn tiết độ, tinh cần sớm hôm\nMa Vương đâu dễ khinh lờn\nGió qua núi đá chẳng sờn, chẳng lay!",
"9": "Người không tự chế, không chơn\nNgười mà tâm địa chẳng hơn thế phàm!\nLàm sao xứng mặc y vàng?\nLàm sao xứng đáng dự hàng Sa-môn?",
"10": "Người mà nhẫn nại tu hành\nNghiêm trì giới luật cao thanh, rỡ ràng\nKhen thay! Khéo mặc y vàng!\nKhen thay! Xứng đáng dự hàng Sa-môn!",
"11": "Phi chơn lại tưởng chánh chơn\nChánh chơn lại tưởng phi chơn, đó là:\nDuy trì ác kiến, ác tà\nNgu nhân nào thấy tinh hoa pháp mầu!",
"12": "Chánh chơn thấy rõ chánh chơn\nPhi chơn thấy rõ phi chơn, mới là:\nLìa xa ác kiến, ác tà\nTrí nhân dễ ngộ tinh hoa pháp mầu!",
"13": "Nhà ai vụng lợp, dột mưa\nCũng dường thế ấy, người chưa tu trì\nTâm nhiều tham ái, sân si\nDễ dàng xâm nhập sầu bi, não phiền.",
"14": "Nhà ai khéo lợp, khéo ngăn\nNước mưa không thể lại xâm nhập vào\nTâm người biết dựng vách rào\nÁi tham, phiền não dễ nào ghé vô!",
"15": "Đây thống khổ, kia thương đau!\nHai đời, kẻ ác muộn sầu chẳng vui\nBất an, ưu não rối bời\nMắt nhìn khổ báo, Phật, Trời thở than!",
"16": "Đây an lạc, kia hỷ hoan\nHai đời thiện hạnh lại càng thêm vui\nBình yên, hoa nở, nụ cười\nMắt nhìn phước quả thắm tươi bốn bề!",
"17": "Đây ưu não, kia khổ đau\nHai đời, kẻ ác muộn sầu thảm thương\nThở than nghiệp dữ đã vương\nChết vào khổ cảnh đoạn trường, than hơn!",
"18": "An vui, hạnh phúc hai đời\nTâm người thiện hạnh rạng ngời, hân hoan\nĐã mừng gieo được phước vàng\nSinh vào tiên cảnh, lại càng mừng hơn!",
"19": "Suốt thông kinh luật mặc dầu\nNếu không hành đạo, đếm trâu, đếm bò!\nDể duôi, tự mãn nằm co\nQua miền siêu thoát, gọi đò ai đưa?",
"20": "Ít thông kinh luật mặc dầu\nNếu chuyên hành đạo, tìm câu sửa mình\nSống đời chánh hạnh, quang minh\nQua miền siêu thoát, vô sinh, hưởng nhàn!",
"21": "Con đường phóng dật, nguy nan\nCon đường tỉnh thức, vinh quang nhiều đời\nBuông lung là kẻ chết rồi\nPháp mầu Bất Tử đợi người cần chuyên!",
"22": "Trí nhân thấy rõ cơ duyên\nTinh cần, kiên định vẫy thuyền sang sông\nAn vui, hoan hỷ tự lòng\nDự vào cảnh giới thanh trong Thánh mầu!",
"23": "Trí nhân tinh tấn thiền hành\nKiên trì, nỗ lực duyên sanh Niết-bàn\nMa Vương khó buộc, khó ràng\nTự do tối thượng, thênh thang bến bờ!",
"24": "Tinh cần, chánh niệm hỡi ai!\nGiữ gìn tịnh hạnh trong ngoài chăm chuyên\nTự điều, theo pháp sống thiền\nNỗ lực sung mãn, thiện hiền tấn tăng!",
"25": "Sống không phóng dật, kiên trì\nTự điều, tự chế thường khi mới là!\nChí người thiện trí cao xa\nXây hòn đảo lớn, quê nhà trú thân!",
"26": "Si mê, cuồng sĩ buông lung\nRiêng người thiện trí canh chừng niệm tâm\nTâm tâm, niệm niệm tinh cần\nGiữ gìn kho báu, thế nhân dễ gì!",
"27": "Người không phóng dật, dể duôi\nNgười không mê đắm niềm vui dục trần\nTỉnh thức, thiền quán tinh cần\nSẽ hái, sẽ gặt phước phần sum suê!",
"28": "Niệm tâm: Phóng dật lùi xa\nThoát khỏi phiền não – binh ma cuối đèo!\nCao sơn, trí tuệ khéo trèo\nNgu si, đau khổ - nằm queo đám người!",
"29": "Trú niệm giữa kẻ buông lung\nTỉnh thức giữa đám mê mung, loạn cuồng\nNhư con tuấn mã kiên cường\nSau lưng bỏ lại lươn ươn ngựa hèn!",
"30": "Chỉ nhờ đức tánh tinh cần\nĐế Thích cai quản bốn tầng Thiên Vương\nDể duôi thiên hạ coi thường\nTinh cần mãi được tán dương đời đời!",
"31": "Tỳ-kheo vui thích tinh cần\nSợ hãi phóng dật, niệm tâm canh chừng\nBước đi như đám lửa hừng\nThiêu bao phiền não, kiết thừng(3) tiêu tan!",
"32": "Tỳ-kheo vui thích tinh cần\nSợ hãi phóng dật, chuyên tâm quán thiền\nKhỏi rơi đọa xuống các miền\nVị ấy nhất định kề bên Niết-bàn!",
"33": "Khó thay! Trì nhiếp tâm người\nChập chờn, dao động cả đời không yên\nThợ tài uốn thẳng cây tên\nGiữ tâm cũng vậy, thiện hiền khéo tu!",
"34": "Cá kia quăng bỏ lên bờ\nVẫy vùng, hốt hoảng đợi giờ chết thôi!\nCho hay tâm lạc chợ đời\nCũng dường thế ấy, hãy rời lực ma!",
"35": "Tâm ta khinh động bất an\nKiếm tìm dục lạc, chạy quàng, chạy xiêng\nLành thay! Chế ngự thành hiền\nTâm được điều phục, diệt phiền, được vui!",
"36": "Tâm ta tế nhị vô cùng\nDễ nào thấy biết, canh chừng làm sao?\nKiếm tìm dục lạc xôn xao\nTâm được phòng hộ, xiết bao an lành!",
"37": "Xa xôi diệu vợi lữ trình\nĐến đi đơn độc, ẩn mình hang sâu(4)\nĐiều tâm: Hạnh phúc cơ mầu\nVui sao! Thoát khỏi Ma đầu trói trăn!(5)",
"38": "Tâm chưa an trú vững vàng\nLàm sao chánh pháp dễ dàng liễu tri?\nNiềm tin rung động từng khi\nTrí tuệ như vậy, mong chi thành toàn?!",
"39": "Tâm không ái dục đầy tràn\nTâm không sân hận, chẳng mang lửa phiền\nVượt lên thiện, ác đôi miền\nBậc luôn tỉnh thức, chẳng hiềm sợ chi!",
"40": "Thân này gốm sứ mỏng manh\nTâm này kiên cố thủ thành chống Ma!(6)\nGươm vàng trí tuệ vung ra(7)\nGiữ gìn chiến thắng, một tòa “vô tham”!(8)",
"41": "Mai kia thương xót thân này\nNằm vùi đất lạnh, tháng ngày nắng mưa\nVô tri một đống thịt thừa\nKhúc cây vô dụng, xẻ cưa được gì?",
"42": "Kẻ thù hiềm hại kẻ thù\nOan gia chước hiểm báo cừu oan gia\nGhê hơn, tâm hướng ác tà\nVạn lần nguy khốn cho ta, cho người!",
"43": "Điều mà quyến thuộc, mẹ cha\nChẳng thể làm được cho ta, cho người\nNhưng tâm chơn chánh hướng rồi\nThành tựu tốt đẹp vẹn mười, vẹn trăm!",
"44": "Ai người thấu triệt “cái ta”?\nThấu triệt Thiên giới, Dạ Ma các hàng?\nAi người khéo giảng “Pháp vàng”?(9)\nNhư tay thiện xảo kết tràng hoa tươi?",
"45": "Ai người chinh phục “cái ta”?\nChinh phục Thiên giới, Dạ Ma các hàng?\nBậc “Hữu học”(10) giảng Pháp vàng\nNhư tay thiện xảo kết tràng hoa tươi.",
"46": "Thân như bọt nước đầu gềnh\nRỗng không, huyễn ảo, diệt sinh vậy mà!\nTrượng phu bẻ gãy tên hoa\nVượt lên tầm mắt, Tử Ma khó tìm!",
"47": "Ai còn thu nhặt hoa hương,\nĐắm si, tham nhiễm bên đường biết hay?\nTử Thần mang kẻ ấy ngay\nNhư cơn lũ cuốn ngủ say cả làng!",
"48": "Ai còn thu nhặt hoa hương\nĐắm si, tham nhiễm bên đường chẳng thôi?\nCoi chừng Thần Chết tới nơi\nBắt làm nô lệ, rồi đời kẻ ngu!",
"49": "Như ong kiếm tí mật thôi\nSắc hương chẳng hại, lá chồi cũng không\nKhẽ khàng chút nhụy lót lòng\nBậc Thánh cũng vậy, thong dong vào làng!",
"50": "Lỗi người tìm trách sao nên\nDầu phải, dầu quấy chen xen chẳng gì?\nGẫm ta làm được điều chi?\nLặng im, tự kiểm, tu trì mới hay!",
"51": "Hoa kia đẹp đẽ dường bao!\nSắc màu tươi thắm nhưng nào có hương\nNgôn lời dệt gấm thêu chương\nKhông hành, chỉ nói là phường bỏ đi!",
"52": "Hoa kia đẹp đẽ dường bao!\nSắc màu đã thắm lại ngào ngạt hương.\nNgôn lời trong sáng như gương\nNói làm là một, văn chương dám bì!",
"53": "Đó đây lác đác đầu cành\nHái tìm từng đóa xâu thành tràng hoa\nChúng sanh giữa cõi ta bà\nViệc lành thu góp kết tòa thiện tâm!",
"54": "Hương thơm tối thắng diệu hoa\nLàm sao ngược gió bay xa mọi đường?\nHương thơm đức hạnh phi thường\nXông lan khắp cả muôn phương ngạt ngào!",
"55": "Hương sen, hương lý, hương lài\nChiên-đàn cùng với một vài thắng hương\nDẫu thơm, đâu thể so lường\nHương người giới hạnh, phi thường thế gian!",
"56": "Hương sen, hương lý, hương lài\nChiên-đàn cùng với một vài thắng hương\nHương người giới hạnh phi thường\nXông bay bốn cõi Thiên Vương ngát ngào!",
"57": "Ai người trú niệm tinh cần,\nAi người siêu thoát dự phần vô vi?\nAi người đức hạnh, chánh tri?\nMa Vương chẳng thấy đường đi, lối về.",
"58": "Hoa sen dễ mến, dễ ưa,\nMọc lên từ đống bùn nhơ vệ đường.\nMôn đệ đức Chuyển Pháp Vương\nTrí tuệ chiếu sáng khắp phường tối tăm!",
"59": 58,
"60": "Người mất ngủ, đêm dài ôi!\nLữ khách mệt mỏi, xa xôi dặm trình\nKẻ mê si, lắm vô minh\nLuân hồi ngút mắt, khổ sinh nghìn trùng!",
"61": "Xa xôi thiên lý lữ trình\nKhông gặp thân hữu bằng mình hoặc hơn\nThà rằng vững bước cô đơn\nChẳng nên kết bạn với phường ngu si!",
"62": "“Con tôi, tài sản của tôi”!\nĐó là ưu não của người cuồng si\nTrong “ta”, “ta” ấy có gì?\nTài sản, con cái - khác chi mộng trường!",
"63": "Người ngu xin hãy biết mình!\nThà rằng như vậy, thông minh mấy phần\nNgu si lại tưởng trí nhân\nVới kẻ như vậy, vạn lần chí ngu!",
"64": "Người ngu, cho dẫu trọn đời\nSống gần trí giả, uổng lời cao siêu\nKhông hành chánh pháp nửa điều\nMuỗng canh nào biết trong niêu vị gì?!",
"65": "Phút giây thân cận đại hiền\nVới người hữu trí là duyên vạn đời\nThấy ngay chánh pháp tuyệt vời\nLưỡi kia nếm thưởng biết nồi canh ngon!",
"66": "Ơi người thiểu trí đại ngu!\nLại xem “tự ngã” kẻ thù khốn thay!\nTrở đi, lộn lại cõi này,\nMãi tạo ác nghiệp, khổ rày ai mang?!",
"67": "Ác nghiệp là nghiệp chẳng lành\nĂn năn, hối quá phát sanh lòng người\nĐến khi quả dữ chín muồi\nLệ tuôn đầy mặt, lạy trời khóc mưa!",
"68": "Thiện nghiệp là nghiệp tốt lành\nThỏa thích, mát mẻ phát sanh lòng người\nĐến khi lạc báo chín muồi\nThọ hưởng phước quả, nói cười hân hoan!",
"69": "Ác hạnh như mật, như đường!\nNgười ngu nghĩ vậy, quả thường chưa sanh\nĐến khi ác báo rành rành\nThan Trời, trách Phật, khổ thành khổ hơn!",
"70": "Người ngu, ép xác, đặt bày\nLiếm ăn đầu cỏ dính rây chút gì\nPhép tu khổ hạnh sao bì\nMột phần mười sáu liễu tri pháp hành!",
"71": "Ác hạnh không tạo quả ngay\nNhư sữa tươi mới, sớm ngày chưa đông\nNghiệp kia theo kẻ cuồng ngông\nDưới tro âm ỉ than hồng, biết chăng?",
"72": "Người ngu sa đọa tâm hồn\nTri thức hái lượm, cúi luồn công danh\nĐầu to bửa nát tan tành\nHoa hương úa rã, cây cành thảm thương!\n\nTrong sự sụp đổ của mình\nHái thâu kiến thức, góp danh vọng đời\nNgười ngu đâu biết, than ôi!\nChính chúng bửa nát bể hai cái đầu!",
"73": "Người ngu cuồng vọng tiếng tăm\nMuốn ngồi trên trước Chư Tăng Thánh, phàm\nQuyền uy tu viện cao sang\nMuốn người đưa đón kiệu vàng, lọng hoa!",
"74": "Người ngu bản ngã phô trương\nCướp công đồng đạo, nêu gương mình làm\nƯa sai, ưa lệnh rắp hàng\nMạn cuồng tăng thượng, ái tham lũ dòng!",
"75": "Con đường lợi lộc trần gian\nCon đường vô dục, Niết-bàn khác nhau\nSa-môn say đắm, dễ đâu!\nKhởi tâm nhàm chán, mồi câu xa rời!",
"76": "Trí hiền điểm lỗi cho ta\nĐiều xấu nên sửa, điều chưa thành toàn\nVí như chỉ chỗ chôn vàng,\nBạn người như vậy, tốt càng tốt hơn!",
"77": "Ai khuyên kẻ khác làm lành\nNgăn ngừa niệm dữ, pháp hành gắng tu\nNgười hiền cảm kích kính yêu\nCòn phường xấu ác, ra điều chẳng ưa!",
"78": "Với người xấu ác, không thân!\nVới kẻ ti tiện, lại cần tránh xa!\nTrí hiền, bạn tốt mới là:\nThượng nhân cao quý điểm hoa lòng mình!",
"79": "Vui thay! Giáo pháp thấm nhuần\nVui thay! An lạc, thân tâm nhẹ nhàng!\nTrí nhân thỏa thích Con Đàng\nCủa bậc Thánh tuệ, Lời Vàng thuyết ngôn.",
"80": "Giỏi thay! Dẫn nước, đào mương!\nMũi tên khéo uốn, thành đường thẳng ngay!\nBánh xe tròn đẽo, tài hay!\nTự điều, tự kiểm mới tày trí nhân!",
"81": "Như núi đá dựng trời cao\nTám phương gió bão dễ nào chuyển lay\nTán dương, khiển trách, dở, hay\nChẳng làm dao động, nhíu mày trí nhân!",
"82": "Ví như hồ nước thẳm sâu\nLặng yên, trong suốt chẳng màu bợn hoen!\nNhư tâm của bậc trí hiền\nKhi nghe diệu pháp, lòng liền tịnh an!",
"83": "Người hiền, dứt bỏ, xả ly\nThánh nhân mấy chuyện dục si, chẳng bàn!\nHạnh phúc, đau khổ thế gian\nThì bậc thiện trí đâu màng để tâm!",
"84": "Không vì mình, không vì người\nChẳng vì con cái, lộc tài trăm xe:\nLàm điều bất chánh đáng chê\nBậc trí như vậy, Bồ-đề nở bông!\n\nKhông vì mình, không vì người\nChẳng vì sự nghiệp, tiếng đời công danh:\nBởi do bất chánh mà thành\nBậc trí như vậy, đạo hành viên dung!",
"85": "Giữa đám nhân loại dật dờ\nMay ra ít kẻ vượt bờ bến mê\nPhần đông cười, khóc ê chề\nTâm hồn rách nát, kéo lê bờ này!\n\nPhần đông nhân loại dật dờ\nSống say, chết mộng bên bờ bến mê\nQuẩn quanh, xuôi ngược ê chề\nĐảo điên, tất bật kéo lê bờ này!",
"86": "Những ai tinh tấn tu trì\nĐúng theo chánh pháp khéo tri, khéo hành\nVượt qua Ma lực, tử sanh\nThuyền xuôi giác ngạn, mây lành đón đưa!",
"87": "Bỏ nhà, mây trắng ra đi\nThong dong muôn sự, viễn ly thế tình\nPháp đen, pháp trắng phân minh\nRời xa khổ lạc, khinh linh độc hành.",
"88": "Phất tay sở hữu riêng tư\nCầu vui tịch tịnh, chân như Niết-bàn\nGỡ bao chướng ngại sân tham,\nNhiễm ô thanh lọc, xứng hàng trí nhân!",
"89": "Khéo thay! Tu tập giác chi\nLành thay! Chánh hạnh nhiếp trì bền tâm\nNgười không ái nhiễm dục trần\nSống đời sáng chói, Niết-bàn, tại đây!",
"90": "Trải qua suốt cuộc hành trình\nNão phiền chấm dứt, khổ hình tiêu tan\nCởi bao triền phược buộc ràng,\nSống đời siêu thoát, lửa tàn vùi tro!",
"91": "Sa-môn chánh niệm kiên trì\nLìa mọi trú xứ, ra đi nhẹ nhàng\nNgỗng trời cất cánh thênh thang\nAo hồ bỏ lại, mây ngàn thong dong!",
"92": "Rỗng rang tư hữu ra đi\nUống ăn biết đủ, có chi phải bàn?\nTánh không, vô tướng nhẹ nhàng\nChim trời xóa dấu, mây ngàn tìm đâu?\n\nThân không, tài sản cũng không\nBa y dị giản, phiêu bồng chiếc mây\nGiữa hư vời, cánh chim bay\nĐố ai biết hướng Đông, Tây mà tìm!",
"93": "Sa-môn lậu hoặc đoạn ly\nUống ăn chẳng đắm, có chi phải bàn?\nTánh không, vô tướng nhẹ nhàng\nBóng chim xóa vết, thênh thang mây trời!\n\nSa-môn, lậu hoặc cắt rời\nUống ăn vừa đủ, sống đời rỗng rang\nTánh không, vô tướng nhẹ nhàng\nVết chân vị ấy, không gian chim trời!",
"94": "Ví như tuấn mã luyện thành\nLục căn chế ngự, xứng danh trượng tòng!\nNhiễm ô, ngã mạn tiêu vong\nChư thiên mến mộ giống dòng Sa-môn!",
"95": "Đất kia cau mặt bao giờ\nTrụ đồng kiên cố, ao hồ lắng trong\nLuân hồi, vị ấy vượt dòng\nTái sinh vô định, khổ không nào còn!\n\nNhư đất, tâm ý quân bình\nKỷ cương, giới hạnh, thất tình chẳng xao\nTrụ đồng kiên cố khác nào\nChẳng còn nhơ bẩn, hồ ao lắng bùn\nLà người đích đến cuối cùng\nLuân hồi vô định, lao lung chẳng còn!",
"96": "Tâm an thì nghiệp cũng an\nLời ăn, tiếng nói lại càng an hơn\nSống đời tri kiến chánh chơn\nThanh bình siêu thoát, Sa-môn giống dòng!",
"97": "Chỉ tin giải thoát, chánh tri\nChẳng tin ai khác, an vi tự lòng\nCắt lìa hệ lụy trần hồng\nLà người tối thượng, chân không đi về!",
"98": "Thị phường, làng mạc, rừng sâu\nNon cao, lũng thấp hoặc đâu mặc dù\nNơi nào bậc thánh ngụ cư\nỞ đấy khả ái, an như tuyệt vời!",
"99": "Rừng sâu khả ái vô cùng\nChỗ người phàm tục ngại ngùng bước chân\nVì không tìm kiếm dục trần\nBậc “ly tham” sống, mười phần hân hoan!",
"100": "Dẫu cho ngôn ngữ lời ngàn\nMà nghe vô ích, chỉ bàn suông thôi!\nTốt hơn: Một chữ, một lời\nNghe xong tịnh lạc, sống đời vô ưu.",
"101": "Chữ câu ngàn vạn ích gì\nKệ kinh nói mãi, lắm khi loạn mù\nMột câu có ích, cho dù\nNghe xong tịnh lạc, an như đời đời!",
"102": "Trăm câu đọc tụng ích gì\nMáy móc, nhái lại khác chi vẹt, nhồng\nMột lời Phật pháp chánh tông\nNghe xong tịnh lạc, trú dòng bất lai!",
"103": "Vẻ vang, tự thắng chính mình\nKhó hơn thắng vạn chiến binh sa trường\nLành thay! Tâm ý kỷ cương\nChiến thắng tối thượng, phi thường: Thắng ta!",
"104": "Là người chế ngự bản thân\nNgữ ngôn, cử chỉ, tinh cần chăm nom\nThắng mình, nhất định tốt hơn\nTự khéo điều phục, chánh chơn nhân hoàn.",
"105": "Với người tự thắng chính mình\nĐứng cao hơn cả muôn sinh sáu đường\nChư Thiên, Phạm Đế, Ma Vương\nCũng đành chiến bại, vô phương sánh cùng!",
"106": "Trăm năm bỏ cả thời gian\nChí thành tế tự núi vàng, rừng châu\nChẳng bằng giây lát cúi đầu\nCúng dường bậc Thánh, dày sâu phước lành!",
"107": "Trăm năm đốt lửa rừng thiêng\nKhẩn cầu tế tự triền miên đêm ngày\nChẳng bằng chỉ một phút giây\nCúng dường bậc Thánh, sâu dày phước hơn!",
"108": "Suốt năm tế vật cúng dường\nĐể mong phước quả nhờ nương sau này\nPhần tư lợi ích chẳng tày\nMột lần đảnh lễ gót mây Thánh Hiền!",
"109": "An vui, sắc đẹp, sống lâu\nDồi dào sức khỏe: Bốn câu chúc mừng!\nCho ai kính lễ cúc cung\nNhững bậc trưởng thượng thuộc dòng Sa-môn.",
"110": "Trăm năm sống có ích gì\nBuông lung, phóng dật, ác tri, ác tà\nMột ngày trong cõi người ta\nSống có giới định - thật là tốt hơn!",
"111": "Trăm năm sống có ích gì\nBuông lung, phóng dật, ác tri, ác tà\nMột ngày trong cõi người ta\nSống có thiền tuệ - thật là tốt hơn!",
"112": "Trăm năm sống có ích gì\nDể duôi, biếng nhác – li bì xác thân\nKhởi tâm nỗ lực tinh cần\nMột ngày như vậy, muôn phần quý hơn!",
"113": "Trăm năm sống có ích gì\nPháp đi, pháp đến, vô tri chẳng tường\nMột ngày, quả thật khó lường\nThấy pháp sanh diệt, vô thường ra sao!",
"114": "Trăm năm sống có ích gì\nChẳng thấy Bất Tử, vô vi pháp hành\nMột ngày quả thật trọn lành,\nThấy pháp Bất Tử, Vô Sanh rõ ràng.",
"115": "Trăm năm sống có ích gì\nGiáo Pháp tối thượng, chẳng tri, chẳng hành\nMột ngày quả thật trọn lành,\nTu tập Giáo Pháp, cao thanh cõi về!",
"116": "Mau mau làm các việc lành\nMau mau ngăn ác phát sanh tâm người\nTâm người vốn thật dể duôi\nNếu chậm thiện nghiệp, ác chồi ló ra!",
"117": "Hỡi ai điều ác lỡ làm\nLặp đi lặp lại dễ thành thói quen\nĐiều ác, thỏa thích chẳng nên\nChứa ác thọ khổ, lời khuyên đạo tình!",
"118": "Hỡi ai hoan hỷ làm lành\nHãy nên tiếp tục cho thành thói quen!\nĐiều lành thỏa thích, rất nên!\nChứa thiện được lạc, lời khuyên đạo vàng!",
"119": "Người kia làm ác, nghĩ rằng:\nLàm ác được tốt, được hằng an vui\nĐến khi quả dữ chín muồi\nKhổ đau họa hại, rồi đời kẻ ngu!",
"120": "Người kia làm thiện lâu ngày\nVẫn gặp đau khổ, vẫn hay than phiền\nĐủ duyên, quả tốt đến liền\nAn vui, hạnh phúc thiện hiền mến ưa!",
"121": "Nước rơi từng giọt giọt thôi\nLâu ngày chầy tháng đến hồi tràn lu\nChút chút việc ác, mặc dù,\nNgày qua tháng lại, người ngu ác đầy!",
"122": "Nước rơi từng giọt giọt thôi\nKhe mương trăm nẻo đến hồi thành sông\nChút chút việc thiện nhẹ bồng\nMai kia vô lượng hư không cũng tràn!",
"123": "Thương buôn lắm bạc nhiều tiền\nĐồng hành ít ỏi tránh miền hiểm hoang\nMuốn sống, thuốc độc chớ quàng\nLánh ác cũng vậy, rõ ràng là khôn!",
"124": "Tay ta nếu chẳng vết thương\nDẫu cầm thuốc độc chẳng phương hại gì\nÁc kia vô hiệu tức thì\nVới người đức hạnh thường khi niệm lành.",
"125": "Sống đời trong sạch, thiêng liêng\nNếu ai hiểm hại, không điên cũng cuồng\nBụi mù tung ngược gió luồng\nKhổ đau dội lại bằng muôn bằng nghìn!",
"126": "Một số sanh thú thai bào\nBốn đường đau khổ đón chào ác nhân\nNgười lành, thiên giới du nhàn\nCòn người vô nhiễm, Niết-bàn tĩnh cư.",
"127": "Dẫu cho động thẳm hang sâu\nHoặc nơi biển cả, non đầu, rừng thiêng\nChẳng đâu trốn thoát ưu phiền\nLỡ gieo ác nghiệp, khổ liền chạy theo!\n\nTrốn vào động thẳm hang sâu\nẨn trong núi vắng, non đầu, trùng khơi\nCó đâu một chỗ trên đời\nMà quả ác nghiệp lại thôi lần tìm!",
"128": "Trốn vào động thẳm hang sâu\nẨn vào núi vắng, non đầu, trùng khơi\nCó đâu một chỗ trên đời\nTử Thần lại chẳng đến lôi kéo về!",
"129": "Ai ai cũng sợ gươm đao\nAi ai cũng sợ máu đào, thây phơi\nBụng ta suy hiểu bụng người\nChớ nên giết hại, xúi lời giết nhau!",
"130": "Ai ai cũng sợ gươm đao\nNgười người mạng sống mong sao bảo toàn\nBụng ta hiểu bụng thế gian\nChớ nên giết hại, xúi bàn giết nhau!",
"131": "Ai ai hạnh phúc cũng cầu\nTại sao đao trượng hại nhau làm gì?\nTìm an mà lại ác tri\nNhững người như vậy mong chi gặp lành.",
"132": "Ai ai hạnh phúc cũng cầu\nTại sao đao trượng hại nhau làm gì?\nXa lìa ác niệm ấy đi\nBáo thân xả bỏ, tức thì nhàn sanh.",
"133": "Giận nhau, thô lỗ, cộc cằn\nNgười kia trả miếng cũng ngần ấy thôi!\nKhổ thay! Phẫn hận trên đời\nVết thương dao xé: Tiếng lời lại qua!",
"134": "Tự mình nếu biết lặng yên\nKhông còn oán nộ, chẳng hiềm hại ai\nNhư chuông đã bể tiếng rồi\nAi mà được vậy, kề nơi Niết-bàn.",
"135": "Người chăn dùng gậy lùa dê\nLùa từng con một đi về đồng xa\nTuổi già, sự chết cũng là\nLùa từng mạng sống chúng ta xuống mồ!",
"136": "Người ngu ác độc, tội lầm\nVẫn không nhận thức việc làm cuồng si\nNghiệp kia cho quả tức thì\nBị thiêu, bị nấu có chi phải ngờ!",
"137": "Dùng đao hại kẻ “không đao”(11)\nTrượng hại “không trượng”(12) khác nào tự thiêu!\nAi kia thọ khổ mười điều\nChịu quả khốc liệt cùng nhiều tai ương!",
"138": "Một là nhức nhối đau thương\nHai là họa biến, khôn đường trở xoay\nBa là thương tích mặt mày\nBốn là trọng bệnh, thuốc thầy chẳng xong!",
"139": "Năm là tâm trí loạn cuồng\nSáu, bị hại bởi lực quyền vua quan\nBảy, chịu trọng tội cáo oan\nTám là gia quyến các hàng phân ly!",
"140": "Chín là tài sản ra đi\nMười là nhà cửa, lắm kỳ hỏa tai\nĐến khi thọ mạng hết rồi\nChung thân địa ngục đồng sôi, chão dầu!",
"141": "Bằng cách lõa thể lang thang\nHoặc là bện tóc tro than trét mình\nHoặc như bôi mặt bùn sình\nHay là tuyệt thực tóp hình sậy khô\nTu gì đất bẩn nằm co\nLấm lem bụi dính, phết nhơ dọa người?\nNgồi xổm hoặc nhảy loi choi\nNhịn ăn, nín thở sống đời dị nhân!\nẤy là thanh lọc thân tâm?\nHoài nghi trừ diệt, thánh nhân đời này?!\nThan ôi! Khổ hạnh đặt bày\nNhân khổ, quả khổ biết hay trí cuồng?!",
"142": "Người kia dẫu đẹp phục trang\nSống đời thanh tịnh, tĩnh an tục trần\nSáu căn chế ngự tinh thuần\nSống đời phạm hạnh trong ngần pha lê\nBước trên chánh đạo mà về\nTừ tâm vô lượng, chẳng hề trượng đao!\nTỳ-khưu, Phạm chí khác nào\nSa-môn, khất sĩ gọi sao cũng là!",
"143": "Hiếm thay người ở thế gian\nĐã biết tự chế, lại càng tự khiêm!\nBiết hổ thẹn, thoát chê gièm\nNhư con tuấn mã tài hiền tránh roi.",
"144": "Ngựa hiền chỉ thấy bóng roi\nTinh cần, giới đức sáng ngời tín tâm\nĐịnh thiền, trạch pháp, tư tầm\nKiên trì, đạo hạnh trong ngần như gương\nĐủ đầy chánh niệm lên đường\nNhững người như vậy, tai ương tận lìa!",
"145": "Hãy xem dẫn nước, đào mương\nMũi tên khéo uốn thành đường thẳng ngay\nBánh xe tròn đẽo, tài hay!\nHành trì tốt đẹp, xứng thay, tự điều!",
"146": "Sao còn thích thú vui cười\nĐắm say khoái lạc khi đời lửa thiêu?\nBao trùm tăm tối muôn chiều\nKhông tìm đèn sáng, tiêu diêu mà về?",
"147": "Nhìn kia! Thể xác “mê hồn”!\nĐống phân, hầm bệnh lại còn đớn đau!\nMưu toan lo trước, tính sau\nCó chi bền vững mà cầu trường sanh?!",
"148": "Thân này sẽ bị suy già\nThường hay tật bệnh lại hòa uế nhơ\nMỏng manh mạng sống từng giờ\nTử Thần bên cửa, đợi chờ mang đi!",
"149": "Mùa thu nhìn trái bầu khô\nNgười ta quăng bỏ vất vơ xó đường\nNhư bồ câu trắng, trắng xương\nQuý gì, thích thú mà trương mắt nhìn?!",
"150": "Thành trì kẹp cốt, bó xương\nĐắp thêm máu thịt, tô hường, phết son!\nMang thêm tật bệnh, tử vong\nChứa đầy ngã mạn, lại gom dối lừa!",
"151": "Xe vua đẹp đẽ dường bao\nTrang hoàng lộng lẫy, hư hao đến kỳ\nThân này đến lúc lão suy\nPháp bậc Thánh Thiện, vô vi chẳng già!\nDành cho hiền trí gần xa...",
"152": "Kẻ kia kém học, ít nghe\nNở nang, cường tráng, to bè như trâu\nLớn lên, đống thịt lớn mau\nNhưng mà trí tuệ có đâu lớn cùng?!",
"153": "Tìm trong vạn kiếp luân hồi\nVẫn không gặp kẻ xây ngôi nhà này(13)\nLang thang sinh tử đoạ đày!\nKhổ đau tiếp diễn, bèo mây nghìn trùng!",
"154": "Này hỡi anh thợ làm nhà!(14)\nTuổi tên, mặt mũi yêu ma thấy rồi!\nĐòn dông, kèo cột gãy đôi(15)\nRui mè, tre ván, kíp thời phá tan(16)\nTa vô tạo tác lên đàng\nÁi tham tận diệt, Niết-bàn thong dong!",
"155": "Trẻ không sớm biết tu trì\nĐể dành tài sản kíp thì mai sau\nCò già ủ rũ bên ao\nCá tôm chẳng có, hư hao chết mòn!",
"156": "Trẻ không sớm biết tu trì\nĐể dành tài sản kíp thì mai sau\nNhư cung vô dụng gãy đầu\nNhìn về dĩ vãng, muộn sầu thở than!",
"157": "Thương mình phải biết yêu mình\nPhải chăm kẻ trộm rập rình ngày đêm\nBa canh(17), bậc trí chẳng quên\nLuôn luôn tỉnh thức kề bên trông chừng!",
"158": "Tự mình kiên định không sờn\nTự mình củng cố chánh chơn Con Đường(18)\nMới đi giáo hóa muôn phương\nBậc trí như vậy, chẳng vương nhiễm gì!",
"159": "Tự mình tu tập thế nào\nMới mong giáo hóa ra sao cho người\nKhéo thay, chế ngự mình rồi\nMới mong điều phục cõi đời lao xao!",
"160": "Tự ta bảo hộ cho ta\nCó ai nương tựa gần xa mà cầu!\nTự mình chế ngự làm đầu\nKhó khăn điều phục, gắng lâu cũng thành!",
"161": "Việc dữ vốn tự mình sanh\nTự khởi, tự tạo, tự hành ác tri\nNó nghiền nát kẻ ngu si\nKim cương rạch vết, nghĩa gì bảo châu!",
"162": "Như thân dây māluvā\nBám ghì, đeo siết – sāla chết dần\nNếu ta quá nhiễm dục trần\nKẻ thù không giết, tự thân giết mình!\n\nNhư dây leo bám siết cây\nNhánh cành tàn tạ đợi ngày chết khô\nQuá nhiều dục lạc nhiễm ô\nLà ta đã tự đào mồ chôn ta!",
"163": "Những việc xấu quấy, dễ làm!\nHại mình cũng vậy, lại càng quen tay!\nThan ôi! Việc đẹp, việc hay\nTốt lành, lợi lạc, đời này, khó sao!",
"164": "Cũng vì cuồng dại, mê lầm\nNgười kia phỉ báng ân thâm Phật-đà\nCười chê thánh hạnh Tăng-già\nMiệt thị Chánh Pháp thật là chua cay\nBởi do ác kiến sâu dày\nBông tre kết hạt, diệt ngay chính mình!",
"165": "Làm điều ác dữ do ta\nTạo nên ô nhiễm cũng là mình thôi\nTự tôi trong sạch, bởi tôi!\nChẳng ai trong sạch cho người, có đâu!",
"166": "Không vì an lạc cho đời\nChẳng vì lợi ích cho người thế gian\nMà quên tối thượng Con Đàng\nMà quên tự lợi: Niết-bàn chánh tri!",
"167": "Chạy theo phóng dật, chớ nên!\nĐua đòi tham vọng thấp hèn, hay chi?\nTin đâu tà kiến ngu si\nQuý gì nuôi lớn hữu vi tục trần?!",
"168": "Tự nỗ lực, chẳng buông lung!\nThực hành chánh pháp vô cùng trang nghiêm\nCó tu, có chí thì nên\nAn vui, lợi lạc, phúc duyên nhiều đời!",
"169": " Phải theo chánh pháp tu trì\nLìa xa ác đạo, ác tri sai lầm\nChớ theo trược hạnh, ngu nhân\nPhúc lành, an lạc đời gần, đời xa!",
"170": "Hãy xem bọt nước lao xao!\nHãy nhìn ảo ảnh, chiêm bao chập chờn!\nThế gian hoa đốm, mộng trường\nThấy được như vậy, Tử Vương khó dò!",
"171": "Thế gian đẹp đẽ xiết bao\nLong xa mỹ lệ, lụa đào, gấm hương!\nMê nhân chết sững bên đường\nTrí nhân thanh thản, chẳng vương dính gì!",
"172": "Trước kia phóng túng, mê mờ\nNgày sau tỉnh niệm, hướng bờ giác xa\nĐưa tay vén đám mây qua\nVầng trăng ló dạng, nguy nga hạ huyền!",
"173": "Hồi đầu làm các hạnh lành\nXóa mờ ác nghiệp đã sanh thuở nào\nTrí nhân chiếu sáng trần lao\nTrời quang, mây tạnh, trăng sao đời này!",
"174": "Thế gian loáng quáng mù manh\nHiếm thay ít kẻ mắt lành, sáng trong!\nLưới trùm, chim khó thoát lồng\nBay lên nhàn cảnh, thật không mấy người!",
"175": "Thiên nga cất cánh thênh thang\nThần thông bay lượn không gian nghìn trùng\nMa Vương, thắng phục, đã xong!\nBậc trí lìa thoát trần hồng ra đi!",
"176": "Những ai nói dối thành quen\nLàm các việc ác tự nhiên như ruồi\nCười chê, bác bỏ luân hồi\nÁc trí như vậy, đồng sôi, chảo dầu!",
"177": "Làm sao bủn xỉn sanh thiên?\nKhen người rộng lượng, kẻ điên, mong gì!\nTrí nhân bố thí, xả ly\nHỷ hoan lạc báo, có chi phải ngờ!",
"178": "Dẫu cho bá chủ, vương quyền\nHoặc là thượng giới, thần tiên, thiên đàng\nĐịa cầu, chúa tể cao sang\nThua xa, xa tít, dự hàng Thánh Lưu!",
"179": "Vô biên, hành xứ Như Lai!\nChiến bất khả bại(19), chẳng ai sánh đồng!\nVinh thay! Phật giới mênh mông!\nChẳng để vết tích, chân không dính gì!(20)\nVinh thay! Uy lực vô vi!(21)\nCó ai thấy dấu bước đi của ngài?(22)",
"180": "Rối ren, hỗn tạp hết rồi\nÁi dục, triền phược kéo lôi ngõ nào?\nĐi không dấu tích trần lao\nPhật giới tối thượng biết sao mà bàn?\nBước ra khỏi cõi ba ngàn\nMa Vương lần vết xuất phàm được ư?!",
"181": "Trí nhân vui hạnh khước từ\nTinh cần thiền quán, tĩnh cư lòng mình\nChư thiên ái kính, hoan nghinh\nPhật luôn chánh niệm, giác minh tròn đầy!",
"182": "Hiếm thay! Sanh được làm người\nHiếm thay! Sống được một đời lành trong\nHiếm thay! Nghe pháp chánh tông\nHiếm thay! Vị Phật trần hồng Đản Sinh",
"183": "Vui thay! Điều ác không làm\nVui thay! Việc thiện lại chăm làm hoài\nTự tâm thanh lọc trong ngoài\nẤy là giáo huấn ba đời Thế Tôn!",
"184": "Nhẫn kham: Khổ hạnh nhất đời\nNiết-bàn là cõi tuyệt vời, tối cao\nXuất gia không hại người nào\nSa-môn chẳng dính trượng đao giữa đời!",
"185": "Sống đời vô hại, vô vi\nGiới điều thu thúc, hộ trì các căn\nTri túc, dị giản uống ăn\nĐộc cư tịch tịnh, Phật hằng thuyết ngôn!",
"186": "Trận mưa bảy báu đầy tràn\nChẳng làm thỏa mãn ái tham lòng người\nDục khổ nhiều, lạc ít thôi\nChỉ bậc trí hiểu, bẻ mồi câu đi!",
"187": "Cho nên đệ tử Thánh Hiền\nChẳng tìm khoái lạc thần tiên cảnh trời\nHỷ hoan ái dục diệt rồi\nNiết-bàn vắng lặng, nghỉ ngơi vẹn toàn!",
"188": "Loài người hoảng hốt, hoảng kinh\nĐi tìm nhiều chỗ cho mình tựa nương\nVào nơi cây cối, ruộng vườn\nHoặc là đền tháp, núi rừng, miếu hoang!",
"189": "Ấy đâu phải chỗ an toàn\nLà nơi bảo vệ cho hàng trí nhân\nChẳng đâu thoát khỏi mê trần\nChẳng đâu ẩn trốn dấu chân khổ hình!",
"190": "Quy y Phật Bảo quang vinh\nQuy y Pháp Bảo cao minh rạng ngời\nQuy y Tăng Chúng ba đời\nQuy y như vậy, chính nơi hướng về!",
"191": "Chánh tri đâu khổ, đâu mê\nChánh tri Tứ Đế, Bồ-đề tự tâm!\nLần theo Bát Chánh, Giác phần\nVượt qua khổ nạn, mê tân đời này.",
"192": "Quy y ấy quả cao dày\nQuy y tối thượng, đâu tày mà so!\nQuy y tận khổ, vô lo,\nQuy y, giải thoát, thảy đò ngàn sông!",
"193": "Khó thay! Thật hiếm có người\nVĩ nhân hiền thiện ra đời ở đây\nChỉ đâu phúc đủ, duyên đầy\nNơi ấy, bậc trí đợi ngày giáng sinh!",
"194": "Lành thay! Chư Phật giáng sinh!\nLành thay! Chánh Pháp quang minh ba tòa!\nLành thay! Tăng Bảo lục hòa!\nLành thay! Tứ Chúng một nhà đồng tu!",
"195": "Xứng thay! Bậc đáng cúng dường\nThế Tôn, môn đệ các hàng Thanh Văn!\nQuý ngài an tĩnh lục căn\nVượt qua hý luận, tham sân, não phiền.",
"196": "Xứng thay! Bậc đáng cúng dường\nNgười có tuệ giác, thơm hương Niết-bàn\nVô vi, vô uý, tĩnh an\nCúng dường như vậy, cao sang phước mầu.",
"197": "Vui thay! Sống chẳng oán cừu\nGiữa người thù hận, không thù hận ai\nVui thay! Thoát sợ, lìa tai\nVô cùng an lạc, tương lai, đời này!",
"198": "Vui thay! Sống chẳng ốm đau\nGiữa người lắm bệnh, ta đâu bệnh gì!\nVui thay! Chẳng ốm đau chi\nGiữa người ươn yếu, ta thì khỏe không!",
"199": "Vui thay! Sống chẳng rộn ràng\nGiữa người bận rộn: Lạc nhàn, vô vi!\nVui thay! Chẳng khát khao gì\nGiữa người khao khát, ta thì lặng không!",
"200": "Vui thay! Chướng ngại lìa xa\nLà vô sở hữu, chẳng ta, chẳng người!\nSống, ăn pháp lạc tuyệt vời\nTựa như tịnh xứ cõi trời Quang Âm!",
"201": "Chiến thắng nuôi dưỡng hận thù\nCòn kẻ thua, bại - khổ sầu chẳng nguôi\nPhủi tay thắng, bại trên đời\nNgủ ngon, vô sự, ba thời lạc an.",
"202": "Lửa nào so nổi lửa tham?\nÁc nào sánh tựa ác sân hiềm thù?\nKhổ bằng ngũ uẩn, có như?\nLạc nào đổi được vô dư Niết-bàn?\n\nLửa bằng tham ái, có không?\nÁc bằng ác hận, rùa lông dễ tìm!\nKhổ bằng ngũ uẩn, khó tin!\nLạc bằng Tịch Diệt, xem chim mọc sừng!",
"203": "Tối trọng là bệnh đói ăn\nTrầm kha là bệnh các hành(23) rối ren!\nNiết-bàn vô thượng, vô phiền\nHưởng niềm pháp lạc, Thánh Hiền đời nay!",
"204": "Không bệnh: Lợi ích xiết bao!\nVừa lòng, biết đủ: Phú hào bảo châu!\nTín thành: Quyến thuộc hàng đầu\nNiết-bàn: An lạc, nhiệm mầu tối tôn!",
"205": "Ẩn cư, hương vị nếm rồi\nVà vị tịch tịnh, nhiều đời lạc an\nCòn vị Giáo Pháp hỷ hoan\nChẳng còn lo sợ, xấu gian tận lìa.",
"206": "Quý thay! Thấy được Thánh Nhân\nVì ta hưởng được lạc ân của người\nVui thay! Sống ở trên đời\nMà ta chẳng gặp những nòi ngu si!",
"207": "Người ngu, ai đã sống chung\nPhải mang sầu muộn biết chừng nào thôi!\nNgười ngu, bằng hữu lỡ rồi\nBạn thù như thế, kết đôi, lẽ nào?\nVui thay! Bậc trí thanh cao\nSống gần vị ấy, trăng sao đời mình!",
"208": "Trí nhân, thượng sĩ, thánh nhân\nThông minh, giác tuệ, giới phần trang nghiêm\nLàm bạn với bậc Thiện Hiền\nĐường trăng sáng rỡ qua miền đầy sao!",
"209": "(24)\nĐáng làm thì lại bỏ quên\nChăm chuyên những việc chẳng nên chút nào\nThả cho dục vọng tuôn trào\nQuên mục đích chính, lội vào dòng mê!\nĐã không cố gắng quay về\nLại còn ganh tị, cười chê người hiền!\n\nChánh chơn thì lại bỏ bên\nChăm chuyên những việc chẳng nên chút nào!\nXa mục đích, dục tuôn trào\nChạy theo những việc tào lao giữa đời\nLại còn dè bỉu, ỉ ôi\nTỵ ganh những bậc chẳng rời hướng tu!",
"210": "“Thương yêu”(25) thì chớ tìm gần\nKẻ mình chẳng thích, phải cần tránh mau!\nNgười thương không gặp thì sầu\nCòn kẻ mình ghét, mày chau ích gì!",
"211": "Vậy nên chớ có thương ai\nThương người mà phải xa người, khổ thay!\nGhét, yêu – ái khởi, duyên bày\nLìa được yêu, ghét - cởi dây buộc ràng!",
"212": "“Thân yêu” sinh bệnh phiền ưu\nLại sinh sợ hãi, lo âu nhiều bề\nKhông thân yêu, chẳng thích mê\nU sầu, sợ hãi - ê chề trốn xa!",
"213": "“Trìu mến”(26) sinh bệnh phiền ưu\nLại sinh sợ hãi, lo âu nhiều bề\nKhông trìu mến, chẳng thích mê\nU sầu, sợ hãi - cận kề được đâu!",
"214": "“Luyến ái”(27) sinh bệnh phiền ưu\nLại sinh sợ hãi, lo âu nhiều bề\nKhông luyến ái, chẳng đắm mê\nU sầu, sợ hãi - chúng chê dở mồi!",
"215": "“Tham dục”(28) sinh bệnh phiền ưu\nLại sinh sợ hãi, lo âu nhiều bề\nKhông tham dục, chẳng đắm mê\nU sầu, sợ hãi - chán chê chẳng gần!",
"216": "“Dục ái”(29) sinh bệnh phiền ưu\nLại sinh sợ hãi, lo âu nhiều bề\nKhông dục ái, chẳng đắm mê\nU sầu, sợ hãi - đã thề viễn ly!",
"217": "Giới đức, trí giác trọn lành\nKiên cố giáo pháp, đạo hành viên dung\nLàm xong công việc cuối cùng\nTrời, người ái kính, đón mừng hân hoan!",
"218": "Nguyện thành quả vị “ly ngôn”(30)\nChẳng còn xúc động, “thánh môn đầu dòng”(31)\nTế vi các ái tiêu vong\nNhững bậc như vậy xứng đồng “thượng lưu”!(32)",
"219": "Lâu ngày làm khách ly hương\nAn toàn trở lại hỏi đường về thăm\nBà con quyến thuộc xa gần\nBạn bè hoan hỷ, thôn lân đón chào.",
"220": "Ví người hành thiện khác nào\nĐời này, đời nọ xiết bao phước dành!\nĐón đưa tốt đẹp, an lành\nBà con thân thuộc, chân thành mừng vui!",
"221": "Bước qua phẫn nộ, ngã kiêu\nCắt lìa ràng buộc kết neo phận đời\nDanh tâm, sắc tướng xa rời\nKhổ nào theo dính gót người vô sân?",
"222": "Tâm sân bộc phát rất nhanh\nChiếc xe trượt dốc, hãm phanh, khó chừ!\nCó người chế ngự được ư?\nNhư Lai sẽ gọi trượng phu đời này!\n\nAi người chận được tâm sân\nNhư dừng ngay lại xe lăn trượt bờ\nĐánh xe thiện xảo chẳng ngờ\nCòn bao kẻ khác, cầm hờ dây cương!",
"223": "Không sân, chế ngự hận sân\nVới người xấu ác, ta cần tốt vui\nBố thí, diệt xan tham rồi\nLấy đức chân thật, thắng lời dối gian!",
"224": "Chân thật là đức làm đầu\nChẳng nên phẫn hận là câu nằm lòng\nDẫu nghèo vẫn chẳng rít rong\nBa điều tốt ấy – thong dong cảnh trời!",
"225": "Không tổn hại: Bậc hiền nhơn!\nNói, làm, suy nghĩ chánh chơn chế mình\nThấm sâu trạng thái quang minh\nChẳng sầu, chẳng muộn, vô sinh Niết-bàn!",
"226": "Người luôn tỉnh giác ngày đêm\nKỷ cương, tự chế tinh chuyên pháp hành\nTâm chơn hướng cõi Vô Sanh\nBao nhiêu lậu hoặc tan tành còn đâu!",
"227": "Nên biết này A-tu-la!\nĐời này cũng vậy, đời qua khác gì\nNgồi im là bị chúng nghi!\nNói nhiều liền bị chúng khi lắm lời!\nNói vừa cũng bị chê cười\nNói ít vẫn bị miệng người thế gian!",
"228": "Tuy nhiên, định luật bất toàn\nKhông đâu có kẻ được hoàn toàn khen\nHoàn toàn bị chúng chê gièm\nHoàn toàn chẳng có khen luôn, chê hoài!",
"229": "Phải luôn tự kiểm hằng ngày\nBậc trí khen ngợi người hay xét mình\nGiới nghi chẳng chỗ chê khinh\nThanh cao phẩm hạnh, kiến minh tròn đầy.",
"230": "Vị ấy như tấm vàng y\nCó ai lại dám khinh khi các ngài\nChư Thiên, Phạm Đế, loài người\nCũng đều hoan hỷ hết lời tán dương!",
"231": "Giữ thân, phải biết canh phòng,\nGìn thân, bảo vệ hết lòng nay mai!\nXả ly hành ác mới tài\nTrang nghiêm thân hạnh, hỡi ai, mặc dầu!",
"232": "Gìn ngôn, giữ khẩu phải phòng\nKhẩu ngôn bảo vệ hết lòng mới hay!\nXả ly ác khẩu, làm ngay\nTrang nghiêm khẩu hạnh mới tày trượng phu!",
"233": "Gìn tâm, giữ ý phải phòng\nÝ tâm bảo vệ hết lòng mới hay!\nXả ly ác ý, làm ngay!\nTrang nghiêm ý hạnh mới tày trượng phu!",
"234": "Người khôn, biết điều phục thân\nNgăn phòng lời nói do sân ác hành\nThu thúc tâm ý trong lành\nKhéo thay! Toàn hảo ba sanh nghiệp nầy!",
"235": "Thân ngươi, chiếc lá úa tàn\nHái đao Diêm Sứ hiện đang đón chờ\nThan ôi! Chết đến bất ngờ\nĐường xa chẳng có dự hờ tư lương!?",
"236": "Tự xây hòn đảo mà nương\nTinh cần gấp rút dọn đường tuệ tri!\nGỡ bao nhơ bợn ngu si\nMở cửa thánh địa ra đi nhẹ nhàng!",
"237": "Đời ngươi, sự sống sắp tàn\nCứ thêm mỗi bước mỗi gần tử vong\nBên đường, chỗ nghỉ cũng không\nXa xăm chẳng có dự phòng tư lương!",
"238": "Tự xây hòn đảo mà nương\nTinh cần gấp rút, dọn đường tuệ tri!\nGỡ bao dục vọng mê si\nTử sinh quyết chẳng lộn đi, trở vào!",
"239": "Từ từ, chút chút mà hay\nTừng sát-na một gỡ ngay ác mầm!\nThợ vàng lọc bụi trong ngần\nCũng dường thế ấy, chắt dần uế nhơ!",
"240": "Rỉ sét vốn từ sắt sanh\nĂn mòn tiêu hoại rất nhanh sắt nầy\nSống đời lợi dưỡng, biết hay!\nTự nghiệp, tự dẫn trắng tay, khốn cùng!",
"241": "Không tụng niệm: Bợn nhơ kinh!\nKhông siêng năng: Bợn nhơ sinh cửa nhà\nBiếng nhác: Sắc đẹp nhơ nhòa\nCanh phòng sơ hở, bợn trà trộn ngay!",
"242": "Tà hạnh: Nhơ uế đàn bà\nBỏn xẻn: Nhơ uế đàn-na các hàng\nÁc pháp: Nhơ uế thế gian\nĐời này, đời kế ngập tràn khổ đau!",
"243": "Trong hàng cấu uế, dẫn đầu:\nLà vô minh bổn, bợn sâu, dính dày!\nTỳ-kheo khởi tuệ lìa ngay\nThành bậc vô nhiễm, đời này sạch không!",
"244": "Dễ thay! Lỗ mãng, trẽn trơ!\nChẳng lòng hổ thẹn, trộm hờ cắn sau!\nQuạ đen, người – có khác đâu!\nNhững kẻ tự phụ, cứng đầu, kiêu căng\nNhiễm ô, xấc xược, huênh hoang\nSống như vậy đó, dễ dàng lắm ôi!",
"245": "Khó thay! Biết hổ thẹn rồi\nLại còn tinh khiết sống đời trăng gương\nCó tâm dứt bỏ, khiêm nhường\nSáng trong, vắng lặng, tuệ hương ngát ngào!\n\nKhó thay! Biết hổ thẹn rồi\nLại cầu thanh tịnh mà noi hướng về\nVô tư, khiêm hạ, lìa mê\nTrăng trong, sao sáng - đề huề hai vai!",
"246": "Kẻ nào vọng ngữ, sát sanh\nTrộm của thiên hạ, đành hanh vợ người\nRượu men, rượu nấu dể duôi\nTự chôn gốc rễ, nhiều đời vùi sâu!(33)",
"247": 246,
"248": "Hỡi này, những kẻ thiện hiền!\nChế ngự điều ác, chẳng nên khinh thường\nÁi tham, sân hận(34) lỡ vương\nCuốn vào cảnh khổ miên trường đớn đau!",
"249": "Người ta bố thí do tin\nDo tâm hoan hỷ hằng vin pháp lành\nCó người đố kỵ, tỵ ganh\nThức ăn, vật uống dâng dành sa-môn\nNgười như vậy, phước tiêu mòn\nĐịnh tâm không được, sớm hôm não phiền.",
"250": "Hãy mau cắt đứt gốc nhân\nPhải mau nhổ tiệt căn sân, tỵ hiềm!\nNgười như vậy: Bậc trí hiền\nĐạt được tâm định, an thiền tháng năm!",
"251": "Lửa tham hơn lửa đất trời!\nKềm sân vô địch kẹp người, siết ta\nLưới nào bằng lưới si ma?\nSông nào sánh được ái hà dòng sâu?!",
"252": "Lỗi người thì dễ thấy ngay!\nLỗi mình khó thấy, khó hay dường nào\nLỗi người tỉ mỉ bới đào\nTìm trấu trong gạo, đếm sao trời mờ\nLỗi ta, ta giấu, ta ngơ\nLại còn che đậy, giả vờ ngụy trang!\nBẫy chim, ta trốn trong hang!\nChơi bài thì lại dối gian, giấu bài!",
"253": "Những ai chăm thấy lỗi người\nDễ sanh đâm thọc, nói lời gièm pha\nKẻ như vậy, còn rất xa\nXa trừ lậu hoặc, càng xa Niết-bàn!",
"254": "Hư không chẳng có vết chân\nBên ngoài chẳng có xuất trần sa-môn!\nChúng sanh hý luận, đa ngôn\nNhư Lai hý luận sạch trơn, sạch làu!",
"255": "Hư không chẳng có vết chân\nBên ngoài chẳng có xuất trần sa-môn\nCác hành(1) chẳng phải trường tồn\nPhật không dao động, đâu còn hữu vi?",
"256": "Làm quan phải biết công minh\nChẳng nên hấp tấp, lý tình chẳng phân\nCho hay là bậc trí nhân\nPhải, trái thận trọng - thước, cân rõ ràng!",
"257": "Chớ nên thủ thuật dối gian\nPhải theo pháp, luật đàng hoàng phân minh\nChẳng nên chuyên chế ép hình\nSống đúng như vậy, xứng vinh trí hiền!",
"258": "Nghe nhiều, học rộng chương văn\nXứng danh bậc trí giữa Tăng đoàn nầy?\nVô sân, vô úy mới hay!\nMới là cao cả, xứng tay trí hiền!",
"259": "Thuộc lòng giáo pháp, nói nhiều\nMà không trì pháp, gõ kêu rỗng thùng!\nÍt nghe, sở học có chừng\nMà chuyên trì pháp, danh lừng trí minh!",
"260": "Phải đâu trưởng lão sa-môn\nPhải đâu đầu bạc, thượng tôn Tăng đoàn?\nTuổi cao, trí kém, ươn gàn:\n“Sư già rỗng tuếch”(36) xứng mang danh này!",
"261": "Vị nào chân lý lên đường\nTự chế, vô hại, chẳng vương nhiễm gì\nSống đời chánh hạnh, tuệ tri\nXứng danh trưởng lão, xứng vì sa-môn!",
"262": "Phải đâu hùng biện đa tài\nHình dong đẹp đẽ thành người thiện lương?\nSống đời tham ái, dối lường\nThì còn xa lắm con đường trí nhân!",
"263": "Cắt đứt trọn vẹn thúc thằng\nGanh, tham, bứng gốc, ngã căn tận trừ\nDiệt sân, thanh tịnh tâm tư\nNgười như vậy đấy, xứng từ trí nhân!",
"264": "Cái đầu trọc lóc biết chăng\nMà không giới hạnh, nói năng vọng quàng\nLòng đầy tham vọng, dối gian\nNhững kẻ như vậy, xứng hàng sa-môn?",
"265": "Những ai thắng phục dục trần\nĐiều ác lớn, nhỏ - dần dần lặng yên\nChẳng còn nhơ bợn, ưu phiền\nMới xứng tên gọi thiện hiền sa-môn!",
"266": "Chẳng vì bình bát xin ăn\nMà do an tĩnh lục căn, ngũ trần\nSống đời tri túc, tri ân\nMới là khất sĩ, dự phần sa-môn!",
"267": "Với ai thiện, ác vượt qua\nSống đời phạm hạnh, không nhà thiêng liêng\nSuốt thông thế giới đảo điên\nNhững người như vậy, thiện hiền sa-môn!",
"268": "Ngu si, im lặng tịnh bình\nPhải đâu ẩn sĩ, vỗ mình tự khoe?\nCầm cân thiện, ác không mê\nLà bậc trí giả, danh đề xứng tên!\n\nPhải đâu im lặng tịnh bình\nNgười ngu si nọ xưng mình ẩn cư?\nTốt làm, xấu lánh, ai chừ\nLà bậc thiện trí, danh như thánh hiền!",
"269": "Chọn lành, xa ác lâu rồi\nMới là bậc trí, là người ẩn cư\nThế gian thông suốt nhiên như\nMới là hiền thánh, chân sư đời này!",
"270": "Tự xưng cao quý thượng lưu(37)\nMà còn giết hại, oan cừu sinh linh!?\nTừ tâm, vô hại hữu tình\nMới thật cao quý, cao minh cõi người!\n\nTự xưng vô thượng ở đời\nMáu đào họa hại, xương phơi hữu tình!?\nTâm từ rải khắp chúng sinh\nSống đời vô hại, quang minh cao hiền!",
"271": "Chỉ nhờ học rộng, biết nhiều\nĐầu-đà khổ hạnh hay lều ẩn cư\nHoặc do giới luật nghiêm tu\nHay là thiền định công phu sớm chiều\nMà sinh tự mãn, tự kiêu\nTự cho hưởng phúc khước từ, viễn ly!?\nTỳ-khưu chẳng dám nói gì\nKhi chưa đoạn tận tế vi não phiền!",
"272": 271,
"273": "Tối cao: Bát chánh Con Đường!\nTối cao: Tứ đế, tỏ tường khổ ai!\nTối cao: Lìa ái trong ngoài!\nTối cao: Pháp nhãn giữa loài hai chân!",
"274": "Đó là duy nhất Con Đường\nChẳng lối nào khác: “Thanh lương kiến phần”!(38)\nMa vương nhìn ngắm, than thầm\nLo âu, sợ hãi thế nhân đi vào!",
"275": "Lối này nếu quyết đi theo\nÁi hà khô cạn, rong bèo tang thương!\nNhư Lai chỉ dạy Con Đường\nChặt lìa gai chướng, thanh gươm tuệ phần!",
"276": "Ra đi nỗ lực tầm tư\nNhư Lai là bậc Đạo Sư chỉ bày\nAi “tâm đạo lộ”(39) đủ đầy\nMa vương đâu dễ buộc dây kéo hoài!",
"277": "Khi tuệ quán chiếu tỏ tường\nCác hành vốn dĩ vô thường xưa nay\nThoát ly khổ não, đọa đày\nLà Thanh Tịnh Đạo, ai rày chớ quên!",
"278": "Khi tuệ quán chiếu tỏ tường\nCác hành vốn dĩ đau thương, khổ nàn\nThoát ly phiền não, chán nhàm\nLà Thanh Tịnh Đạo, Niết-bàn tìm đâu?!",
"279": "Khi tuệ quán chiếu tỏ tường\nCác pháp vô ngã, chẳng thường là ta\nThoát ly phiền não, ác tà\nLà Thanh Tịnh Đạo, chẳng xa lối về!",
"280": "Tuổi trẻ sức lực dồi dào\nLại sống buông thả, lao chao biếng lười!\nTinh thần suy nhược, rã rời\nLàm sao có Tuệ mà soi Con Đường?",
"281": "Giữ gìn lời nói chánh chơn\nHộ phòng tâm ý trắng trơn sạch làu\nThân quen hành ác, dứt mau!\nBa nghiệp thanh tịnh, đạo mầu chứng tri!",
"282": "Tu thiền thì Tuệ phát sanh\nKhông thiền thì Tuệ mong manh phụt tàn!\nHữu và phi hữu hai đàng(40)\nSuốt thông, nỗ lực dễ dàng Tuệ tăng!",
"283": "Hãy đốn rừng!(41) Chẳng chặt cây!(42)\nLà rừng dục vọng ẩn đầy quỷ ma\nRừng to, rừng nhỏ không tha(43)\n“Không rừng”(44) mà sống, gọi là sa-môn!",
"284": "Cho dầu một bụi cỏn con\nNữ nam ái luyến vẫn còn chồi leo\nÁi kia cứ buộc, cứ đeo\nBê đòi vú mẹ, bám theo, dính hoài!",
"285": "Dây tình xin chớ xót thương\nCắt lìa cành cọng, sen vương thu tàn\nNuối chi những buộc, những ràng\nSống đời an tịnh: Con Đàng Tôn Sư!",
"286": "Mùa mưa ta sống ở đây\nHạ này cũng vậy, thu rày đi đâu?\nNgười ngu tính chuyện dài lâu\nCó nghe sự chết gõ đầu hỏi thăm?",
"287": "Những ai say đắm thế gian\nBám vào con cái, vào đàn vật nuôi\nSự chết cũng cuốn theo người\nNhư làng mê ngủ, lũ trôi chẳng ngờ!",
"288": "Lấy ai để bảo trợ ta?\nHọ hàng con cái hay cha mẹ mình?\nKhi mà sự chết rập rình\nCô đơn chịu nghiệp, vắng thinh chẳng người!",
"289": "Bậc trí biết như vậy rồi\nTự chăm giới hạnh, chẳng rời oai nghi\nDọn đường thanh tịnh, tuệ tri\nSớm thành chánh đạo vô vi Niết-bàn!",
"290": "Xa lìa hạnh phúc nhỏ nhoi\nTìm hạnh phúc lớn để noi hướng về\nLạc nhỏ, bậc trí không mê\nQuyết hái lạc lớn: Bồ-đề tám bông!(45)",
"291": "Cứ gieo đau khổ cho người\nĐể tìm hạnh phúc, nực cười lắm thay!\nKẻ ngu thù hận trói tay\nBị lôi, bị siết, bủa vây oán cừu!",
"292": "Việc đáng thì lại không làm(46)\nViệc không thích đáng(47) lại ham dính vào\nNgười ngu ngã mạn tự hào\nLậu hoặc tăng trưởng khác nào bìm leo!",
"293": "Những người cần mẫn siêng năng\nNiệm thân, quán tưởng thường hằng chẳng lơi\nChỉ làm việc thích đáng thôi\nNgã mạn, lậu hoặc khó mòi nẩy sanh!",
"294": "Sau khi diệt “cha mẹ”(48) rồi\nGiết “hai vua”(49) nọ hết đời hiếu tranh!\nChặt tên “quốc khố đại thần”(50)\nChém bọn “lãnh thổ quan quân tùy tùng”(51)\nĐược rồi quốc độ mênh mông\nBậc vô ưu sống thong dong bốn mùa!",
"295": "“Mẹ cha” đã giết, đã chôn\nVà “hai vua Bà-la-môn”, chém ngành!\nTrị “năm hổ tướng lừng danh”(52)\nBậc vô ưu sống, vô sanh đời đời!",
"296": "Đệ tử đức Gotama\nNgày đêm tỉnh giác, Phật-đà niệm luôn\nÂn đức Phật Bảo cao thâm\nNằm, ngồi, đi đứng - nhất tâm niệm hoài.",
"297": "Đệ tử của đức Như Lai\nNgày đêm tỉnh niệm trọn bài Đạt-ma\nÂn đức Pháp Bảo bao la\nPháp đi, pháp đến - lơ là chẳng nên!",
"298": "Đệ tử của đức Sakyā\nNgày đêm tỉnh giác, Tăng-già niệm luôn\nÂn đức Tăng Bảo thậm thâm\nBa canh, sáu khắc tinh cần không lơi!",
"299": "Đệ tử của đức Thế Tôn\nSắc thân đi đứng, luôn luôn niệm hoài\nThân gồm thể trược ba hai\nNhớ ghi, niệm tưởng trong ngoài chớ quên!",
"300": "Đệ tử của đức Đại Hiền\nVô thù, vô hại chăm chuyên niệm hoài\nTừ tâm rải khắp bốn loài\nAn vui chuyên niệm khuya, mai, tối, chiều!",
"301": "Đệ tử của đức Vô Sanh\nNgày đêm tỉnh giác, trong lành, hỷ hoan\nThân tâm trú niệm chu toàn\nVui đời thiền quán, xứng hàng sa-môn!",
"302": "Khó thay đời sống xuất gia!\nAn vui đời sống không nhà, khó hơn!\nTại gia, phiền não dập dồn\nLại khó hơn nữa, sầu buồn kéo lôi!\nBạn bè không hợp, chán ôi!\nLàm người lữ khách luân hồi, càng thương!\nVậy nên dừng gót đoạn trường\nChạy theo, biết khổ, vẫn bươn chải hoài!",
"303": "Đức tin, giới hạnh đầy tròn\nDanh thơm, tài sản Sa-môn có rồi!(53)\nĐi đâu cũng được đón mời\nCung nghinh, quý trọng phúc trời dám so?",
"304": "Cao cao núi tuyết Hy-ma\nNgười lành cũng vậy, ở xa thấy liền\nMũi tên bay giữa đêm đen\nNhư kẻ xấu ác, ai thèm biết cho!",
"305": "Với ai thích sống cô đơn\nĐộc hành lặng lẽ, chánh chơn tự lòng!\nNgồi, nằm tâm ý thanh trong\nRừng sâu khả ái, thật không phụ người!",
"306": "Người do vọng dối, nói quàng\nChết sanh khổ cảnh thở than nỗi gì?\nKẻ làm, lại chối quách đi\nHai tên một giuộc: Tiện tỳ, tiểu nhân!",
"307": "Xuất gia, tâm chẳng xuất gia\nBao nhiêu xấu ác “trong nhà” còn y!\nLòng đầy hươu vượn sân si\nMở cửa địa ngục mà đi “hưởng nhàn”!",
"308": "Thà rằng sắt đỏ nuốt tươi!\nThà rằng lửa hực, dầu sôi dạ dày!\nCòn hơn ngửa bát trên tay\nĂn nhờ vật thực Đông Tây tín thành\nNgười ngu chẳng niệm điều lành\nThân tâm ác giới, loạn hành nhớ cho!",
"309": "Tà dâm, tà vạy vợ người\nBốn điều bất hạnh đến thời phải vương:\nMột, chịu họa hại tai ương\nHai là khó ngủ, dạ thường lo âu\nBa, đời phỉ nhổ ngập đầu\nBốn đọa địa ngục, đâm xâu, cột đùm!",
"310": "Tội đầy phải vác, phải bưng\nBất hạnh chạy đuổi, còng lưng mà bò!\nKhoái lạc mảnh tợ đường tơ\nLại hoảng, lại sợ - vui so thấm gì?!\nLuật vua, hình trọng kéo đi\nGặt quả khốc liệt, dính chi vợ người!",
"311": "Ai người lấy cỏ kusa?\nNếu tay vụng nắm, thịt da cắt lìa!\nHạnh sa-môn cũng thế kia\nTu hành không khéo, đội bia ngục hình!",
"312": "Một hành, dễ dãi buông lung\nMột tâm ô nhiễm khởi cùng ác tri\nMột thêm phạm hạnh đáng nghi\nCả ba điều ấy, mong gì quả vui?!",
"313": "Có điều phải, hãy nên làm\nTừng bước vững chắc, kiên gan hành trì\nĐời tu sĩ có ra gì:\nDể duôi, tung bụi, càng khi càng mờ!",
"314": "Không nên làm xấu, hay hơn!\nDẫu là ác nhỏ, khổ buồn về sau\nHãy nên làm tốt, làm mau!\nĐiều lành, mai hậu - chẳng cầu cũng vui!",
"315": "Như trên ải trấn biên thùy\nQuan quân bảo vệ, ngăn nguy giặc ngoŕi\nThân tâm phòng hộ, hỡi ai!\nSát-na biếng trễ, “gia tài” còn đâu?\nBỏ qua cơ hội(54) pháp mầu\nĐọa vào địa ngục, khổ sầu chẳng nguôi!",
"316": "Thẹn thùa những việc quàng xiêng\nLại không hổ thẹn chuyện nên thẹn thùa!\nAi người tà kiến vậy kia?\nBàng sanh ác thú, mang hia nhảy vào!",
"317": "Sợ hãi những chuyện gì đâu\nLại không sợ hăi, lo âu đáng điều\nÔm ấp tà kiến ấy nhiều\nNgười ngu đọa khổ, chẳng “siêu” được nào!",
"318": "Không chi, lại thấy lỗi lầm\nLỗi lầm lại nghĩ tầm ngầm là không!\nNgười ngu tà kiến, si ngông\nRớt vào cảnh khổ, đi tong cuộc đời!",
"319": "Việc sai thì bảo rằng sai\nViệc đúng, thấy đúng ai ngoài trí nhân?\nĐi đâu chánh kiến theo chân\nKhói sương khinh khoát – nhàn vân gót hoài!",
"320": "Thớt voi đứng giữa trận tiền\nHứng bao mũi đạn lằn tên sá gì!\nNhư Lai chịu đựng ác tri,\nNhẫn nại phỉ báng, ngu si lòng người!",
"321": "Ngựa voi đã luyện, đã thành\nCon nào thuần nhất để dành vương quân\nCao thượng nhất giữa nhân quần\nChịu đựng phỉ báng, dao đâm tiếng lời!",
"322": "Con la tinh thục, quý thay!\nNgựa kỳ, ngựa ký tung mây, quý là!\nQuý hơn: Voi lớn có ngà\nQuý hơn tất cả: Chính ta tự điều!",
"323": "Lừa, voi hay ngựa tinh thuần\nĐưa ta ngàn dặm đến gần tự do?\nCó người “tự chế con đò”(55)\nNúi sông chẳng ngại, vượt bờ tới nơi!",
"324": "Voi con thân rỉ tanh hôi\nQuay cuồng bất trị đến hồi phát điên\nBỏ ăn, bỏ uống, chảy ghèn\nNhớ rừng, nhớ mẹ bao phen phá chuồng!",
"325": "Những người hôn ám, ngu si\nHam ăn, mê ngủ, li bì thối thây\nHeo no nằm đống cứt nhầy\nThai bào sanh thú kiếp này, kiếp kia!",
"326": "Trước kia phóng túng quen nề\nChạy theo dục lạc, u mê ở đời\nNhưng nay niệm phục được rồi\nNhư dùng móc sắt khiển voi tài tình!",
"327": "Voi kia chân ngập xuống sình,\nKiên trì, nỗ lực tự mình thoát ra!\nSa-môn: Chánh niệm làm “đà”\nKiên trì, nỗ lực nhảy xa khổ đồ!\n\nVoi kia chân bị sa lầy\nKiên trì nỗ lực, thoát ngay khỏi sình\nSa-môn chánh niệm giữ mình\nKiên trì, nỗ lực, khổ sinh bước ngoài!",
"328": "Ra đi trên bước đường đời\nGặp được thiện trí, đáng người làm quen!\nHọc chân thật, học dịu hiền\nKết bằng, vui sống - vượt miền hiểm nguy!\n\nXa xăm vạn lý độc hành\nKết bạn thiện sĩ, phúc lành lắm thay!\nHọc tâm, học trí đủ đầy\nAn vui, chánh niệm - vượt ngay hiểm nghèo!",
"329": "Ra đi trên bước đường đời\nNếu không gặp bạn là người trí nhân\nLà người tuệ hạnh trong ngần\nLà người chánh niệm, ân cần sớm hôm\nThà rằng vững bước cô đơn\nNhư voi chúa nọ, thâm sơn một mình!\n\nXa xăm vạn lý độc hành\nNếu không gặp được bạn lành cùng đi\nSẽ không tăng trưởng tuệ tri\nKhông thêm giới hạnh, khiêm, bi cũng hoài!\nThà rằng cô độc hôm mai\nRừng sâu chúa tể, mình voi hưởng nhàn!",
"330": "Tốt hơn, hãy sống một mình\nNgười ngu kết bạn đồng hành, chẳng nên!\nÁc xa, rời bỏ não phiền\nChúa voi cô độc, vui miền rừng xanh!",
"331": "Vui thay! Gặp bạn lúc cần\nVui thay! Biết đủ, biết ân giữa đời\nVui thay! Tích đức làm rồi\nVui thay! Lánh ác, xa rời khổ đau!",
"332": "Vui thay! Hiếu thảo mẹ già\nVui thay! Hiếu kính ơn cha vẹn toàn\nVui thay! Cúng dường Sa-môn\nVui thay! Phục vụ Thánh Nhơn đời này.",
"333": "Vui thay! Giới hạnh trẻ già\nVui thay! Tín đức trong ta trú lành\nVui thay! Trí tuệ đạt thành\nVui thay! Ác pháp chẳng sanh nẩy chồi!",
"334": "Biết chăng ái dục lòng người\nDây leo nẩy tược, dể duôi khác nào!\nKiếp này, kiếp khác bám vào\nVượn kia ham trái, thấp, cao chuyền cành!",
"335": "Ai người khắng khít đê hèn\nBuông lung ái dục, đua chen dối lừa\nCỏ bīraṇa gặp mưa\nMuộn phiền nảy nở, dây dưa dính chùm!",
"336": "Ai người thiện trí đời này\nTự điều các dục, tự xây thành trì\nNhư nước kia chảy trượt đi\nLá sen chẳng đọng, sầu bi nào còn?",
"337": "Như Lai thường dạy các con:\nVề đây tụ họp, lòng son tín thành\nDục tham bứng gốc cho nhanh!\nNhư đào lấy rễ cỏ tranh khác gì\nĐừng để Ma Vương khinh khi\nNhư cơn tràn lũ cuốn đi rác bèo!",
"338": "Cây kia dẫu bị chặt rồi\nCòn nguyên chùm rễ, vẫn chồi nẩy lên\nNếu chưa nhổ “ái tùy miên”\nMuộn sầu sanh mãi, tương duyên, tương tồn!\n\nCây kia dẫu bị chặt rồi\nCòn nguyên chùm rễ, nẩy chồi lớn mau\nNếu chưa diệt “ái ngủ sâu”\nNó còn sống mãi, khổ sầu sống theo!",
"339": "Ba mươi sáu ái(56) hướng dòng\nBởi do tư tưởng, bởi lòng hỷ tham(57)\nSi mê, tà kiến thế gian\nTheo cơn thác lũ, ngập tràn cuốn đi!",
"340": "Than ôi! Ái dục chảy lan\nDay leo bìm quấn, mọc tràn khắp nơi\nTrí nhân thấy rễ, thấy chồi\nMài gươm tuệ nhãn bén ngời chém phăng!",
"341": "Mỗi khi ái dục phát sanh\nNgũ trần chờ sẵn cuốn nhanh người vào\nMong tìm hỷ ái khác nào\nSanh, già chờ sẵn – gai rào túm chân!",
"342": "Kẻ bị ái dục buộc ràng\nThỏ nằm trong rọ, kinh hoàng xiết bao!\nMong chi tính chuyện bôn đào\nThúc thằng(58) quấn xiết, khổ lao nhiều bề!",
"343": "Kẻ bị ái dục buộc ràng\nThỏ nằm trong rọ, kinh hoàng xiết bao!\nSa-môn thấy rõ khổ lao\nViễn ly ái dục, mở rào, tự do!",
"344": "Đã tìm vui chốn rừng già\nĐể mong thoát khỏi căn nhà thế gian\nNhưng kìa! Chúng lại lộn quàng!\nMái xưa trở lại, buộc ràng hơn xưa!",
"345": "Bậc trí đã dạy như vầy:\nDùng gai hay sắt làm dây chẳng bền!\nNhưng lòng bám víu bạc tiền\nVợ con, vàng ngọc - cố kiên hơn nhiều!",
"346": "Bậc trí đã dạy như vầy:\nSự trói buộc nọ là dây quá bền!\nDẫu tơ mảnh, dẫu lụa mềm\nVấn quấn, vẫn siết, trược phiền thế gian\nXuất gia: Chẳng tiếc, chẳng màng\nCắt lìa, tận diệt, lên đàng thảnh thơi!",
"347": "Những ai tham ái đắm say\nSẽ rơi trở lại loay hoay giữa dòng\nNhện giăng lưới, tự sa tròng\nBậc trí cắt đứt, rỗng không, khước từ!",
"348": "Quá khứ, hiện tại, vị lai\nThảy trôi đi hết, xa ngoài dặm không!\nBỏ thế tình, thoát qua sông\nSao còn lặn hụp giữa dòng tử sinh?\n\nTrôi đi! Dĩ vãng trôi đi!\nTương lai cũng vậy, chẳng gì, trôi luôn!\nHiện tại theo nước chảy suông\nChẳng gì chứa giữ, vui buồn thoảng xa!\nÔi nhân sinh, kiếp người ta!\nPhủi chân tất cả, bước qua cõi này!\nSao đành sanh tử vướng vây?\nBờ kia giải thoát, nước mây thanh bình!",
"349": "Người kia tư tưởng chẳng lành\nNuôi lớn dục lạc, nảy sanh tâm hồn\nÁi tham như nước thông nguồn\nNước càng chảy mãi, ái duồn tăng thêm\nLà dây trói buộc chắc bền\nMà Ma Vương đã xỏ xiên tặng đời!",
"350": "Người kia vui thích niệm lành\nChế ngự dục lạc nảy sanh tâm hồn\nÁi tham, cắt mạch nước nguồn\nNước kia khô cạn, ái còn ẩn đâu?\nBứt dây trói buộc hai đầu\nMa Vương ngơ ngác, trước sau khó tìm!",
"351": "Tới đích, sợ hãi bỏ xa\nDục tham lưu lạc, không nhà mà nương!\nMũi tên sanh tử chẳng vương,\nThân này thân cuối, biết phương nào tìm?\n\nMục tiêu vị ấy đạt rồi\nGỡ hết lo sợ, gỡ mồi dục tham\nMũi tên sinh tử bắn quàng!\nThân này chẳng dính, biết đàng nào truy?",
"352": "Ái không, chấp thủ cũng không,\nNgữ nguyên vô ngại, suốt thông tứ từ(59)\nTrước sau cú pháp nhiên như\nBiện tài, thiện xảo, kinh thư lòng mình\nBậc như vậy quả Vô Sinh\nVĩ nhơn, đại trí, tuệ minh khó lường!",
"353": "Như Lai tất cả vượt qua\nVượt qua trói buộc căn nhà thế gian\nNhư Lai tất cả phục hàng\nThấy rõ tất cả hỗn mang lòng người!\nNhư Lai ái dục diệt rồi\nSuốt thông vạn pháp, sống đời thắng tri\nThoát tất cả, chẳng vướng gì\nNhư Lai ai sánh, nói chi là thầy?",
"354": "Mọi thí, pháp thí vô song!\nHương thơm thù thắng, chẳng đồng pháp hương\nNiềm vui “pháp hỷ” khó lường\nÁi diệt tối thượng, khổ ương tận lìa!",
"355": "Tài sản làm hại người mê\nNhưng không hại kẻ “kết bè” vượt sông!\nTham giàu đã hại mình xong\nCòn dìm kẻ khác trong dòng nước đen!",
"356": "Cỏ dại tai hại ruộng đồng\nÁi tham nhiễm độc giữa lòng thế gian\nQuý thay! Những bậc “ly tham”!\nCúng dường vị ấy, phúc vàng kết xây!",
"357": "Cỏ dại tai hại ruộng đồng\nHận sân nhiễm độc giữa lòng thế nhân\nQuý thay! Những bậc “ly sân”!\nCúng dường vị ấy, phúc ân dồi dào!",
"358": "Cỏ dại tai hại ruộng đồng\nSi mê, nhiễm độc đời không khó gì!\nQuý thay! Những bậc “ly si”!\nCúng dường vị ấy, thắng tri phước mầu!",
"359": "Cỏ dại tai hại ruộng đồng\nÁi dục nhiễm độc chẳng hòng chừa ai!\nQuý thay! Dục ái bỏ ngoài\nCúng dường vị ấy, phúc đài kết hoa!",
"360": "Lành thay! Mắt được hộ phòng!\nLành thay! Tai được “ngắm trông” kỹ càng!\nLành thay! Mũi được an toàn!\nLành thay! Lưỡi được bảo ban, dè chừng!",
"361": "Lành thay! Thân được hộ phòng!\nLành thay! Lời nói giữ không vọng quàng!\nLành thay! Ý được buộc ràng!\nLành thay! Tất cả bảo toàn chẳng lơi!\nTỳ-khưu muốn thoát khổ đời\nCanh phòng mọi điểm khắp nơi, trọn mình!",
"362": "Tay chân đã chế ngự rồi\nThu thúc tâm ý, nói lời chánh chơn\nVui thích thiền định, cô đơn\nTri túc, dị giản - keo sơn chẳng rời\nĐến đi chẳng dính bụi đời\nSống được như vậy, rạng ngời tỳ-khưu!",
"363": "Thu thúc miệng lưỡi thiện tài\nNói năng khéo giỏi, khoan thai, dịu dàng!\nNghĩa kinh, thông giảng giọng vàng,\nChẳng kiêu, chẳng mạn - xứng hàng tỳ-khưu!",
"364": "Ẩn cư trong Giáo Pháp này\nThỏa thích Giáo Pháp, suy ngày, tưởng đêm\nTỳ-khưu như vậy đáng khen!\nGiáo Pháp cao thượng kề bên chẳng lìa!",
"365": "Vật mình thọ, thì coi khinh\nPhần người có được lại sinh muốn thèm\nTham, ganh xao động chẳng yên\nTỳ-khưu như vậy, định thiền khó thay!",
"366": "Dầu được chút ít vật thôi\nHằng luôn biết đủ, quý người, trọng ân\nTỳ-khưu chánh mạng nuôi thân\nChư thiên ái kính, xa gần tán dương!",
"367": "Không chấp ta và của ta\nThân tâm thấy rõ chỉ là sắc danh\nVật không có, chẳng tham ganh\nNgười như vậy đấy, xứng thành tỳ-khưu!",
"368": "Tỳ-khưu ẩn náu tâm từ\nHỷ hoan giáo pháp, an như, tín thành\nChứng đạt trạng thái trong lành\nThấy rõ tịch tịnh các hành hữu vi!",
"369": "Rỗng không, thuyền tát nước rồi\nTừ đây lướt sóng, chèo bơi nhẹ hều!\nTham sân theo đám rong bèo\nXuôi sang bờ giác, tỳ-kheo xứng người!",
"370": "Cắt đứt năm(60), dứt bỏ năm(61)\nTỳ-khưu năm lực, năm căn(62) trau dồi\nCởi năm dây trói buộc(63) rồi\nBốn dòng lũ lớn muôn đời, vượt qua!",
"371": "Hỡi tỳ-khưu! Hãy tham thiền\nBuông lung dục lạc phải nên dè chừng!\nNếu nuốt cục sắt đỏ hừng\nĐịa ngục thiêu đốt, nhớ đừng khổ than!",
"372": "Không trí tuệ, không định thiền!\nKhông định thiền, biết tuệ duyên chỗ nào?\nNiết-bàn giải thoát tối cao\nĐầy đủ định tuệ, bước vào gần bên!",
"373": "Tỳ-khưu ẩn náu cô đơn\nGiữa lòng an tĩnh, chánh chơn ly trần\nDưỡng nuôi phỉ lạc siêu nhân\nQuan sát giáo pháp, rõ dần tuệ minh.",
"374": "Hằng chuyên quán niệm tự thân\nPháp sanh, pháp diệt thấy gần, thấy xa!\nVui thay! Các uẩn tiêu ma!\nGõ cửa “bất tử”, vào nhà “vô sanh”!",
"375": "Tỳ-khưu có trí, có cần\nTri túc, tự chế, lục căn bảo toàn\nThu thúc giới bổn nghiêm trang\nVật dùng chánh mạng, bạn vàng kết giao\nTấn ích, lợi lạc xiết bao!\nThân tâm thanh tịnh - phiền lao nào còn?",
"376": "Khi giao tiếp, lúc vào ra\nKhiêm hư, thuần hậu, nết na tiếng lời\nHỷ an, niệm niệm chẳng dời\nTâm hồn không bợn, một đời vô ưu!\n\nTiếp giao thân thiện mọi người\nĐoan trang, nho nhã, ý lời thanh tao!\nHỷ an, niệm niệm ngọt ngào\nTâm hồn không bợn, khổ lao tận lìa!",
"377": "Như cành hoa vassikā\nTự quăng bỏ lấy cánh già úa hương\nChư tỳ-khưu cũng như dường\nTham sân tước cọng, chẳng thương cọng nào!",
"378": "Những người thân, khẩu tĩnh an\nÝ cũng an tĩnh, khéo nhàn, khéo tu!\nBỏ xa thế sự bụi mù\nLà bậc Tịch Tịnh, xứng từ tỳ-khưu!",
"379": "Con ơi! Hãy cứ thật tình\nTự tri, tự kiểm xét mình mới hay!\nCanh phòng giác tỉnh đêm ngày\nChánh niệm được lạc, có ngay, chẳng cầu!",
"380": "Chỉ ta mới bảo vệ ta\nChỉ ta nương tựa, chẳng là khác ai!\nTự mình điều phục miệt mài\nNhư khách buôn ngựa, khéo tài kềm cương!",
"381": "Niềm tin giáo pháp tín thành\nThọ hưởng phỉ lạc, trong lành, hân hoan\nCác hành vắng lặng, rỗng rang\nHạnh phúc tối thượng, Niết-bàn tự tâm.",
"382": "Tỳ-khưu nhỏ tuổi mặc dầu\nTự thân cần quán, pháp mầu siêng tu\nVầng trăng thoát đám mây lu\nChiếu soi rỡ rỡ, cõi mù thế gian!",
"383": "(64)\nHỡi này! Người bà-la-môn!\nHãy mau tinh tấn, cắt dòng mà đi!\nBao nhiêu ái dục viễn ly\nKhông còn tạo tác, vô vi, vô hành!",
"384": "Khi người tuệ, định đủ đầy\nBờ kia sẽ đạt, ở đây, tức thì!\nBao nhiêu thằng thúc đoạn ly\nBà-la-môn đã liễu tri tỏ tường!",
"385": "Bên này sông, bên kia sông,\nCả hai không có, cũng không bờ nào!\nThoát ly phiền não buộc rào\nBà-la-môn gọi, đúng sao, danh người!",
"386": "Tu thiền ly nhiễm, vô trần\nSống đời ẩn dật, tinh cần sớm hôm\nHoàn thành mục đích chánh chơn\nNhư Lai gọi, bà-la-môn, chính người!",
"387": "Mặt trời chiếu sáng ban ngày\nMặt trăng soi rạng nước mây đêm dài\nGươm đao, nhung giáp ngời ngời\nĐức vua, quân lính khắp nơi trận tiền\nBà-la-môn lúc định thiền\nÁnh sáng rực rỡ xóa miền tối đen\nNhưng vinh hạnh suốt ngày đêm\nHào quang đức Phật vô biên, vô ngần!",
"388": "Dứt ác gọi bà-la-môn\nSống đời an tịnh – sa-môn chính là!\nTự mình cấu uế lìa xa,\nTu sĩ ẩn dật, “xuất gia”, đúng từ!",
"389": "Đánh đập Phạm Chí(65), không nên!\nPhạm Chí đánh trả không kềm nổi sân!\nNgười đánh xấu hổ một phần\nCòn người đánh lại, nhiều lần xấu hơn!",
"390": "Phạm Chí không trả thù ai\nLà điều lợi ích lâu dài về sau!\nKhi dứt ái luyến, vọng cầu\nTâm hại chận đứng, khổ sầu tự tiêu!",
"391": "Với người ba nghiệp ác xa\nLà thân khẩu ý ôn hòa, vô vi\nNgày đêm tỉnh giác hộ trì\nBà-la-môn ấy, đúng vì danh xưng!",
"392": "Hiểu thông giáo pháp nhờ ai\nTừ bậc Toàn Giác, Như Lai giáo truyền\nNhư Phạm Chí thờ lửa thiêng\nTa phải thành kính khắc tên đá vàng!",
"393": "Chẳng vì bện tóc, thọ sanh\nChẳng vì giai cấp, thanh danh gia đình\nVới ai chánh hạnh, tuệ minh,\nBà-la-môn ấy, xứng vinh gọi là!",
"394": "Người ngu kia có ích gì,\nĐầu thì bện tóc, áo thì da dê?!\nBên trong ác uế, u mê\nBên ngoài trang sức nếp nề chơn tu!?",
"395": "Đắp y vải lượm bên đường\nGân xanh lồ lộ, trơ xương, ốm gầy\nRừng sâu, thiền định tháng ngày\nCô đơn Phạm Chí, ai tày danh xưng?",
"396": "Phải đâu do mẹ cha sanh\nThai bào dòng giống mà thành bla-môn?\nNó chỉ là tên gọi suông\nNíu đeo cấu uế, nối guồng dục tham\nKhông phiền não, chẳng buộc ràng\nMới là Phạm Chí, dự hàng chân tu!",
"397": "Cắt đứt rễ má, dây mơ\nĐoạn lìa trói buộc, chẳng lo sợ gì\nVượt xa dính mắc hữu vi\nNhư Lai sẽ gọi, đúng vì bla-môn!",
"398": "Bỏ dây nọng(66), bỏ dây cương(67)\nĐai da cùng với sợi thừng thèo leo!(68)\nĐập tan trục, chốt buộc đeo(69)\nBla-môn, Phạm Chí - tên theo đúng người!\n\nBỏ dây cương, bỏ đai da\nBỏ luôn dây nọng, giết Ma ngủ ngầm!\nĐập tan trục, chốt ngu đần\nLàm người sáng suốt, dự phần bla-môn!",
"399": "Người không tức giận bao giờ\nTrước lời phỉ báng: Lặng tờ, nín thinh!\nDẫu cho roi trượng phạt hình\nLấy đức nhẫn nại làm binh hộ phòng\nTâm từ rải khắp hư không,\nNhững kẻ như vậy, xứng dòng bla-môn!",
"400": "Người mà vô hận, vô sân\nLàm tròn bổn phận, tự tâm, tự điều\nLà thân cuối, sống tiêu diêu\nĐúng bậc Phạm Chí, chẳng nhiều lắm đâu!",
"401": "Lá sen chẳng giữ mưa sa\nĐầu kim chẳng dính hạt hoa cải vàng\nVô y, vô nhiễm thế gian\nNhững người như vậy, xứng làm bla-môn!",
"402": "Ở đây, ở thế gian này\nAi người thấy khổ, diệt ngay khổ sầu\nBỏ gánh nặng xuống bên cầu\nSống đời siêu thoát, đứng đầu bla-môn!",
"403": "Người có trí tuệ thâm sâu\nNẻo tà, đường chánh - đâu đâu cũng rành\nĐạt thông tối thượng pháp hành\nNhững người như vậy, trọn lành bla-môn!",
"404": "Xuất gia, thế tục hai hàng\nĐến đi chẳng luyến, dặm ngàn thong dong\nCô đơn, thiểu dục bên lòng\nNhư Lai sẽ bảo, xứng dòng bla-môn!\n\nXuất gia, cư sĩ chẳng thân\nNon xanh vô ngại, dặm trần an như\nGió xao chẳng gợn tâm tư\nCô đơn, thiểu dục, đúng từ bla-môn!",
"405": "Trượng đao vị ấy bỏ rồi\nChúng sanh vô hại, với đời vô sân\nCũng không xúi bẫy hại ngầm\nLòng từ quảng đại, chẳng lầm bla-môn!",
"406": "Thân thiện giữa đám nghịch thù\nVới người hung dữ, ôn nhu, ôn hòa\nSống vô nhiễm giữa trần sa\nNhững vị như vậy, chính là bla-môn!",
"407": "Tham sân chẳng dính vào lòng\nNgã kiêu, tật đố thảy dòng nước trôi\nHạt cải kia - đầu kim rơi!\nNhững người như vậy, sống đời bla-môn!",
"408": "Nói lời chẳng mất lòng ai\nDựng xây, chân thật, hòa hài, ôn nhu\nNói lời thâm thiết, bi từ\nBla-môn là vậy, đúng như danh người!",
"409": "Vật kia dầu ngắn hay dài\nDầu to hay nhỏ của ai chẳng màng\nXấu, tốt không lấy, không ham\nNhững bậc như vậy, xứng làm bla-môn!",
"410": "Rỗng không, chẳng một hy cầu\nĐời này, đời kế chẳng đâu bận lòng\nThảnh thơi, siêu thoát trần hồng\nNhững người như vậy, đúng dòng bla-môn!",
"411": "Người mà tham ái tiêu vong\nDo nhờ trí tuệ đoạn lòng hoài nghi\nThể nhập bất tử, vô vi\nNhư Lai sẽ gọi, đúng vì bla-môn!",
"412": "Người đã vượt thoát hai điều\nCả thiện và ác, tiêu diêu cõi ngoài\nKhông bụi bặm, chẳng sầu ai\nNhững người như vậy, trí tài bla-môn!",
"413": "Lòng kia không bợn, sạch làu\nSáng trong, vắng lặng, vui sầu chẳng xao\nÁi và thủ, hữu vẫy chào\nBla-môn là vậy, ai nào khác đâu!\n\nVũng lầy nầy đã bước ra(70)\nCon đường nguy hiểm thoát xa hồi nào(71)\nĐại dương đời sống dạt dào(72)\nXuyên qua, đi khỏi ba đào sân si(73)\nCắt lìa ái dục, hoài nghi\nTịch tịnh, vô trước, thoát ly mọi miền\nChẳng còn đâu nữa “tùy miên”\nNhững bậc như vậy, vinh hiền bla-môn!",
"415": "Ai người bỏ dục đi ra\nKhước từ đời sống căn nhà thế gian\nDục hữu - đốt cháy tiêu tan!\nNhững bậc như vậy, dự hàng bla-môn!",
"416": "Ai người bỏ ái đi ra\nKhước từ đời sống căn nhà thế gian\nÁi hữu - đốt cháy tiêu tan\nNhững bậc như vậy, đồng hàng bla-môn!",
"417": "Lìa xa ràng buộc cõi người\nLìa luôn dính mắc cõi trời cao sang\nThoát bao cám dỗ huy hoàng\nNhững bậc như vậy, ngồi hàng bla-môn!",
"418": "Thản nhiên: Ưa, ghét - hai bờ!(74)\nSanh y(75) lìa đoạn, lặng tờ tâm tư\nThế gian(76), chiến thắng trượng phu!\nBla-môn tên gọi, cho dù là ai!",
"419": "Là người hiểu biết hoàn toàn\nSự sống, sự chết các hàng chúng sanh\nKhông ái luyến, đào thoát nhanh\nTự mình giác ngộ, xứng dành bla-môn!",
"420": "Đã lậu tận, dứt sanh y\nChấm dứt thọ mạng ra đi phương nào?\nChư thiên dẫu thấp hay cao\nDạ-ma, nhân loại biết sao mà lần?\nLà La-hán, là Thánh Nhân,\nLà bậc tối thượng, xuất trần bla-môn!",
"421": "Ai mà quá, hiện, vị lai\nSống không sở hữu, trong ngoài sạch lau\nSạch lau cũng chẳng mắc câu\nNhững người như vậy, đứng đầu bla-môn!",
"422": "Ví như trâu chúa kiên hùng\nĐại sĩ, vô úy, vô cùng quý cao\nBậc chiến thắng cả trần lao\nTuệ tri, giác ngộ - khác nào bla-môn!",
"423": "Ai đời trước thấy rõ ràng\nCảnh khổ đọa xứ, cảnh nhàn chư thiên\nĐã tận sanh diệt các miền,\nTrí tuệ cao viễn tự viên, tự thành\nMâu-ni, đạo sĩ đã đành\nLà bậc Bất Tử, tên dành bla-môn!"
  },
  "notes": {
    "1": "Theo Abhidhamma thì ý (mano), thức (viññāṇa), tâm (citta)... đồng nghĩa; nhưng tôi chọn dịch là tư tác (cetanā) – vì tư tác mới là nghiệp. Từ trước đến nay, nhiều nơi bảo tác ý (manasikāra) là nghiệp; không phải vậy, tác ý mới chỉ là hướng tâm, như bánh lái của chiếc thuyền. Trong 7 biến hành tâm sở (Duy Thức chỉ 5): Xúc, tác ý, thọ, tưởng, tư, nhất tâm, mạng căn – thì chính tư (tư tác-cetanā) mới quan trọng, mới tạo nghiệp; sau đó, các lộ trình tâm mới khởi theo – chúng đồng khởi. Tuy nhiên, nếu dịch là tâm hay ý đều không sai, vì ý, tâm, tư tác - được coi là tâm và các pháp (dhammā), hai từ đầu trong câu kệ, chính là những tâm sở (theo chú giải).",
    "2": "Câu Pāli tương ứng có nghĩa: Sống mà hằng suy nghĩ đến lạc thú (nhìn tịnh tướng).",
    "3": "Kiết thừng: Dây trói buộc.",
    "4": "Trú xứ ẩn mật của Thức.",
    "5": "Ngũ ma.",
    "6": "Ý nói về dục vọng.",
    "7": "Tuệ minh sát",
    "8": "Không ái luyến, không đeo níu những bậc thiền đã đạt được; an trú trạng thái ly tham, vô ái, Niết-bàn.",
    "9": "Kinh pháp cú, kinh lời vàng, Phật ngôn, bát chánh đạo, giáo pháp.",
    "10": "Từ Tu-đà-hoàn đến A-na-hàm.",
    "11": "Hàm chỉ bậc Thánh.",
    "12": "Hàm chỉ bậc Thánh.",
    "13": "Ngôi nhà ngũ uẩn.",
    "14": "Ái (Taṅhā)",
    "15": "Thân (Kāya)",
    "16": "Phiền não (Kilesa)",
    "17": "Chú giải nói, ba canh là ba giai đoạn của đời người: Thiếu, trung và lão.",
    "18": "Magga: Đạo.",
    "19": "Cuộc chiến thắng tham, sân, si.",
    "20": "Mọi vết tích của hữu vi, phiền não.",
    "21": "10 Phật lực, 9 hồng danh.",
    "22": "Giải thoát ngoài 3 cõi, không còn dấu vết tâm hành.",
    "23": "Saṅkhāra: Hành trong 12 duyên khởi, trong ngũ uẩn.",
    "24": "Cần phân biệt một số từ có từ gốc “Ái”, đó là piya, pema, rati, rāgī, rāga, kāma, taṇhā... Piya, pema thường dùng trong nghĩa thương yêu, trìu mến, thân yêu, thương mến, yêu quý, yêu mến... là những tình cảm tốt đẹp trong đời thường như cha mẹ, vợ con, bằng hữu, xóm làng, quê hương... Rati, rāgī, rāga được dùng khi tình cảm đã sâu nặng, như quyến luyến, luyến thương, ái luyến đưa đến dục tình, tình dục... Kāma thì thuộc về tất cả dục ngũ trần, thuộc dục giới. Taṅhā là ái, ái dục nằm trong 12 duyên khởi; khi nó thích thì yêu, thương, tham - khi không thích thì sinh ra ghét, chán, sân. Tuy nhiên, dù thương, dù ái kiểu gì thì cũng đem đến buộc ràng, đau khổ... như tham, thương nhiều thì khổ nhiều; tham, thương ít thì khổ ít vậy (Đây là sự thấy biết riêng, có tính chủ quan của soạn giả, có thể chưa được chính xác hoặc có một vài sai sót nào đó, xin các bậc thức giả, trí giả hiểu cho).",
    "25": "Piya: Thân yêu, yêu quý, thương mến...(có từ gốc Ái dục – taṇhā); nó là tình thường trong đời sống, chưa quá đà, chưa có tội lắm, nhưng cũng phát sanh khổ.",
    "26": "Pema: Thương yêu, trìu mến...; cũng có từ gốc taṇhā – ái dục; là tình cảm tốt trên cuộc đời như thương vợ, thương con; chưa có tội lắm nhưng cũng đưa đến phiền não.",
    "27": "Rati: Luyến ái, phát sanh dục tình – có từ gốc Ái dục - taṇhā, từ đây mới phát sanh vấn đề cần phải được nhìn ngắm. Cao hơn một cấp độ nữa là Rāga: Tình dục, gốc của luân hồi.",
    "28": "Kāma: Tham muốn thoả mãn ngũ dục, nói chung là cõi dục giới, có từ gốc Ái dục - taṇhā.",
    "29": "Taṇhā: Ái Dục, nằm trong 12 duyên khởi, gốc của sinh tử luân hồi. Từ Taṇhā này, cái gì được thì tham, thương; cái gì không được thì sân, ghét.",
    "30": "Chỉ Niết-bàn.",
    "31": "Chỉ 3 quả vị đầu là Tu-đà-hoàn, Tư-đà-hàm, A-na-hàm.",
    "32": "Chỉ A-la-hán.",
    "33": "Ý nói là tự chôn gốc rễ của mình mãi mãi trên thế gian này, không bao giờ lìa thoát được.",
    "34": "Adhammo: Phi pháp, nghịch nghĩa với pháp; nghĩa là không đi theo giáo pháp – nhưng chú giải cho nghĩa là sân hận vì tham và sân là căn nguyên của điều ác.",
    "35": "Saṅkhāra: Tôi dịch là hành chứ không dịch là hữu vi – vì tâm hành là tâm lăng xăng tạo tác, nó ở trong 12 duyên khởi; còn hữu vi là thường chi tất cả các pháp được kết hợp, cấu tạo của thế giới gồm chung tinh thần, vật chất, của sum la vạn tượng.",
    "36": "Mogha: Rỗng không; jiṇṇa: già lão, già yếu... Nên có thể dịch là “lão ngu” hoặc “lão già vô vị”; nhưng tôi dịch là “sư già rỗng tuếch” là đúng với ý của sự khiển trách trong câu này.",
    "37": "Ariya: Cao quý, cao thượng, quý phái... mà cũng có nghĩa là bậc thánh nhân.",
    "38": "Dassanassa visuddhiyā: Với cái thấy thanh tịnh (Tri kiến thanh tịnh).",
    "39": "Người thực hành bát chánh đạo.",
    "40": "Hai đàng: Rõ thông định và tuệ; tham và sân; thiền sắc giới và vô sắc giới; hữu (hữu ái), phi hữu (phi hữu ái).",
    "41": "Rừng dục vọng.",
    "42": "Theo chú giải, khi đức Phật dạy “hãy đốn rừng”, có một số vị tỳ-khưu hiểu theo nghĩa đen, nên ngài phải nói tiếp là “không chặt cây” – vì rừng là rừng dục vọng, không phải là rừng cây thật.",
    "43": "Dục, nhiễm ô lớn nhỏ.",
    "44": "Không còn dục vọng, nhiễm ô.",
    "45": "Bát chánh đạo.",
    "46": "Việc thích đáng: Như giới, định, tuệ.",
    "47": "Việc không thích đáng: Chăm sóc cái thân, trang trí y bát, dù dép; lo việc ở ngoài đời...",
    "48": "Mātu: Mẹ, tiêu biểu cho tâm ái dục (taṇhā); pitu: Cha, tiêu biểu cho ngã mạn, cố chấp, cứng đầu, kiêu căng, tự phụ, hống hách... ",
    "49": "Hai vua: Thường kiến và đoạn kiến.",
    "50": "Người phụ trách kho tàng của vương quốc – ý nói cái tâm ái luyến bám bíu vào đời sống.",
    "51": "Ý nói lục căn và lục trần.",
    "52": "Là năm chướng ngại tinh thần (5 triền cái): Hôn trầm, thuỵ miên, nghi; sân ác; trạo hối; tham dục.",
    "53": "Gia tài thánh hạnh.",
    "54": "Cơ hội: Có Phật đản sanh, có giáo pháp, có thiện trí thức, có chánh kiến, có nơi ở thuận lợi, có ngũ quan đầy đủ, thân thể khoẻ mạnh",
    "55": "Tự tu, tự hành thập độ để huân tụ pháp lành.",
    "56": "Ái dục (taṇhā): 6 ái dục có từ 6 căn; 6 ái dục có từ 6 trần - tức là 12 ái dục; cộng với 3 thời quá khứ, hiện tại, vị lai thành ra 36 loại ái dục.",
    "57": "6 căn ái tham, hỷ tham ngũ trần.",
    "58": "Thằng là sợi dây; thúc là bó buộc.",
    "59": "Đạt tuệ phân tích, tứ vô ngại giải.",
    "60": "Năm hạ phần kiết sử: Thân kiến, hoài nghi, giới cấm thủ, tình dục, bất bình.",
    "61": "Năm thượng phần kiết sử: Sắc ái, vô sắc ái, ngã mạn, phóng tâm, vô minh.",
    "62": "Ngũ căn, ngũ lực: Tín, tấn, niệm, định, tuệ.",
    "63": "Tham, sân, si, mạn, tà kiến.",
    "64": "Trong phẩm nầy, từ brāhmaṇa (bà-la-môn) đồng nghĩa với samaṇa (sa-môn) đều là bậc thanh tịnh, vắng lặng - ở đây đức Phật muốn chính danh lại nghĩa đúng đắn của một bà-la-môn chơn chánh, do vào thời ấy, giới bà-la-môn đã hành trì quá sai lạc.",
    "65": "Là một cách phiên âm khác của brāmaṇa.",
    "66": "Tà kiến",
    "67": "Sân hận",
    "68": "Luyến ái.",
    "69": "Tuỳ miên kiết sử và vô minh.",
    "70": "Vũng lầy tham ái.",
    "71": "Con đường dục vọng.",
    "72": "Vòng luân hồi trầm luân sinh tử.",
    "73": "Xuyên qua, vượt thoát 4 dòng lũ: Dục lậu đưa đến dục bạo lưu (kāmogho); hữu lậu đưa đến hữu bạo lưu (bhavogho); kiến lậu đưa đến kiến bạo lưu (diṭṭhogho); vô minh đưa đến vô minh bạo lưu (avijjogho).",
    "74": "Ưa thuộc tham, ghét thuộc sân; tham sân là gốc của ái (taṇhā).",
    "75": "Nương tựa mà sanh khởi, bám víu vào đời sống",
    "76": "Loka: Thế gian, nội giới cũng như ngoại giới; ở đây hàm chỉ ngũ uẩn."
  }
}
